//
// ExperimentsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ExperimentsAPI {

    /**
     Create an experiment
     
     - parameter createExperimentRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: CreateExperimentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createExperiment(createExperimentRequest: CreateExperimentRequest, xProjectId: String? = nil) async throws -> CreateExperimentResponse {
        return try await createExperimentWithRequestBuilder(createExperimentRequest: createExperimentRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Create an experiment
     - POST /api/admin/experiments
     - Creates a new experiment in `draft` status. `name`, `universe`, and `groups` are required; everything else has sensible defaults.  Returns `409` if `name` already exists, `422` if the named universe doesn't exist, `403` if a plan-gated option is set (`sequential_testing`, custom `significance_threshold`) on a plan that doesn't include it.  **Use cases**  - **Minimal 50/50** — `name` + `universe` + two equal-weight groups. - **Targeted rollout** — supply `targeting_gate` to restrict the eligible audience and `allocation_pct` to enrol a slice of it. - **Multivariant** — three or more groups with weights summing to 10000. - **Sequential testing** — `sequential_testing: true` for Premium plans.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter createExperimentRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<CreateExperimentResponse> 
     */
    open class func createExperimentWithRequestBuilder(createExperimentRequest: CreateExperimentRequest, xProjectId: String? = nil) -> RequestBuilder<CreateExperimentResponse> {
        let localVariablePath = "/api/admin/experiments"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createExperimentRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateExperimentResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete an experiment
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: DeleteExperimentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteExperiment(id: String, xProjectId: String? = nil) async throws -> DeleteExperimentResponse {
        return try await deleteExperimentWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Delete an experiment
     - DELETE /api/admin/experiments/{id}
     - Archives the experiment (soft-delete via status transition). Returns `409` if the experiment is still `running` — stop it first.  **Use case:** Tear down an experiment after the analysis is signed off.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<DeleteExperimentResponse> 
     */
    open class func deleteExperimentWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<DeleteExperimentResponse> {
        var localVariablePath = "/api/admin/experiments/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteExperimentResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get one experiment
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetExperimentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getExperiment(id: String, xProjectId: String? = nil) async throws -> GetExperimentResponse {
        return try await getExperimentWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Get one experiment
     - GET /api/admin/experiments/{id}
     - Returns the full experiment row including groups, params, allocation, and lifecycle timestamps.  **Use case:** Fetch one experiment to render the detail page or to inspect its current allocation and group weights.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetExperimentResponse> 
     */
    open class func getExperimentWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<GetExperimentResponse> {
        var localVariablePath = "/api/admin/experiments/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetExperimentResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get analysis results
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetExperimentResultsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getExperimentResults(id: String, xProjectId: String? = nil) async throws -> GetExperimentResultsResponse {
        return try await getExperimentResultsWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Get analysis results
     - GET /api/admin/experiments/{id}/results
     - Returns the latest analysis output for the experiment — one row per metric/group/day, including sample size, mean, % delta vs. control, p-value, and a sample-ratio mismatch flag.  **Use case:** Render the results table on the experiment detail page or drive an automated decision once a `goal` metric reaches significance.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetExperimentResultsResponse> 
     */
    open class func getExperimentResultsWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<GetExperimentResultsResponse> {
        var localVariablePath = "/api/admin/experiments/{id}/results"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetExperimentResultsResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get analysis timeseries
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter metric: (query) Optional metric name to filter the series. (optional)
     - returns: GetExperimentTimeseriesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getExperimentTimeseries(id: String, xProjectId: String? = nil, metric: String? = nil) async throws -> GetExperimentTimeseriesResponse {
        return try await getExperimentTimeseriesWithRequestBuilder(id: id, xProjectId: xProjectId, metric: metric).execute().body
    }

    /**
     Get analysis timeseries
     - GET /api/admin/experiments/{id}/timeseries
     - Same row shape as `/results`, but returns every daily slice rather than the latest. Filter to a single metric with the `metric` query parameter.  **Use case:** Drive a chart of metric movement over the experiment runtime, or sanity-check the lift is monotonic before deciding.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter metric: (query) Optional metric name to filter the series. (optional)
     - returns: RequestBuilder<GetExperimentTimeseriesResponse> 
     */
    open class func getExperimentTimeseriesWithRequestBuilder(id: String, xProjectId: String? = nil, metric: String? = nil) -> RequestBuilder<GetExperimentTimeseriesResponse> {
        var localVariablePath = "/api/admin/experiments/{id}/timeseries"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "metric": (wrappedValue: metric?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetExperimentTimeseriesResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List experiments
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter status: (query) Filter by lifecycle status. Pass &#x60;archived&#x60; to return the archive tab; any other value (or omitting it) returns the non-archived experiments. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: ListExperimentsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listExperiments(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, status: String? = nil, q: String? = nil) async throws -> ListExperimentsResponse {
        return try await listExperimentsWithRequestBuilder(xProjectId: xProjectId, limit: limit, cursor: cursor, status: status, q: q).execute().body
    }

    /**
     List experiments
     - GET /api/admin/experiments
     - Returns a single page of non-archived experiments ordered by `updated_at desc, id desc`. Use the `cursor` query parameter to paginate.  **Use case:** Snapshot every active experiment in the project — e.g. render an overview dashboard or drive a CI check that no experiment has been running past its `min_runtime_days`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter status: (query) Filter by lifecycle status. Pass &#x60;archived&#x60; to return the archive tab; any other value (or omitting it) returns the non-archived experiments. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: RequestBuilder<ListExperimentsResponse> 
     */
    open class func listExperimentsWithRequestBuilder(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, status: String? = nil, q: String? = nil) -> RequestBuilder<ListExperimentsResponse> {
        let localVariablePath = "/api/admin/experiments"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListExperimentsResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Re-queue analysis
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: ReanalyzeExperimentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func reanalyzeExperiment(id: String, xProjectId: String? = nil) async throws -> ReanalyzeExperimentResponse {
        return try await reanalyzeExperimentWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Re-queue analysis
     - POST /api/admin/experiments/{id}/reanalyze
     - Requeues the daily analysis pass for this experiment outside the normal cron cadence. Useful after attaching a new metric or correcting an event taxonomy. The job runs asynchronously.  **Use case:** Force-refresh results after wiring up a new metric without waiting for the next nightly cron tick.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<ReanalyzeExperimentResponse> 
     */
    open class func reanalyzeExperimentWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<ReanalyzeExperimentResponse> {
        var localVariablePath = "/api/admin/experiments/{id}/reanalyze"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReanalyzeExperimentResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Attach metrics
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter setExperimentMetricsRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: SetExperimentMetricsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setExperimentMetrics(id: String, setExperimentMetricsRequest: SetExperimentMetricsRequest, xProjectId: String? = nil) async throws -> SetExperimentMetricsResponse {
        return try await setExperimentMetricsWithRequestBuilder(id: id, setExperimentMetricsRequest: setExperimentMetricsRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Attach metrics
     - POST /api/admin/experiments/{id}/metrics
     - Replaces the experiment's metric attachments wholesale. Each entry pairs an existing `metric_id` with a `role` (`goal` / `guardrail` / `secondary`).  Returns `422` if any `metric_id` doesn't exist in the project. Pass `{ metrics: [] }` to detach everything.  **Use cases**  - **Standard setup** — one `goal`, one or two `guardrail`, optional `secondary` metrics for diagnostics. - **Detach all** — send `{ \"metrics\": [] }` before archiving.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter setExperimentMetricsRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<SetExperimentMetricsResponse> 
     */
    open class func setExperimentMetricsWithRequestBuilder(id: String, setExperimentMetricsRequest: SetExperimentMetricsRequest, xProjectId: String? = nil) -> RequestBuilder<SetExperimentMetricsResponse> {
        var localVariablePath = "/api/admin/experiments/{id}/metrics"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setExperimentMetricsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SetExperimentMetricsResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Transition experiment status
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter setExperimentStatusRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: SetExperimentStatusResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setExperimentStatus(id: String, setExperimentStatusRequest: SetExperimentStatusRequest, xProjectId: String? = nil) async throws -> SetExperimentStatusResponse {
        return try await setExperimentStatusWithRequestBuilder(id: id, setExperimentStatusRequest: setExperimentStatusRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Transition experiment status
     - POST /api/admin/experiments/{id}/status
     - Drives the experiment lifecycle. Allowed transitions:  - `draft → running` — starts allocation. Bumps the `startedAt` timestamp. - `running → stopped` — halts allocation. Existing exposures stay in the dataset. - `stopped → archived` — soft-delete. - `draft → archived` — discard an unstarted experiment. - `archived → draft` — restore a soft-deleted experiment so it can be re-completed and started. Allowed only if it never started; one that already ran must be cloned instead.  Restarting an `archived` experiment directly is not allowed — restore it to `draft` first. Returns `409` on illegal transitions and `429` if the plan's `experiments_running` limit is exceeded on `→ running`.  **Use cases**  - **Start** — `{ \"status\": \"running\" }` after wiring up the SDK and verifying targeting on staging. - **Stop** — `{ \"status\": \"stopped\" }` once the experiment hits its `min_runtime_days` and conclusive results land. - **Archive** — `{ \"status\": \"archived\" }` to soft-delete after sign-off.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter setExperimentStatusRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<SetExperimentStatusResponse> 
     */
    open class func setExperimentStatusWithRequestBuilder(id: String, setExperimentStatusRequest: SetExperimentStatusRequest, xProjectId: String? = nil) -> RequestBuilder<SetExperimentStatusResponse> {
        var localVariablePath = "/api/admin/experiments/{id}/status"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setExperimentStatusRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SetExperimentStatusResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update an experiment
     
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter updateExperimentRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: UpdateExperimentResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateExperiment(id: String, updateExperimentRequest: UpdateExperimentRequest, xProjectId: String? = nil) async throws -> UpdateExperimentResponse {
        return try await updateExperimentWithRequestBuilder(id: id, updateExperimentRequest: updateExperimentRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Update an experiment
     - PATCH /api/admin/experiments/{id}
     - Partial update. `allocation_pct`, `groups`, `salt`, `universe`, `params` are **immutable while running** — returns `409` if you try. Stop the experiment first.  Editing `groups` while in `draft` is fine; weights must still sum to 10000.  **Use cases**  - **Update metadata** — `description`, `tag`, `targeting_gate` editable any time. - **Ramp before launch** — set `allocation_pct` while still in `draft`. - **Tighten significance** — `significance_threshold` (Pro+). - **Rewire groups** — replace `groups` wholesale while in `draft`; immutable once running.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque experiment id (&#x60;exp_…&#x60;) or the experiment&#39;s &#x60;name&#x60;. 
     - parameter updateExperimentRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<UpdateExperimentResponse> 
     */
    open class func updateExperimentWithRequestBuilder(id: String, updateExperimentRequest: UpdateExperimentRequest, xProjectId: String? = nil) -> RequestBuilder<UpdateExperimentResponse> {
        var localVariablePath = "/api/admin/experiments/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateExperimentRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateExperimentResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
