//
// FlagsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class FlagsAPI {

    /**
     Create a feature gate
     
     - parameter createGateRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: CreateGateResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createGate(createGateRequest: CreateGateRequest, xProjectId: String? = nil) async throws -> CreateGateResponse {
        return try await createGateWithRequestBuilder(createGateRequest: createGateRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Create a feature gate
     - POST /api/admin/gates
     - Creates a new gate. Default `enabled: true` at the supplied `rollout_pct` (`0` = fully dark).  Only `name` is required. Request fields use snake_case (`owner_email`); the GET response returns camelCase (`ownerEmail`, `groupName`).  Returns `409` if `name` already exists in the project (case-sensitive).  **Use cases**  - **Dark create + ramp later** — `{ \"name\": \"checkout_v2\" }` at 0% rollout. Ramp via PATCH after deploy validation. - **Targeted rollout** — supply `rules` to gate the caller (e.g. only `plan = pro` users) plus a `rollout_pct` to bucket within that audience. - **Gatekeeper stack** — supply `stack` instead of `rules`/`rollout_pct` for `internal ∪ beta ∪ public` fall-through. Stack entries evaluated top-to-bottom; first match wins. - **Dashboard metadata** — populate `title`, `description`, `folder`, `group`, `owner_email` so the admin UI is self-documenting from day one. - **Disabled on create** — pre-provision with `enabled: false` for a future launch; flip on with `POST /{id}/enable` at go-live.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter createGateRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<CreateGateResponse> 
     */
    open class func createGateWithRequestBuilder(createGateRequest: CreateGateRequest, xProjectId: String? = nil) -> RequestBuilder<CreateGateResponse> {
        let localVariablePath = "/api/admin/gates"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createGateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateGateResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a feature gate
     
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: DeleteGateResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteGate(id: String, xProjectId: String? = nil) async throws -> DeleteGateResponse {
        return try await deleteGateWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Delete a feature gate
     - DELETE /api/admin/gates/{id}
     - Soft-deletes the gate. Returns 409 if the gate is still referenced by a running experiment as a targeting gate — stop the experiment first.  **Use case:** Tear down a gate after a feature has fully shipped and the rollout flag is no longer needed.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<DeleteGateResponse> 
     */
    open class func deleteGateWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<DeleteGateResponse> {
        var localVariablePath = "/api/admin/gates/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteGateResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Disable a gate
     
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: DisableGateResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func disableGate(id: String, xProjectId: String? = nil) async throws -> DisableGateResponse {
        return try await disableGateWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Disable a gate
     - POST /api/admin/gates/{id}/disable
     - Sets `enabled: false` so the gate evaluates to `false` for every caller, regardless of `rollout_pct` or `rules`. Use as a quick kill switch.  **Use case:** Flip a gate off in production without redeploying — the canonical kill-switch flow.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<DisableGateResponse> 
     */
    open class func disableGateWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<DisableGateResponse> {
        var localVariablePath = "/api/admin/gates/{id}/disable"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DisableGateResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Enable a gate
     
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: EnableGateResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func enableGate(id: String, xProjectId: String? = nil) async throws -> EnableGateResponse {
        return try await enableGateWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Enable a gate
     - POST /api/admin/gates/{id}/enable
     - Sets `enabled: true`. The current `rollout_pct` is preserved.  **Use case:** Re-enable a previously disabled gate without re-issuing a full update.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<EnableGateResponse> 
     */
    open class func enableGateWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<EnableGateResponse> {
        var localVariablePath = "/api/admin/gates/{id}/enable"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EnableGateResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List feature gates
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: ListGatesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listGates(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, q: String? = nil) async throws -> ListGatesResponse {
        return try await listGatesWithRequestBuilder(xProjectId: xProjectId, limit: limit, cursor: cursor, q: q).execute().body
    }

    /**
     List feature gates
     - GET /api/admin/gates
     - Returns a single page of gates ordered by `updated_at desc, id desc`. Use the `cursor` query parameter to paginate.  **Use case:** Snapshot every gate in the project — for example to render an admin overview or to drive a CI check that asserts no gate is left at 100% in staging.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: RequestBuilder<ListGatesResponse> 
     */
    open class func listGatesWithRequestBuilder(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, q: String? = nil) -> RequestBuilder<ListGatesResponse> {
        let localVariablePath = "/api/admin/gates"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListGatesResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a feature gate
     
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter updateGateRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: UpdateGateResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateGate(id: String, updateGateRequest: UpdateGateRequest, xProjectId: String? = nil) async throws -> UpdateGateResponse {
        return try await updateGateWithRequestBuilder(id: id, updateGateRequest: updateGateRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Update a feature gate
     - PATCH /api/admin/gates/{id}
     - Partial update — only supplied fields change. Array fields (`rules`, `stack`) **replace** wholesale; there is no merge or append.  `name` and the gate id are immutable. The response carries only `{ id }` — re-fetch via `GET /api/admin/gates` for the new row.  **Use cases**  - **Ramp rollout** — `{ \"rollout_pct\": 5000 }` for 50%. Basis points (0–10000); `100` = 1%. - **Kill switch** — `{ \"enabled\": false }`. Forces evaluation to `false` for every caller regardless of rules/rollout. Re-enable with `POST /{id}/enable` or `{ \"enabled\": true }`. - **Modify a rule's `in` set** — send the full new `rules` array. To add `'GB'` to `['US','CA']`: `{ \"rules\": [{ \"attr\": \"country\", \"op\": \"in\", \"value\": [\"US\",\"CA\",\"GB\"] }] }`. No per-rule patch endpoint. - **Add targeting from scratch** — `{ \"rules\": [{ \"attr\": \"email\", \"op\": \"regex\", \"value\": \"@acme\\\\.com$\" }] }`. - **Switch to gatekeeper stack** — send a non-null `stack`. To revert to flat eval, send `{ \"stack\": null }`. - **Update metadata** — any subset of `title`, `description`, `folder`, `group`, `owner_email`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;. 
     - parameter updateGateRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<UpdateGateResponse> 
     */
    open class func updateGateWithRequestBuilder(id: String, updateGateRequest: UpdateGateRequest, xProjectId: String? = nil) -> RequestBuilder<UpdateGateResponse> {
        var localVariablePath = "/api/admin/gates/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateGateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateGateResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
