//
// KillswitchAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class KillswitchAPI {

    /**
     Create a killswitch
     
     - parameter createKillswitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: CreateKillswitchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createKillswitch(createKillswitchRequest: CreateKillswitchRequest, xProjectId: String? = nil) async throws -> CreateKillswitchResponse {
        return try await createKillswitchWithRequestBuilder(createKillswitchRequest: createKillswitchRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Create a killswitch
     - POST /api/admin/killswitches
     - Creates a new killswitch with `value` (default `false`) applied to **every** env at version 1.  Returns `409` if `name` already exists in the project.  **Use cases**  - **Untripped create** — `{ \"name\": \"payments.checkout\" }`. Provision the kill ahead of an incident. - **Pre-tripped** — `{ \"value\": true }` to ship the killswitch already engaged. - **With switches** — seed `switches` to carve out per-region/per-tenant kills from day one.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter createKillswitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<CreateKillswitchResponse> 
     */
    open class func createKillswitchWithRequestBuilder(createKillswitchRequest: CreateKillswitchRequest, xProjectId: String? = nil) -> RequestBuilder<CreateKillswitchResponse> {
        let localVariablePath = "/api/admin/killswitches"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createKillswitchRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateKillswitchResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a killswitch
     
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: DeleteKillswitchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteKillswitch(id: String, xProjectId: String? = nil) async throws -> DeleteKillswitchResponse {
        return try await deleteKillswitchWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Delete a killswitch
     - DELETE /api/admin/killswitches/{id}
     - Soft-deletes the killswitch and rebuilds the project's flags KV blob so SDKs stop seeing it.  **Use case:** Tear down a killswitch after the feature it protected has been removed.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<DeleteKillswitchResponse> 
     */
    open class func deleteKillswitchWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<DeleteKillswitchResponse> {
        var localVariablePath = "/api/admin/killswitches/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteKillswitchResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get one killswitch
     
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetKillswitchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getKillswitch(id: String, xProjectId: String? = nil) async throws -> GetKillswitchResponse {
        return try await getKillswitchWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Get one killswitch
     - GET /api/admin/killswitches/{id}
     - Returns the killswitch metadata plus the latest published `value`/`switches`/`version` per env.  **Use case:** Fetch the current state of one killswitch — e.g. to verify a trip propagated before declaring an incident mitigated.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetKillswitchResponse> 
     */
    open class func getKillswitchWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<GetKillswitchResponse> {
        var localVariablePath = "/api/admin/killswitches/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetKillswitchResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List killswitches
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: ListKillswitchesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listKillswitches(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, q: String? = nil) async throws -> ListKillswitchesResponse {
        return try await listKillswitchesWithRequestBuilder(xProjectId: xProjectId, limit: limit, cursor: cursor, q: q).execute().body
    }

    /**
     List killswitches
     - GET /api/admin/killswitches
     - Returns a single page of killswitches ordered by `updated_at desc, id desc`. Each row includes the latest published `value`/`switches`/`version` per env.  **Use case:** Snapshot every killswitch in the project — e.g. to render an incident-response runbook listing every kill and its current trip state.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: RequestBuilder<ListKillswitchesResponse> 
     */
    open class func listKillswitchesWithRequestBuilder(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, q: String? = nil) -> RequestBuilder<ListKillswitchesResponse> {
        let localVariablePath = "/api/admin/killswitches"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListKillswitchesResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set one switch entry
     
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter setKillswitchSwitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: SetKillswitchSwitchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setKillswitchSwitch(id: String, setKillswitchSwitchRequest: SetKillswitchSwitchRequest, xProjectId: String? = nil) async throws -> SetKillswitchSwitchResponse {
        return try await setKillswitchSwitchWithRequestBuilder(id: id, setKillswitchSwitchRequest: setKillswitchSwitchRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Set one switch entry
     - PUT /api/admin/killswitches/{id}/switch
     - Sets or updates a single `switchKey` on a single `env`. Publishes one new version on that env only — other envs untouched.  Use this for surgical per-env, per-key flips during incident response (e.g. trip `eu_region` on prod without touching the flat `value` or other envs).  **Use cases**  - **Trip a region** — `{ \"env\": \"prod\", \"switchKey\": \"eu_region\", \"value\": true }`. - **Untrip without removing** — same payload with `value: false`. To remove the entry entirely use `DELETE /{id}/switch`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter setKillswitchSwitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<SetKillswitchSwitchResponse> 
     */
    open class func setKillswitchSwitchWithRequestBuilder(id: String, setKillswitchSwitchRequest: SetKillswitchSwitchRequest, xProjectId: String? = nil) -> RequestBuilder<SetKillswitchSwitchResponse> {
        var localVariablePath = "/api/admin/killswitches/{id}/switch"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setKillswitchSwitchRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SetKillswitchSwitchResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set the flat value on one env
     
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter setKillswitchValueRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: SetKillswitchValueResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setKillswitchValue(id: String, setKillswitchValueRequest: SetKillswitchValueRequest, xProjectId: String? = nil) async throws -> SetKillswitchValueResponse {
        return try await setKillswitchValueWithRequestBuilder(id: id, setKillswitchValueRequest: setKillswitchValueRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Set the flat value on one env
     - PUT /api/admin/killswitches/{id}/value
     - Sets the flat `value` on a single `env`, publishing one new version on that env only. `switches` and other envs are untouched.  Use this to trip (or untrip) a killswitch on one environment without replacing its per-key overrides.  **Use cases**  - **Trip on prod** — `{ \"env\": \"prod\", \"value\": true }`. - **Untrip on prod** — `{ \"env\": \"prod\", \"value\": false }`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter setKillswitchValueRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<SetKillswitchValueResponse> 
     */
    open class func setKillswitchValueWithRequestBuilder(id: String, setKillswitchValueRequest: SetKillswitchValueRequest, xProjectId: String? = nil) -> RequestBuilder<SetKillswitchValueResponse> {
        var localVariablePath = "/api/admin/killswitches/{id}/value"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setKillswitchValueRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SetKillswitchValueResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Remove one switch entry
     
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter unsetKillswitchSwitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: UnsetKillswitchSwitchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func unsetKillswitchSwitch(id: String, unsetKillswitchSwitchRequest: UnsetKillswitchSwitchRequest, xProjectId: String? = nil) async throws -> UnsetKillswitchSwitchResponse {
        return try await unsetKillswitchSwitchWithRequestBuilder(id: id, unsetKillswitchSwitchRequest: unsetKillswitchSwitchRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Remove one switch entry
     - DELETE /api/admin/killswitches/{id}/switch
     - Removes a single `switchKey` from the `switches` map on a single `env`. Publishes a new version on that env.  Returns `{ removed: false }` if the entry didn't exist (idempotent no-op).  **Use case:** Clean up a per-region override after the incident is resolved so the flat `value` governs again.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter unsetKillswitchSwitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<UnsetKillswitchSwitchResponse> 
     */
    open class func unsetKillswitchSwitchWithRequestBuilder(id: String, unsetKillswitchSwitchRequest: UnsetKillswitchSwitchRequest, xProjectId: String? = nil) -> RequestBuilder<UnsetKillswitchSwitchResponse> {
        var localVariablePath = "/api/admin/killswitches/{id}/switch"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: unsetKillswitchSwitchRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UnsetKillswitchSwitchResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a killswitch
     
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter updateKillswitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: UpdateKillswitchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateKillswitch(id: String, updateKillswitchRequest: UpdateKillswitchRequest, xProjectId: String? = nil) async throws -> UpdateKillswitchResponse {
        return try await updateKillswitchWithRequestBuilder(id: id, updateKillswitchRequest: updateKillswitchRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Update a killswitch
     - PATCH /api/admin/killswitches/{id}
     - Partial update applied to **every** env. Setting `value`/`switches` publishes a new version per env. Description-only patches don't bump versions.  To change a single switch on a single env, use `PUT /{id}/switch` instead.  **Use cases**  - **Trip everywhere** — `{ \"value\": true }`. Kills the feature across dev/stage/prod in one call. - **Untrip everywhere** — `{ \"value\": false }`. - **Replace switches** — send the full new map; per-key edits use `PUT /{id}/switch`. - **Update description** — metadata-only patches don't bump versions.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque killswitch id (&#x60;ksw_…&#x60;) or the killswitch&#39;s &#x60;name&#x60;. 
     - parameter updateKillswitchRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<UpdateKillswitchResponse> 
     */
    open class func updateKillswitchWithRequestBuilder(id: String, updateKillswitchRequest: UpdateKillswitchRequest, xProjectId: String? = nil) -> RequestBuilder<UpdateKillswitchResponse> {
        var localVariablePath = "/api/admin/killswitches/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateKillswitchRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateKillswitchResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
