//
// MetricsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MetricsAPI {

    /**
     Create a metric
     
     - parameter createMetricRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: CreateMetricResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createMetric(createMetricRequest: CreateMetricRequest, xProjectId: String? = nil) async throws -> CreateMetricResponse {
        return try await createMetricWithRequestBuilder(createMetricRequest: createMetricRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Create a metric
     - POST /api/admin/metrics
     - Creates an event-backed metric. Pass the query as the DSL string (`query`) **or** the typed IR (`query_ir`) — exactly one. `event_name` must equal the event the query references.  Returns `409` if a metric with the same `name` already exists, and `422` if the query is invalid or references an unregistered event / label.  **Use cases**  - **Track an event** — `count_users(<event>)` for unique-user counts. - **Sum a value** — `sum(<event>, <label>)` for revenue / quantity metrics. - **Experiment success metric** — create the metric, then attach its id to an experiment.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter createMetricRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<CreateMetricResponse> 
     */
    open class func createMetricWithRequestBuilder(createMetricRequest: CreateMetricRequest, xProjectId: String? = nil) -> RequestBuilder<CreateMetricResponse> {
        let localVariablePath = "/api/admin/metrics"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createMetricRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateMetricResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Archive a metric
     
     - parameter id: (path) Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: DeleteMetricResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteMetric(id: String, xProjectId: String? = nil) async throws -> DeleteMetricResponse {
        return try await deleteMetricWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Archive a metric
     - DELETE /api/admin/metrics/{id}
     - Soft-deletes (archives) the metric. Returns `409` if it is attached to a running experiment — stop those experiments first.  **Use case:** Retire a metric once no running experiment depends on it (the user-facing verb is `archive`).
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<DeleteMetricResponse> 
     */
    open class func deleteMetricWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<DeleteMetricResponse> {
        var localVariablePath = "/api/admin/metrics/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteMetricResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a metric
     
     - parameter id: (path) Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetMetricResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMetric(id: String, xProjectId: String? = nil) async throws -> GetMetricResponse {
        return try await getMetricWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Get a metric
     - GET /api/admin/metrics/{id}
     - Fetch one metric by its id or name, including the rendered DSL query and the typed IR.  **Use case:** Inspect a single metric's full definition before reusing it in an experiment or alert rule.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetMetricResponse> 
     */
    open class func getMetricWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<GetMetricResponse> {
        var localVariablePath = "/api/admin/metrics/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetMetricResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List metrics
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: [ListMetricsResponseInner]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listMetrics(xProjectId: String? = nil, q: String? = nil) async throws -> [ListMetricsResponseInner] {
        return try await listMetricsWithRequestBuilder(xProjectId: xProjectId, q: q).execute().body
    }

    /**
     List metrics
     - GET /api/admin/metrics
     - Returns every metric in the project (not paginated) — name, folder, source event, the typed `queryIr`, and the rendered query.  **Use case:** Audit every metric defined in the project — for example to find the metric id to attach as an experiment's success metric.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: RequestBuilder<[ListMetricsResponseInner]> 
     */
    open class func listMetricsWithRequestBuilder(xProjectId: String? = nil, q: String? = nil) -> RequestBuilder<[ListMetricsResponseInner]> {
        let localVariablePath = "/api/admin/metrics"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ListMetricsResponseInner]>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a metric
     
     - parameter id: (path) Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. 
     - parameter updateMetricRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetMetricResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateMetric(id: String, updateMetricRequest: UpdateMetricRequest, xProjectId: String? = nil) async throws -> GetMetricResponse {
        return try await updateMetricWithRequestBuilder(id: id, updateMetricRequest: updateMetricRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Update a metric
     - PATCH /api/admin/metrics/{id}
     - Update a metric's definition — folder, source event, query (`query` DSL or typed `query_ir`), winsorisation, minimum detectable effect, or direction. `name` is immutable. Provide at most one of `query` / `query_ir`.  **Use case:** Refine a metric's query or guardrail direction without recreating it.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque metric id (&#x60;met_…&#x60;) or the metric&#39;s &#x60;name&#x60;. 
     - parameter updateMetricRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetMetricResponse> 
     */
    open class func updateMetricWithRequestBuilder(id: String, updateMetricRequest: UpdateMetricRequest, xProjectId: String? = nil) -> RequestBuilder<GetMetricResponse> {
        var localVariablePath = "/api/admin/metrics/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateMetricRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetMetricResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
