//
// OpsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class OpsAPI {

    /**
     File a queue item
     
     - parameter createOpsItemRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: CreateOpsItemResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createOpsItem(createOpsItemRequest: CreateOpsItemRequest, xProjectId: String? = nil) async throws -> CreateOpsItemResponse {
        return try await createOpsItemWithRequestBuilder(createOpsItemRequest: createOpsItemRequest, xProjectId: xProjectId).execute().body
    }

    /**
     File a queue item
     - POST /api/admin/ops
     - Files one queue item — a bug report or a feature request — and fires the project's connectors (GitHub issue / Slack). `type` selects which; only the two user-fileable types are accepted (`error`/`alert` tickets are auto-filed by the platform). Returns the new id and per-project number.  **Use cases**  - **File a bug** — `{ \"type\": \"bug\", \"title\": \"Checkout 500s on Safari\", \"stepsToReproduce\": \"…\" }`. - **File a feature request** — `{ \"type\": \"feature_request\", \"title\": \"Dark mode\", \"priority\": \"nice_to_have\" }`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter createOpsItemRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<CreateOpsItemResponse> 
     */
    open class func createOpsItemWithRequestBuilder(createOpsItemRequest: CreateOpsItemRequest, xProjectId: String? = nil) -> RequestBuilder<CreateOpsItemResponse> {
        let localVariablePath = "/api/admin/ops"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createOpsItemRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateOpsItemResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get one queue item
     
     - parameter handle: (path) Per-project item number (e.g. &#x60;7&#x60;) or the full ops item id. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetOpsItemResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOpsItem(handle: String, xProjectId: String? = nil) async throws -> GetOpsItemResponse {
        return try await getOpsItemWithRequestBuilder(handle: handle, xProjectId: xProjectId).execute().body
    }

    /**
     Get one queue item
     - GET /api/admin/ops/{handle}
     - Fetch a single queue item by its per-project `number` or full id.  **Use case:** Inspect one item's full detail before updating its status or linking a PR.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter handle: (path) Per-project item number (e.g. &#x60;7&#x60;) or the full ops item id. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetOpsItemResponse> 
     */
    open class func getOpsItemWithRequestBuilder(handle: String, xProjectId: String? = nil) -> RequestBuilder<GetOpsItemResponse> {
        var localVariablePath = "/api/admin/ops/{handle}"
        let handlePreEscape = "\(APIHelper.mapValueToPathItem(handle))"
        let handlePostEscape = handlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{handle}", with: handlePostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOpsItemResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Link a fixing PR
     
     - parameter handle: (path) Per-project item number (e.g. &#x60;7&#x60;) or the full ops item id. 
     - parameter linkPrToOpsItemRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: LinkPrToOpsItemResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func linkPrToOpsItem(handle: String, linkPrToOpsItemRequest: LinkPrToOpsItemRequest, xProjectId: String? = nil) async throws -> LinkPrToOpsItemResponse {
        return try await linkPrToOpsItemWithRequestBuilder(handle: handle, linkPrToOpsItemRequest: linkPrToOpsItemRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Link a fixing PR
     - POST /api/admin/ops/{handle}/link-pr
     - Record the pull request that fixes a queue item (and clears the link with `prNumber: null`).  **Use case:** Tie the fixing PR to the item so closing the PR can flip it to ready_for_qa.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter handle: (path) Per-project item number (e.g. &#x60;7&#x60;) or the full ops item id. 
     - parameter linkPrToOpsItemRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<LinkPrToOpsItemResponse> 
     */
    open class func linkPrToOpsItemWithRequestBuilder(handle: String, linkPrToOpsItemRequest: LinkPrToOpsItemRequest, xProjectId: String? = nil) -> RequestBuilder<LinkPrToOpsItemResponse> {
        var localVariablePath = "/api/admin/ops/{handle}/link-pr"
        let handlePreEscape = "\(APIHelper.mapValueToPathItem(handle))"
        let handlePostEscape = handlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{handle}", with: handlePostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: linkPrToOpsItemRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LinkPrToOpsItemResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_listOpsItems: String, CaseIterable {
        case bug = "bug"
        case featureRequest = "feature_request"
        case error = "error"
        case alert = "alert"
        case all = "all"
    }

    /**
     * enum for parameter status
     */
    public enum Status_listOpsItems: String, CaseIterable {
        case _open = "open"
        case pendingApproval = "pending_approval"
        case triage = "triage"
        case triaged = "triaged"
        case inProgress = "in_progress"
        case readyForQa = "ready_for_qa"
        case resolved = "resolved"
        case wontFix = "wont_fix"
        case all = "all"
    }

    /**
     List the operational queue
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter type: (query) Filter by item type (&#x60;bug&#x60;/&#x60;feature_request&#x60;/&#x60;error&#x60;/&#x60;alert&#x60;), or &#x60;all&#x60;. (optional)
     - parameter status: (query) Filter by lifecycle status, or &#x60;all&#x60;. The human-gated holding states (&#x60;pending_approval&#x60;, &#x60;triage&#x60;) are excluded from &#x60;all&#x60;/default and returned only when requested as the exact status. (optional)
     - parameter limit: (query) Max items to return (1–500). (optional)
     - returns: [ListOpsItemsResponseInner]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listOpsItems(xProjectId: String? = nil, type: ModelType_listOpsItems? = nil, status: Status_listOpsItems? = nil, limit: Int? = nil) async throws -> [ListOpsItemsResponseInner] {
        return try await listOpsItemsWithRequestBuilder(xProjectId: xProjectId, type: type, status: status, limit: limit).execute().body
    }

    /**
     List the operational queue
     - GET /api/admin/ops
     - Returns the unified ops queue (bugs, feature requests, errors, alerts) in work order — highest priority first, oldest first within a priority — so consumers work it top-down. Filter by `type` and/or `status`, and cap with `limit`. Human-gated holding states (items awaiting human sign-off in the dashboard) are never returned by `all`/default status.  **Use case:** Pull the open queue to triage — e.g. every `bug` still `open` — before working items down one by one.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter type: (query) Filter by item type (&#x60;bug&#x60;/&#x60;feature_request&#x60;/&#x60;error&#x60;/&#x60;alert&#x60;), or &#x60;all&#x60;. (optional)
     - parameter status: (query) Filter by lifecycle status, or &#x60;all&#x60;. The human-gated holding states (&#x60;pending_approval&#x60;, &#x60;triage&#x60;) are excluded from &#x60;all&#x60;/default and returned only when requested as the exact status. (optional)
     - parameter limit: (query) Max items to return (1–500). (optional)
     - returns: RequestBuilder<[ListOpsItemsResponseInner]> 
     */
    open class func listOpsItemsWithRequestBuilder(xProjectId: String? = nil, type: ModelType_listOpsItems? = nil, status: Status_listOpsItems? = nil, limit: Int? = nil) -> RequestBuilder<[ListOpsItemsResponseInner]> {
        let localVariablePath = "/api/admin/ops"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "type": (wrappedValue: type?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ListOpsItemsResponseInner]>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Raise an attention notification
     
     - parameter notifyOpsRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: NotifyOpsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func notifyOps(notifyOpsRequest: NotifyOpsRequest, xProjectId: String? = nil) async throws -> NotifyOpsResponse {
        return try await notifyOpsWithRequestBuilder(notifyOpsRequest: notifyOpsRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Raise an attention notification
     - POST /api/admin/notifications
     - Raise a 'needs your attention' bell notification. Create-only and idempotent on `dedupeKey` — re-raising with the same key updates the one card instead of stacking duplicates. It never reads, marks read, or deletes the feed, so it is safe for restricted ops keys.  **Use case:** Escalate work that can't land in code (a product decision, a credential only a human has, a resource only a human may edit), deduped so repeats don't spam the bell.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter notifyOpsRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<NotifyOpsResponse> 
     */
    open class func notifyOpsWithRequestBuilder(notifyOpsRequest: NotifyOpsRequest, xProjectId: String? = nil) -> RequestBuilder<NotifyOpsResponse> {
        let localVariablePath = "/api/admin/notifications"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: notifyOpsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NotifyOpsResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a queue item
     
     - parameter handle: (path) Per-project item number (e.g. &#x60;7&#x60;) or the full ops item id. 
     - parameter updateOpsItemRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: UpdateOpsItemResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateOpsItem(handle: String, updateOpsItemRequest: UpdateOpsItemRequest, xProjectId: String? = nil) async throws -> UpdateOpsItemResponse {
        return try await updateOpsItemWithRequestBuilder(handle: handle, updateOpsItemRequest: updateOpsItemRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Update a queue item
     - PATCH /api/admin/ops/{handle}
     - Update a queue item. The body is validated against the item's stored type: a `bug` accepts its content fields (title, steps-to-reproduce, actual/expected result) plus `status`/`priority`/`notify` and a GitHub PR link; a `feature_request` its content (title, description, use-case) plus the same triage fields; `error`/`alert`/`measure_plan` accept `status`/`priority`/`notify` only (their content is platform-owned). Pass at least one field.  Completing an `error` ticket (status `resolved` or `ready_for_qa`) also resolves the tracked error it links to; the error reopens automatically if it recurs — so completing is safe pre-deploy.  **Use cases**  - **Start working an item** — `{ \"status\": \"in_progress\" }`. - **Hand off for review** — `{ \"status\": \"ready_for_qa\" }` once the fix landed (the mode PR-based loops use). - **Triage** — `{ \"priority\": \"high\" }`, content edits on bug/feature items.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter handle: (path) Per-project item number (e.g. &#x60;7&#x60;) or the full ops item id. 
     - parameter updateOpsItemRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<UpdateOpsItemResponse> 
     */
    open class func updateOpsItemWithRequestBuilder(handle: String, updateOpsItemRequest: UpdateOpsItemRequest, xProjectId: String? = nil) -> RequestBuilder<UpdateOpsItemResponse> {
        var localVariablePath = "/api/admin/ops/{handle}"
        let handlePreEscape = "\(APIHelper.mapValueToPathItem(handle))"
        let handlePostEscape = handlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{handle}", with: handlePostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateOpsItemRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateOpsItemResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
