//
// ProjectsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ProjectsAPI {

    /**
     Show the current project
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetCurrentProjectResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCurrentProject(xProjectId: String? = nil) async throws -> GetCurrentProjectResponse {
        return try await getCurrentProjectWithRequestBuilder(xProjectId: xProjectId).execute().body
    }

    /**
     Show the current project
     - GET /api/admin/projects/current
     - Returns the project the caller's auth header resolves to — plan, status, billing, and which modules are enabled. The server reads the project from the credential, so there is no id parameter. Powers `whoami`.  **Use case:** Resolve who you are — the project, plan, and enabled modules tied to the current credential — without passing an id. Backs a registry-driven `whoami`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetCurrentProjectResponse> 
     */
    open class func getCurrentProjectWithRequestBuilder(xProjectId: String? = nil) -> RequestBuilder<GetCurrentProjectResponse> {
        let localVariablePath = "/api/admin/projects/current"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetCurrentProjectResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search project resources
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter q: (query) Search query. Matched as a case-insensitive substring against each resource&#39;s &#x60;name&#x60; and title/display name. Trimmed; empty returns no hits. (optional)
     - returns: SearchResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func searchResources(xProjectId: String? = nil, q: String? = nil) async throws -> SearchResponse {
        return try await searchResourcesWithRequestBuilder(xProjectId: xProjectId, q: q).execute().body
    }

    /**
     Search project resources
     - GET /api/admin/search
     - Universal substring search across the project's primary resources — feature gates, experiments, dynamic configs, killswitches, metrics, and team members. Matches the trimmed `q` against each resource's immutable `name` and its human title/display name (members match on display name or email), newest-first, capped per resource family so one noisy type can't crowd out the rest.  Returns a flat, ranked-by-type list of hits (members first); an empty or whitespace-only `q` returns no hits. Each hit carries a project-relative `href` that deep-links to the row.  **Use case:** Back a command-palette / quick-switcher in the dashboard, or look up the id of a resource by a fragment of its name before driving another API call.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter q: (query) Search query. Matched as a case-insensitive substring against each resource&#39;s &#x60;name&#x60; and title/display name. Trimmed; empty returns no hits. (optional)
     - returns: RequestBuilder<SearchResponse> 
     */
    open class func searchResourcesWithRequestBuilder(xProjectId: String? = nil, q: String? = nil) -> RequestBuilder<SearchResponse> {
        let localVariablePath = "/api/admin/search"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SearchResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update the current project
     
     - parameter id: (path) Stable opaque project id. Must match the caller&#39;s own project. 
     - parameter updateProjectRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: GetCurrentProjectResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateProject(id: String, updateProjectRequest: UpdateProjectRequest, xProjectId: String? = nil) async throws -> GetCurrentProjectResponse {
        return try await updateProjectWithRequestBuilder(id: id, updateProjectRequest: updateProjectRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Update the current project
     - PATCH /api/admin/projects/{id}
     - Update the current project's settings — name, domain, slug, default environment, timezone, experiment-analysis knobs (statistical method, significance threshold, auto-rollback, minimum sample days), and the per-module enable flags. Partial: only the fields you send change.  The project id in the path must match the project the caller's credential resolves to (a credential can only edit its own project). Changing `domain` re-stamps the allowed origin into every live SDK key.  **Use case:** Rename a project, move its domain, toggle a module on/off, or tune the experiment-analysis defaults without leaving the CLI.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque project id. Must match the caller&#39;s own project. 
     - parameter updateProjectRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<GetCurrentProjectResponse> 
     */
    open class func updateProjectWithRequestBuilder(id: String, updateProjectRequest: UpdateProjectRequest, xProjectId: String? = nil) -> RequestBuilder<GetCurrentProjectResponse> {
        var localVariablePath = "/api/admin/projects/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateProjectRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetCurrentProjectResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Find-or-create a project by domain
     
     - parameter upsertProjectRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: UpsertProjectResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func upsertProject(upsertProjectRequest: UpsertProjectRequest, xProjectId: String? = nil) async throws -> UpsertProjectResponse {
        return try await upsertProjectWithRequestBuilder(upsertProjectRequest: upsertProjectRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Find-or-create a project by domain
     - POST /api/admin/projects/upsert
     - Find-or-creates a project keyed by `(owner_email, domain)` under the session's owner, and returns it. Idempotent: a second call with the same domain returns the existing project with `created: false`.  Only `domain` is required — `name` defaults to the domain on first create. Recording the result in a local `.shipeasy` binding is a consumer side-effect; this endpoint never performs it.  **Use cases**  - **Install flow** — provision a per-app project without a trip to the dashboard. Run it on every install; the idempotent key means a re-run returns the existing project rather than duplicating it. - **Name explicitly** — pass `name` to label the project distinctly from its `domain`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter upsertProjectRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<UpsertProjectResponse> 
     */
    open class func upsertProjectWithRequestBuilder(upsertProjectRequest: UpsertProjectRequest, xProjectId: String? = nil) -> RequestBuilder<UpsertProjectResponse> {
        let localVariablePath = "/api/admin/projects/upsert"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: upsertProjectRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpsertProjectResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
