//
// TriggerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TriggerAPI {

    /**
     Create a recurring coding-agent trigger
     
     - parameter createTriggerConnectorRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: CreateConnectorResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createTriggerConnector(createTriggerConnectorRequest: CreateTriggerConnectorRequest, xProjectId: String? = nil) async throws -> CreateConnectorResponse {
        return try await createTriggerConnectorWithRequestBuilder(createTriggerConnectorRequest: createTriggerConnectorRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Create a recurring coding-agent trigger
     - POST /api/admin/connectors/trigger
     - Creates (or idempotently updates) a coding-agent **trigger** connector — the recurring, unattended run that burns down the ops queue in `--pr` mode. Discriminated on `provider`; only the four Shipeasy-fireable providers are accepted (`claude_trigger`, `cursor_trigger`, `copilot_trigger`, `jules_trigger`). Config + credential(s) arrive together; creates are idempotent by the provider's natural key, so re-creating updates the existing row.  Platforms without a fire endpoint (Codex, Windsurf, Cline, OpenClaw, OpenCode, Continue) cannot be created here — they are scheduled on their own platform (typically a GitHub Actions `schedule:` cron running the platform's headless CLI with the trigger prompt).  **Use cases**  - **Register a Claude routine** — after `RemoteTrigger {action:\"create\"}` returns `trig_…`, `{ \"provider\": \"claude_trigger\", \"config\": { \"routineId\": \"trig_…\" } }` (tokenless is fine; add the fire token later). - **Cold Cursor/Jules run** — repo coordinates + both keys; Shipeasy launches the run and the PR opens via the provider's GitHub App. - **Copilot cloud agent** — repo + a Copilot-licensed user PAT with the \"Agent tasks\" permission.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter createTriggerConnectorRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<CreateConnectorResponse> 
     */
    open class func createTriggerConnectorWithRequestBuilder(createTriggerConnectorRequest: CreateTriggerConnectorRequest, xProjectId: String? = nil) -> RequestBuilder<CreateConnectorResponse> {
        let localVariablePath = "/api/admin/connectors/trigger"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createTriggerConnectorRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateConnectorResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
