//
// UniversesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UniversesAPI {

    /**
     Create a universe
     
     - parameter createUniverseRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: CreateUniverseResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createUniverse(createUniverseRequest: CreateUniverseRequest, xProjectId: String? = nil) async throws -> CreateUniverseResponse {
        return try await createUniverseWithRequestBuilder(createUniverseRequest: createUniverseRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Create a universe
     - POST /api/admin/universes
     - Creates a new universe. Only `name` is required — `unit_type` defaults to `user_id` and `holdout_range` defaults to `null` (no holdout).  Returns `409` if `name` already exists in the project. Returns `403` if you supply `holdout_range` on a plan below Pro.  **Use cases**  - **Default universe** — `{ \"name\": \"primary_users\" }`. Per-user randomisation, no holdout. - **Reserved holdout** — supply `holdout_range` to carve out a measurement slice excluded from all experiments. - **Account-level** — `unit_type: 'account_id'` so multi-seat accounts see one consistent variant.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter createUniverseRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<CreateUniverseResponse> 
     */
    open class func createUniverseWithRequestBuilder(createUniverseRequest: CreateUniverseRequest, xProjectId: String? = nil) -> RequestBuilder<CreateUniverseResponse> {
        let localVariablePath = "/api/admin/universes"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createUniverseRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateUniverseResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a universe
     
     - parameter id: (path) Stable opaque universe id (&#x60;uni_…&#x60;) or the universe&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: DeleteUniverseResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteUniverse(id: String, xProjectId: String? = nil) async throws -> DeleteUniverseResponse {
        return try await deleteUniverseWithRequestBuilder(id: id, xProjectId: xProjectId).execute().body
    }

    /**
     Delete a universe
     - DELETE /api/admin/universes/{id}
     - Soft-deletes the universe. Returns `409` if any non-archived experiment still references it — archive those experiments first.  **Use case:** Tear down a universe after every experiment that used it has been archived.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque universe id (&#x60;uni_…&#x60;) or the universe&#39;s &#x60;name&#x60;. 
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<DeleteUniverseResponse> 
     */
    open class func deleteUniverseWithRequestBuilder(id: String, xProjectId: String? = nil) -> RequestBuilder<DeleteUniverseResponse> {
        var localVariablePath = "/api/admin/universes/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteUniverseResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List universes
     
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: ListUniversesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listUniverses(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, q: String? = nil) async throws -> ListUniversesResponse {
        return try await listUniversesWithRequestBuilder(xProjectId: xProjectId, limit: limit, cursor: cursor, q: q).execute().body
    }

    /**
     List universes
     - GET /api/admin/universes
     - Returns a single page of universes ordered by `created_at desc, id desc`. The universes table has no `updated_at`, so this list is keyed on creation time.  **Use case:** Snapshot every universe in the project — for example to audit which `unit_type` and `holdout_range` are in use before launching a new experiment.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - parameter limit: (query) Page size (1–500). Defaults to 100. (optional, default to 100)
     - parameter cursor: (query) Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     - parameter q: (query) Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     - returns: RequestBuilder<ListUniversesResponse> 
     */
    open class func listUniversesWithRequestBuilder(xProjectId: String? = nil, limit: Int? = nil, cursor: String? = nil, q: String? = nil) -> RequestBuilder<ListUniversesResponse> {
        let localVariablePath = "/api/admin/universes"
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "q": (wrappedValue: q?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListUniversesResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a universe
     
     - parameter id: (path) Stable opaque universe id (&#x60;uni_…&#x60;) or the universe&#39;s &#x60;name&#x60;. 
     - parameter updateUniverseRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: UpdateUniverseResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateUniverse(id: String, updateUniverseRequest: UpdateUniverseRequest, xProjectId: String? = nil) async throws -> UpdateUniverseResponse {
        return try await updateUniverseWithRequestBuilder(id: id, updateUniverseRequest: updateUniverseRequest, xProjectId: xProjectId).execute().body
    }

    /**
     Update a universe
     - PATCH /api/admin/universes/{id}
     - Partial update. Only `holdout_range` is mutable — `name` and `unit_type` are immutable after create.  Pass `\"holdout_range\": null` to remove an existing holdout.  **Use cases**  - **Adjust holdout** — change the reserved measurement slice without recreating experiments. - **Remove holdout** — `{ \"holdout_range\": null }`.
     - Bearer Token:
       - type: http
       - name: bearerSdkKey
     - parameter id: (path) Stable opaque universe id (&#x60;uni_…&#x60;) or the universe&#39;s &#x60;name&#x60;. 
     - parameter updateUniverseRequest: (body)  
     - parameter xProjectId: (header) Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     - returns: RequestBuilder<UpdateUniverseResponse> 
     */
    open class func updateUniverseWithRequestBuilder(id: String, updateUniverseRequest: UpdateUniverseRequest, xProjectId: String? = nil) -> RequestBuilder<UpdateUniverseResponse> {
        var localVariablePath = "/api/admin/universes/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = ShipeasyAdminAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateUniverseRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Project-Id": xProjectId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateUniverseResponse>.Type = ShipeasyAdminAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
