//
// ApproveEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/events/{id}&#x60; and &#x60;POST /api/admin/events/{id}/approve&#x60;. All fields optional; &#x60;name&#x60; is immutable after create. */
public struct ApproveEventRequest: Codable, JSONEncodable {

    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** New description for the event. */
    public var description: String?
    /** Replaces the full property set (no merge). Omit to leave properties unchanged. */
    public var properties: [ListEventsResponseInnerPropertiesInner]?

    public init(folder: String? = nil, description: String? = nil, properties: [ListEventsResponseInnerPropertiesInner]? = nil) {
        self.folder = folder
        self.description = description
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folder
        case description
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(properties, forKey: .properties)
    }
}

