//
// AttributeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Declared value type of a targeting attribute. */
public enum AttributeType: String, Codable, CaseIterable {
    case string = "string"
    case number = "number"
    case boolean = "boolean"
    case _enum = "enum"
    case date = "date"
}
