//
// ConnectorProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Connector destination. OAuth/app providers (&#x60;google_sheets&#x60;, &#x60;github&#x60;, &#x60;slack&#x60;) dispatch the event payload to an external destination. Trigger providers (&#x60;claude_trigger&#x60;, &#x60;cursor_trigger&#x60;, &#x60;copilot_trigger&#x60;, &#x60;jules_trigger&#x60;) instead kick a coding-agent run that burns down the operational queue. */
public enum ConnectorProvider: String, Codable, CaseIterable {
    case googleSheets = "google_sheets"
    case github = "github"
    case slack = "slack"
    case claudeTrigger = "claude_trigger"
    case cursorTrigger = "cursor_trigger"
    case copilotTrigger = "copilot_trigger"
    case julesTrigger = "jules_trigger"
}
