//
// ConnectorRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A connector row. The encrypted credentials cipher backing the connector is intentionally never serialised. */
public struct ConnectorRecord: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 80, pattern: nil)
    /** Stable opaque connector id (a UUID). */
    public var id: String
    /** Id of the project the connector belongs to. */
    public var projectId: String
    public var provider: ConnectorProvider
    /** Human-readable connector label shown in the dashboard. */
    public var name: String
    /** Whether the connector is active. OAuth providers are created `false` and flip to `true` only after the OAuth/config flow completes; trigger providers default to `true` on create. A disabled connector never dispatches and never auto-fires. */
    public var enabled: Bool
    /** Events this connector is subscribed to. Empty array = no auto-dispatch / no auto-fire (the connector can still be fired/tested manually). */
    public var events: [ConnectorEvent]
    /** Provider-specific, non-secret configuration (e.g. a Google Sheets `spreadsheetId`/`sheetTitle`, a Slack channel ref, or a trigger's repo coordinates + routine id). Secrets are never stored here — they live in an encrypted credentials cipher that is never returned by the API. */
    public var config: [String: AnyCodable]
    /** Display label for the connected account / target (e.g. the OAuth account email, or a trigger's idempotency key such as its repo url or routine id). `null` until the connector is authenticated/configured. */
    public var accountLabel: String?
    /** Error message from the most recent failed dispatch/fire attempt, or `null` if the last attempt succeeded (or none has run). */
    public var lastError: String?
    /** ISO-8601 timestamp of the most recent dispatch/fire attempt, or `null` if none has run. */
    public var lastAttemptAt: String?
    /** ISO-8601 timestamp of the most recent successful dispatch/fire, or `null` if none has succeeded. Preserved across later failures. */
    public var lastSuccessAt: String?
    /** ISO-8601 timestamp of creation. */
    public var createdAt: String
    /** ISO-8601 timestamp of last mutation. */
    public var updatedAt: String

    public init(id: String, projectId: String, provider: ConnectorProvider, name: String, enabled: Bool, events: [ConnectorEvent], config: [String: AnyCodable], accountLabel: String?, lastError: String?, lastAttemptAt: String?, lastSuccessAt: String?, createdAt: String, updatedAt: String) {
        self.id = id
        self.projectId = projectId
        self.provider = provider
        self.name = name
        self.enabled = enabled
        self.events = events
        self.config = config
        self.accountLabel = accountLabel
        self.lastError = lastError
        self.lastAttemptAt = lastAttemptAt
        self.lastSuccessAt = lastSuccessAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case projectId
        case provider
        case name
        case enabled
        case events
        case config
        case accountLabel
        case lastError
        case lastAttemptAt
        case lastSuccessAt
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(provider, forKey: .provider)
        try container.encode(name, forKey: .name)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(events, forKey: .events)
        try container.encode(config, forKey: .config)
        try container.encode(accountLabel, forKey: .accountLabel)
        try container.encode(lastError, forKey: .lastError)
        try container.encode(lastAttemptAt, forKey: .lastAttemptAt)
        try container.encode(lastSuccessAt, forKey: .lastSuccessAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ConnectorRecord: Identifiable {}
