//
// CopilotTriggerConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Non-secret config for a Copilot trigger. */
public struct CopilotTriggerConfig: Codable, JSONEncodable {

    public static let ownerRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let repoRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let baseRefRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let projectIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** GitHub repo owner. Together with `repo` forms the connector's idempotency key (`owner/repo`). */
    public var owner: String
    /** GitHub repo name. */
    public var repo: String
    /** Optional base ref the agent branches from. */
    public var baseRef: String?
    /** Shipeasy project id the run targets. */
    public var projectId: String

    public init(owner: String, repo: String, baseRef: String? = nil, projectId: String) {
        self.owner = owner
        self.repo = repo
        self.baseRef = baseRef
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case owner
        case repo
        case baseRef
        case projectId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(owner, forKey: .owner)
        try container.encode(repo, forKey: .repo)
        try container.encodeIfPresent(baseRef, forKey: .baseRef)
        try container.encode(projectId, forKey: .projectId)
    }
}

