//
// CreateCopilotTriggerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Create a GitHub Copilot coding-agent trigger. Idempotent by &#x60;config.owner/config.repo&#x60;. */
public struct CreateCopilotTriggerRequest: Codable, JSONEncodable {

    public enum Provider: String, Codable, CaseIterable {
        case copilotTrigger = "copilot_trigger"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 80, pattern: nil)
    public static let tokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Discriminator. GitHub Copilot coding-agent trigger. */
    public var provider: Provider
    /** Human-readable connector label. */
    public var name: String? = "Copilot trigger"
    /** Events that auto-fire a Copilot agent task. Defaults to empty. */
    public var events: [ConnectorEvent]?
    public var config: CopilotTriggerConfig
    /** Copilot-licensed user PAT (secret). The ops key lives in the repo's GitHub \"Agents\" secret store and is never sent through Shipeasy. Encrypted; never returned. */
    public var token: String
    /** Whether the trigger is active on create. */
    public var enabled: Bool? = true

    public init(provider: Provider, name: String? = "Copilot trigger", events: [ConnectorEvent]? = nil, config: CopilotTriggerConfig, token: String, enabled: Bool? = true) {
        self.provider = provider
        self.name = name
        self.events = events
        self.config = config
        self.token = token
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case name
        case events
        case config
        case token
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encode(config, forKey: .config)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

