//
// CreateUniverseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/universes&#x60;. Only &#x60;name&#x60; is required. */
public struct CreateUniverseRequest: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: "/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/")
    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    public static let holdoutRangeRule = ArrayRule(minItems: 2, maxItems: 2, uniqueItems: false)
    /** Stable universe key. Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create. */
    public var name: String
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** Unit of randomisation. Typically `user_id`. Use `account_id` to keep whole accounts in the same group across an experiment. */
    public var unitType: String? = "user_id"
    /** Inclusive `[lo, hi]` bucket range (0–9999) reserved as the **holdout** — callers hashed into this slice are excluded from every experiment in the universe. `null` disables the holdout. Pro plan or higher required. */
    public var holdoutRange: [Int]?

    public init(name: String, folder: String? = nil, unitType: String? = "user_id", holdoutRange: [Int]? = nil) {
        self.name = name
        self.folder = folder
        self.unitType = unitType
        self.holdoutRange = holdoutRange
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case folder
        case unitType = "unit_type"
        case holdoutRange = "holdout_range"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(unitType, forKey: .unitType)
        try container.encodeIfPresent(holdoutRange, forKey: .holdoutRange)
    }
}

