//
// CreateOpsItemResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for &#x60;POST /api/admin/ops&#x60;. */
public struct CreateOpsItemResponse: Codable, JSONEncodable {

    /** Newly created item id. */
    public var id: String
    /** Per-project item number assigned to the new item. */
    public var number: Double?

    public init(id: String, number: Double? = nil) {
        self.id = id
        self.number = number
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(number, forKey: .number)
    }
}


