//
// CreateCursorTriggerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Create a Cursor cloud-agent trigger. Both keys are required up front (never tokenless). Idempotent by &#x60;config.repoUrl&#x60;. */
public struct CreateCursorTriggerRequest: Codable, JSONEncodable {

    public enum Provider: String, Codable, CaseIterable {
        case cursorTrigger = "cursor_trigger"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 80, pattern: nil)
    public static let apiKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let opsKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Discriminator. Cursor cloud-agent trigger. */
    public var provider: Provider
    /** Human-readable connector label. */
    public var name: String? = "Cursor trigger"
    /** Events that auto-fire a cold cloud-agent run. Defaults to empty. */
    public var events: [ConnectorEvent]?
    public var config: CursorTriggerConfig
    /** Cursor API key that launches the run (secret). Encrypted into the credentials cipher; never returned. */
    public var apiKey: String
    /** Restricted Shipeasy ops key, injected into the run as `SHIPEASY_CLI_TOKEN` via the launch envVars (secret). Encrypted; never returned. */
    public var opsKey: String
    /** Whether the trigger is active on create. */
    public var enabled: Bool? = true

    public init(provider: Provider, name: String? = "Cursor trigger", events: [ConnectorEvent]? = nil, config: CursorTriggerConfig, apiKey: String, opsKey: String, enabled: Bool? = true) {
        self.provider = provider
        self.name = name
        self.events = events
        self.config = config
        self.apiKey = apiKey
        self.opsKey = opsKey
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case name
        case events
        case config
        case apiKey
        case opsKey
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encode(config, forKey: .config)
        try container.encode(apiKey, forKey: .apiKey)
        try container.encode(opsKey, forKey: .opsKey)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

