//
// CreateOpsCommentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/ops/{handle}/comments&#x60;. */
public struct CreateOpsCommentRequest: Codable, JSONEncodable {

    public static let bodyRule = StringRule(minLength: 1, maxLength: 10000, pattern: nil)
    /** The comment body as markdown. Mentions (`@teammate`, `@shipeasy`) are parsed from it. */
    public var body: String
    /** Reply under this top-level comment. Omit / `null` for a top-level comment. Replying to a reply attaches to the same top-level parent (threading is one level deep). */
    public var parentId: String?

    public init(body: String, parentId: String? = nil) {
        self.body = body
        self.parentId = parentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case parentId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(parentId, forKey: .parentId)
    }
}

