//
// CreateAttributeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/attributes&#x60;. Declares a targeting attribute. */
public struct CreateAttributeRequest: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[a-z0-9][a-z0-9_-]{0,63}$/")
    /** Attribute key (lowercase alphanumeric start, then letters/digits/`_`/`-`; max 64 chars). Immutable after create. */
    public var name: String
    public var type: AttributeType
    /** Allowed values when `type` is `enum` (required in that case — 422 otherwise); `null` for non-enum types. */
    public var enumValues: [String]?
    /** Whether the attribute must be present on the evaluation context. */
    public var _required: Bool? = false
    /** Optional human note shown in the dashboard. */
    public var description: String?
    /** Optional dotted path the SDK reads the value from. */
    public var sdkPath: String?

    public init(name: String, type: AttributeType, enumValues: [String]? = nil, _required: Bool? = false, description: String? = nil, sdkPath: String? = nil) {
        self.name = name
        self.type = type
        self.enumValues = enumValues
        self._required = _required
        self.description = description
        self.sdkPath = sdkPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case enumValues = "enum_values"
        case _required = "required"
        case description
        case sdkPath = "sdk_path"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(enumValues, forKey: .enumValues)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(sdkPath, forKey: .sdkPath)
    }
}

