//
// CreateOpsItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/ops&#x60;. A discriminated union on &#x60;type&#x60;: &#x60;bug&#x60; carries the bug fields, &#x60;feature_request&#x60; the feature fields. Only these two user-fileable types are accepted — &#x60;error&#x60;, &#x60;alert&#x60;, and &#x60;measure_plan&#x60; tickets are auto-filed by the platform and cannot be created over the API. */
public enum CreateOpsItemRequest: Codable, JSONEncodable {
    case typeCreateBugRequest(CreateBugRequest)
    case typeCreateFeatureRequestRequest(CreateFeatureRequestRequest)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeCreateBugRequest(let value):
            try container.encode(value)
        case .typeCreateFeatureRequestRequest(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case type = "type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .type)

        switch discriminatorValue {
        case "bug":
            self = .typeCreateBugRequest(try CreateBugRequest(from: decoder))
        case "feature_request":
            self = .typeCreateFeatureRequestRequest(try CreateFeatureRequestRequest(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for CreateOpsItemRequest"
                )
            )
        }
    }
}

