//
// CreateI18nDraftRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/i18n/drafts&#x60;. Stages a new translation draft against a target profile, optionally seeding from a source profile. */
public struct CreateI18nDraftRequest: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    /** Draft name, e.g. the target locale being staged. */
    public var name: String
    /** Profile the draft targets. */
    public var profileId: UUID
    /** Optional profile to seed the draft's keys from. */
    public var sourceProfileId: UUID?

    public init(name: String, profileId: UUID, sourceProfileId: UUID? = nil) {
        self.name = name
        self.profileId = profileId
        self.sourceProfileId = sourceProfileId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case profileId = "profile_id"
        case sourceProfileId = "source_profile_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(profileId, forKey: .profileId)
        try container.encodeIfPresent(sourceProfileId, forKey: .sourceProfileId)
    }
}

