//
// CreateEventResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of creating (or approving an existing pending) event. */
public struct CreateEventResponse: Codable, JSONEncodable {

    /** Newly assigned event id. */
    public var id: String
    /** The event name that was registered. */
    public var name: String

    public init(id: String, name: String) {
        self.id = id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
    }
}


