//
// CreateGateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/gates&#x60;. At minimum supply &#x60;name&#x60;; everything else has sensible defaults. */
public struct CreateGateRequest: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: "/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/")
    public static let rolloutPctRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let rolloutPercentRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let saltRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let titleRule = StringRule(minLength: nil, maxLength: 140, pattern: nil)
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 2000, pattern: nil)
    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    public static let groupRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let ownerEmailRule = StringRule(minLength: nil, maxLength: 190, pattern: nil)
    /** Stable gate key used by SDKs (`Shipeasy.checkGate(user, '<name>')`). Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create — rename = delete + recreate. */
    public var name: String
    /** Master switch. Defaults to `true`. Set `false` to create the gate disabled (evaluates to `false` regardless of rules/rollout); flip on via `POST /{id}/enable` or PATCH. */
    public var enabled: Bool? = true
    /** Initial rollout in **basis points** (0–10000 = 0%–100%) — `100` here means **1%**, not 100%. Use `rollout_percent` (0–100) below if you'd rather think in percent. Use `0` to create the gate dark and ramp via PATCH after deploy validation. */
    public var rolloutPct: Int? = 0
    /** Initial rollout as a **percentage** (0–100, fractional ok). Friendlier alias for `rollout_pct`; converted internally to basis points (e.g. `100` here = 10000 bp = 100%). If both `rollout_pct` and `rollout_percent` are set, `rollout_percent` wins. */
    public var rolloutPercent: Double?
    /** Targeting predicates. AND-combined. If non-empty, the gate returns `true` only for callers that satisfy every rule **and** fall under `rollout_pct`. */
    public var rules: [ListGatesResponseDataInnerRulesInner]?
    /** Hash salt for percentage bucketing. Auto-generated if omitted. Provide explicitly to keep a gate's buckets stable across delete/recreate. **Immutable after create** — there is no PATCH for `salt` because changing it would re-bucket every caller. */
    public var salt: String?
    /** Optional gatekeeper stack. When provided, takes precedence over `rules` + `rollout_pct` at evaluation time. Omit (or pass `null`) for a flat gate. */
    public var stack: [ListGatesResponseDataInnerStackInner]?
    /** Human-readable title shown in the dashboard. Free-form, no key format constraint. */
    public var title: String?
    /** Long-form description / runbook. Markdown is rendered in the dashboard. */
    public var description: String?
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** Group label for dashboard organisation (e.g. team or product area). */
    public var group: String?
    /** Owner contact. Displayed verbatim; not used for auth. */
    public var ownerEmail: String?

    public init(name: String, enabled: Bool? = true, rolloutPct: Int? = 0, rolloutPercent: Double? = nil, rules: [ListGatesResponseDataInnerRulesInner]? = nil, salt: String? = nil, stack: [ListGatesResponseDataInnerStackInner]? = nil, title: String? = nil, description: String? = nil, folder: String? = nil, group: String? = nil, ownerEmail: String? = nil) {
        self.name = name
        self.enabled = enabled
        self.rolloutPct = rolloutPct
        self.rolloutPercent = rolloutPercent
        self.rules = rules
        self.salt = salt
        self.stack = stack
        self.title = title
        self.description = description
        self.folder = folder
        self.group = group
        self.ownerEmail = ownerEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case enabled
        case rolloutPct = "rollout_pct"
        case rolloutPercent = "rollout_percent"
        case rules
        case salt
        case stack
        case title
        case description
        case folder
        case group
        case ownerEmail = "owner_email"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(rolloutPct, forKey: .rolloutPct)
        try container.encodeIfPresent(rolloutPercent, forKey: .rolloutPercent)
        try container.encodeIfPresent(rules, forKey: .rules)
        try container.encodeIfPresent(salt, forKey: .salt)
        try container.encodeIfPresent(stack, forKey: .stack)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(group, forKey: .group)
        try container.encodeIfPresent(ownerEmail, forKey: .ownerEmail)
    }
}

