//
// CreateExperimentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/experiments&#x60;. &#x60;name&#x60;, &#x60;universe&#x60;, and &#x60;groups&#x60; (≥2, weights sum to 10000) required. */
public struct CreateExperimentRequest: Codable, JSONEncodable {

    public enum Params: String, Codable, CaseIterable {
        case string = "string"
        case bool = "bool"
        case number = "number"
    }
    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: "/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/")
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 2000, pattern: nil)
    public static let hypothesisRule = StringRule(minLength: nil, maxLength: 4000, pattern: nil)
    public static let tagRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let ownerEmailRule = StringRule(minLength: nil, maxLength: 254, pattern: nil)
    public static let audienceRule = StringRule(minLength: nil, maxLength: 256, pattern: nil)
    public static let bucketByRule = StringRule(minLength: 1, maxLength: 128, pattern: "/^[a-zA-Z_][a-zA-Z0-9_]*$/")
    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    public static let universeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let allocationPctRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let allocationPercentRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let saltRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let groupsRule = ArrayRule(minItems: 2, maxItems: nil, uniqueItems: false)
    public static let significanceThresholdRule = NumericRule<Double>(minimum: 0.00010, exclusiveMinimum: false, maximum: 0.5, exclusiveMaximum: false, multipleOf: nil)
    public static let minRuntimeDaysRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 365, exclusiveMaximum: false, multipleOf: nil)
    public static let minSampleSizeRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    public static let guardrailMetricsRule = ArrayRule(minItems: nil, maxItems: 10, uniqueItems: false)
    /** Stable experiment key. Single segment or `folder.name` (a-z, 0-9, `_`/`-`; max 128 chars). Used by SDKs as `Shipeasy.getExperiment(user, '<name>')`. Immutable after create. */
    public var name: String
    /** Free-form description. Max 2000 chars, markdown rendered in the dashboard. */
    public var description: String?
    /** Hypothesis statement shown in the editor. Display-only. */
    public var hypothesis: String?
    /** Short tag chip rendered next to the name. Display-only. */
    public var tag: String?
    /** Owner email. Display-only. */
    public var ownerEmail: String?
    /** Audience label shown in the editor. Display-only. */
    public var audience: String?
    /** User-attribute name used as the bucketing key — e.g. `user_id` (default), `session_id`, `device_id`, or a custom attribute like `company_id` to keep a whole org on one variant. Defaults to `user_id` when omitted. */
    public var bucketBy: String?
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** Name of an existing universe in the project. Returns `422` if the universe doesn't exist. */
    public var universe: String
    /** Optional gate name. Only callers that pass the gate are enrolled in the experiment. */
    public var targetingGate: String?
    /** Share of the (gated) audience allocated to the experiment, in basis points (0–10000 = 0%–100%). `0` = unallocated. Use `allocation_percent` (0–100) below to think in percent. Immutable while the experiment is running. */
    public var allocationPct: Int? = 0
    /** Allocation as a **percentage** (0–100, fractional ok). Friendlier alias for `allocation_pct`; converted to basis points server-side (e.g. `50` = 5000 bp). If both are set, `allocation_percent` wins. */
    public var allocationPercent: Double?
    /** Hash salt for bucketing. Auto-generated if omitted. Immutable while running. */
    public var salt: String?
    /** Map of param-name → scalar type. Defines the shape of `groups[].params`. Example: `{ headline: 'string', show_cta: 'bool' }`. */
    public var params: [String: String]?
    /** Two or more variants. Weights must sum to exactly 10000 (100%). Immutable while running. */
    public var groups: [ListExperimentsResponseDataInnerGroupsInner]
    /** p-value cutoff used by the analysis pass. Defaults to `0.05`. Values other than 0.05 require Pro plan or higher. */
    public var significanceThreshold: Double? = 0.05
    /** Minimum days the experiment must run before results are considered conclusive. */
    public var minRuntimeDays: Int? = 0
    /** Minimum exposures per group before results are considered conclusive. */
    public var minSampleSize: Int? = 100
    /** Enable sequential testing (always-valid p-values). Requires Premium plan or higher. */
    public var sequentialTesting: Bool? = false
    /** Single goal metric defined inline — either a DSL `query` or an `event` (+`aggregation`/`value`) the server compiles. Attaching one is required before the experiment can be started. The underlying event is auto-created if missing. */
    public var goalMetric: ExperimentInlineMetric?
    /** Up to 10 guardrail metrics defined inline. Each is upserted (event + metric) and attached with role=guardrail. */
    public var guardrailMetrics: [ExperimentInlineMetric]?

    public init(name: String, description: String? = nil, hypothesis: String? = nil, tag: String? = nil, ownerEmail: String? = nil, audience: String? = nil, bucketBy: String? = nil, folder: String? = nil, universe: String, targetingGate: String? = nil, allocationPct: Int? = 0, allocationPercent: Double? = nil, salt: String? = nil, params: [String: String]? = nil, groups: [ListExperimentsResponseDataInnerGroupsInner], significanceThreshold: Double? = 0.05, minRuntimeDays: Int? = 0, minSampleSize: Int? = 100, sequentialTesting: Bool? = false, goalMetric: ExperimentInlineMetric? = nil, guardrailMetrics: [ExperimentInlineMetric]? = nil) {
        self.name = name
        self.description = description
        self.hypothesis = hypothesis
        self.tag = tag
        self.ownerEmail = ownerEmail
        self.audience = audience
        self.bucketBy = bucketBy
        self.folder = folder
        self.universe = universe
        self.targetingGate = targetingGate
        self.allocationPct = allocationPct
        self.allocationPercent = allocationPercent
        self.salt = salt
        self.params = params
        self.groups = groups
        self.significanceThreshold = significanceThreshold
        self.minRuntimeDays = minRuntimeDays
        self.minSampleSize = minSampleSize
        self.sequentialTesting = sequentialTesting
        self.goalMetric = goalMetric
        self.guardrailMetrics = guardrailMetrics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case hypothesis
        case tag
        case ownerEmail = "owner_email"
        case audience
        case bucketBy = "bucket_by"
        case folder
        case universe
        case targetingGate = "targeting_gate"
        case allocationPct = "allocation_pct"
        case allocationPercent = "allocation_percent"
        case salt
        case params
        case groups
        case significanceThreshold = "significance_threshold"
        case minRuntimeDays = "min_runtime_days"
        case minSampleSize = "min_sample_size"
        case sequentialTesting = "sequential_testing"
        case goalMetric = "goal_metric"
        case guardrailMetrics = "guardrail_metrics"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(hypothesis, forKey: .hypothesis)
        try container.encodeIfPresent(tag, forKey: .tag)
        try container.encodeIfPresent(ownerEmail, forKey: .ownerEmail)
        try container.encodeIfPresent(audience, forKey: .audience)
        try container.encodeIfPresent(bucketBy, forKey: .bucketBy)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encode(universe, forKey: .universe)
        try container.encodeIfPresent(targetingGate, forKey: .targetingGate)
        try container.encodeIfPresent(allocationPct, forKey: .allocationPct)
        try container.encodeIfPresent(allocationPercent, forKey: .allocationPercent)
        try container.encodeIfPresent(salt, forKey: .salt)
        try container.encodeIfPresent(params, forKey: .params)
        try container.encode(groups, forKey: .groups)
        try container.encodeIfPresent(significanceThreshold, forKey: .significanceThreshold)
        try container.encodeIfPresent(minRuntimeDays, forKey: .minRuntimeDays)
        try container.encodeIfPresent(minSampleSize, forKey: .minSampleSize)
        try container.encodeIfPresent(sequentialTesting, forKey: .sequentialTesting)
        try container.encodeIfPresent(goalMetric, forKey: .goalMetric)
        try container.encodeIfPresent(guardrailMetrics, forKey: .guardrailMetrics)
    }
}

