//
// CreateKeyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The minted key. The plaintext &#x60;key&#x60; is returned **once**, here — it is stored hashed and can never be retrieved again. */
public struct CreateKeyResponse: Codable, JSONEncodable {

    public enum ModelType: String, Codable, CaseIterable {
        case server = "server"
        case client = "client"
        case admin = "admin"
        case ops = "ops"
    }
    public enum Env: String, Codable, CaseIterable {
        case dev = "dev"
        case staging = "staging"
        case prod = "prod"
    }
    /** Stable opaque key id (UUID). Use it to revoke the key. */
    public var id: String
    /** The kind of key that was minted. */
    public var type: ModelType
    /** Environment the key is bound to (`prod` for `admin`/`ops`). */
    public var env: Env
    /** The plaintext API token (e.g. `sdk_server_…`). Returned once — store it now; it cannot be recovered. */
    public var key: String
    /** ISO-8601 expiry, or `null` if the key never expires. */
    public var expiresAt: String?

    public init(id: String, type: ModelType, env: Env, key: String, expiresAt: String?) {
        self.id = id
        self.type = type
        self.env = env
        self.key = key
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case env
        case key
        case expiresAt = "expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(env, forKey: .env)
        try container.encode(key, forKey: .key)
        try container.encode(expiresAt, forKey: .expiresAt)
    }
}


