//
// CreateMetricRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/metrics&#x60;. Requires &#x60;name&#x60;, &#x60;event_name&#x60;, and exactly one of &#x60;query&#x60; / &#x60;query_ir&#x60; — modelled as a &#x60;oneOf&#x60; of two strict variants, so supplying both (or neither) is rejected. */
public enum CreateMetricRequest: Codable, JSONEncodable {
    case typeCreateMetricWithQuery(CreateMetricWithQuery)
    case typeCreateMetricWithQueryIr(CreateMetricWithQueryIr)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeCreateMetricWithQuery(let value):
            try container.encode(value)
        case .typeCreateMetricWithQueryIr(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(CreateMetricWithQuery.self) {
            self = .typeCreateMetricWithQuery(value)
        } else if let value = try? container.decode(CreateMetricWithQueryIr.self) {
            self = .typeCreateMetricWithQueryIr(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of CreateMetricRequest"))
        }
    }
}

