//
// CreateConfigRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/configs&#x60;. &#x60;name&#x60; + &#x60;schema&#x60; required. */
public struct CreateConfigRequest: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: "/^(?:_default|[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?$/")
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 512, pattern: nil)
    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    /** Stable config/killswitch key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Immutable after create. */
    public var name: String
    /** Optional free-form description shown in the dashboard. Max 512 chars. */
    public var description: String?
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** JSON Schema (draft 2020-12) describing the shape of the config value. Top-level `type` must be `'object'`; every published value is validated against this schema. */
    public var schema: [String: AnyCodable]
    public var value: AnyCodable?

    public init(name: String, description: String? = nil, folder: String? = nil, schema: [String: AnyCodable], value: AnyCodable? = nil) {
        self.name = name
        self.description = description
        self.folder = folder
        self.schema = schema
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case folder
        case schema
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encode(schema, forKey: .schema)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

