//
// CreateTriggerConnectorRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/connectors/trigger&#x60;, discriminated on &#x60;provider&#x60; — the trigger-provider subset of &#x60;CreateConnectorRequest&#x60; (no OAuth stubs). Config + credentials arrive together and the connector is usable immediately; creates are idempotent by each provider&#39;s natural key (&#x60;config.routineId&#x60; / &#x60;config.repoUrl&#x60; / &#x60;config.owner&#x60;+&#x60;config.repo&#x60; / &#x60;config.source&#x60;). */
public enum CreateTriggerConnectorRequest: Codable, JSONEncodable {
    case typeCreateClaudeTriggerRequest(CreateClaudeTriggerRequest)
    case typeCreateCopilotTriggerRequest(CreateCopilotTriggerRequest)
    case typeCreateCursorTriggerRequest(CreateCursorTriggerRequest)
    case typeCreateJulesTriggerRequest(CreateJulesTriggerRequest)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeCreateClaudeTriggerRequest(let value):
            try container.encode(value)
        case .typeCreateCopilotTriggerRequest(let value):
            try container.encode(value)
        case .typeCreateCursorTriggerRequest(let value):
            try container.encode(value)
        case .typeCreateJulesTriggerRequest(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case provider = "provider"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .provider)

        switch discriminatorValue {
        case "claude_trigger":
            self = .typeCreateClaudeTriggerRequest(try CreateClaudeTriggerRequest(from: decoder))
        case "copilot_trigger":
            self = .typeCreateCopilotTriggerRequest(try CreateCopilotTriggerRequest(from: decoder))
        case "cursor_trigger":
            self = .typeCreateCursorTriggerRequest(try CreateCursorTriggerRequest(from: decoder))
        case "jules_trigger":
            self = .typeCreateJulesTriggerRequest(try CreateJulesTriggerRequest(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for CreateTriggerConnectorRequest"
                )
            )
        }
    }
}

