//
// CreateJulesTriggerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Create a Google Jules trigger. Both keys are required up front. Idempotent by &#x60;config.source&#x60;. */
public struct CreateJulesTriggerRequest: Codable, JSONEncodable {

    public enum Provider: String, Codable, CaseIterable {
        case julesTrigger = "jules_trigger"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 80, pattern: nil)
    public static let apiKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let opsKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Discriminator. Google Jules trigger. */
    public var provider: Provider
    /** Human-readable connector label. */
    public var name: String? = "Jules trigger"
    /** Events that auto-fire a Jules session. Defaults to empty. */
    public var events: [ConnectorEvent]?
    public var config: JulesTriggerConfig
    /** Jules API key that launches the session (secret). Encrypted into the credentials cipher; never returned. */
    public var apiKey: String
    /** Restricted Shipeasy ops key, embedded in the prompt (Jules exposes no env channel) (secret). Encrypted; never returned. */
    public var opsKey: String
    /** Whether the trigger is active on create. */
    public var enabled: Bool? = true

    public init(provider: Provider, name: String? = "Jules trigger", events: [ConnectorEvent]? = nil, config: JulesTriggerConfig, apiKey: String, opsKey: String, enabled: Bool? = true) {
        self.provider = provider
        self.name = name
        self.events = events
        self.config = config
        self.apiKey = apiKey
        self.opsKey = opsKey
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case name
        case events
        case config
        case apiKey
        case opsKey
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encode(config, forKey: .config)
        try container.encode(apiKey, forKey: .apiKey)
        try container.encode(opsKey, forKey: .opsKey)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

