//
// CreateBugRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Bug-kind fields for &#x60;POST /api/admin/ops&#x60; (sent with &#x60;type: bug&#x60;). */
public struct CreateBugRequest: Codable, JSONEncodable {

    public enum ModelType: String, Codable, CaseIterable {
        case bug = "bug"
    }
    public static let titleRule = StringRule(minLength: 1, maxLength: 200, pattern: "/^\\S(.*\\S)?$/")
    public static let stepsToReproduceRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    public static let actualResultRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    public static let expectedResultRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    public static let userAgentRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    public static let viewportRule = StringRule(minLength: nil, maxLength: 40, pattern: nil)
    /** Discriminator — files a bug. */
    public var type: ModelType
    /** One-line bug title (no leading/trailing whitespace). */
    public var title: String
    /** How to reproduce the bug. */
    public var stepsToReproduce: String? = ""
    /** What actually happened. */
    public var actualResult: String? = ""
    /** What was expected instead. */
    public var expectedResult: String? = ""
    /** Initial triage priority, or `null`. */
    public var priority: OpsItemPriority?
    /** Email of the reporter, or `null`. */
    public var reporterEmail: String?
    /** URL of the page the bug relates to, or `null`. */
    public var pageUrl: String?
    /** Reporter's user-agent string, or `null`. */
    public var userAgent: String?
    /** Reporter's viewport (e.g. `1280x720`), or `null`. */
    public var viewport: String?
    /** Arbitrary capture context, or `null`. */
    public var context: [String: AnyCodable]?
    /** Where this bug's completion notification lands. */
    public var notify: NotificationTarget?

    public init(type: ModelType, title: String, stepsToReproduce: String? = "", actualResult: String? = "", expectedResult: String? = "", priority: OpsItemPriority? = nil, reporterEmail: String? = nil, pageUrl: String? = nil, userAgent: String? = nil, viewport: String? = nil, context: [String: AnyCodable]? = nil, notify: NotificationTarget? = nil) {
        self.type = type
        self.title = title
        self.stepsToReproduce = stepsToReproduce
        self.actualResult = actualResult
        self.expectedResult = expectedResult
        self.priority = priority
        self.reporterEmail = reporterEmail
        self.pageUrl = pageUrl
        self.userAgent = userAgent
        self.viewport = viewport
        self.context = context
        self.notify = notify
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case stepsToReproduce
        case actualResult
        case expectedResult
        case priority
        case reporterEmail
        case pageUrl
        case userAgent
        case viewport
        case context
        case notify
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(stepsToReproduce, forKey: .stepsToReproduce)
        try container.encodeIfPresent(actualResult, forKey: .actualResult)
        try container.encodeIfPresent(expectedResult, forKey: .expectedResult)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(reporterEmail, forKey: .reporterEmail)
        try container.encodeIfPresent(pageUrl, forKey: .pageUrl)
        try container.encodeIfPresent(userAgent, forKey: .userAgent)
        try container.encodeIfPresent(viewport, forKey: .viewport)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(notify, forKey: .notify)
    }
}

