//
// CursorTriggerConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Non-secret config for a Cursor trigger. */
public struct CursorTriggerConfig: Codable, JSONEncodable {

    public static let startingRefRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let projectIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Repo the cloud agent runs against, e.g. `https://github.com/owner/repo`. Idempotency key for the connector. */
    public var repoUrl: String
    /** Optional git ref the run starts from. */
    public var startingRef: String?
    /** Shipeasy project id the run targets. */
    public var projectId: String

    public init(repoUrl: String, startingRef: String? = nil, projectId: String) {
        self.repoUrl = repoUrl
        self.startingRef = startingRef
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case repoUrl
        case startingRef
        case projectId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(repoUrl, forKey: .repoUrl)
        try container.encodeIfPresent(startingRef, forKey: .startingRef)
        try container.encode(projectId, forKey: .projectId)
    }
}

