//
// DeleteAttributeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for &#x60;DELETE /api/admin/attributes/{id}&#x60;. */
public struct DeleteAttributeResponse: Codable, JSONEncodable {

    /** True when the attribute was archived. */
    public var ok: Bool

    public init(ok: Bool) {
        self.ok = ok
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
    }
}

