//
// DeleteGateTemplateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteGateTemplateResponse: Codable, JSONEncodable {

    public enum Ok: Bool, Codable, JSONEncodable, CaseIterable {
        case _true = true
    }
    public var ok: Ok

    public init(ok: Ok) {
        self.ok = ok
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
    }
}

