//
// EnableGateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnableGateResponse: Codable, JSONEncodable {

    public var id: String
    public var enabled: Bool

    public init(id: String, enabled: Bool) {
        self.id = id
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(enabled, forKey: .enabled)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EnableGateResponse: Identifiable {}
