//
// ErrorRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A tracked production error — one row per distinct issue, keyed by &#x60;fingerprint&#x60;. Rows are never created by hand: an ingestion path (worker log drain / the &#x60;see()&#x60; SDK reporter) folds each occurrence into the matching row, bumping &#x60;count&#x60; and &#x60;lastSeenAt&#x60;. The admin surface only lists them, reads one, and flips &#x60;status&#x60;.  Field names are camelCase (the D1 row projected through Drizzle). Many columns are nullable because the reporting source may not supply them. */
public struct ErrorRecord: Codable, JSONEncodable {

    public enum Kind: String, Codable, CaseIterable {
        case caught = "caught"
        case uncaught = "uncaught"
        case unhandledRejection = "unhandled_rejection"
        case network = "network"
        case violation = "violation"
    }
    public enum Status: String, Codable, CaseIterable {
        case _open = "open"
        case resolved = "resolved"
        case ignored = "ignored"
    }
    public static let countRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Stable opaque error id. */
    public var id: String
    /** Project this issue belongs to. */
    public var projectId: String
    /** Stable dedupe key (hash of `errorType` + normalized `message` + consequence). Unique per project — every occurrence with the same fingerprint folds into this one row. */
    public var fingerprint: String
    /** Fingerprint of the issue this one descends from — set when `see()` reported the same error (re-throw) or its `{ cause }` (wrap) at an inner boundary first. Points at another error's `fingerprint` in the same project (soft reference, no FK). `null` for a root issue. */
    public var causedByFingerprint: String?
    /** Error message text. */
    public var message: String
    /** Error class/name, e.g. `TypeError`. `null` when the source didn't supply one. */
    public var errorType: String?
    /** Stack trace of the latest occurrence, or `null` if none was captured. */
    public var stack: String?
    /** Where it surfaced — Worker name (`shipeasy`, `shipeasy-worker`) or `sdk-client` / `sdk-server`. `null` if unknown. */
    public var source: String?
    /** Latest occurrence's raw URL (with ids intact), or `null`. */
    public var url: String?
    /** Distinct, id-normalized route templates this issue has surfaced on, as a JSON-encoded string array (e.g. `[\"https://app/dashboard/#/gates\"]`). UUIDs / numeric ids / opaque tokens are collapsed to `#` so the same route under different ids counts once. `null` if none recorded. */
    public var seenUrls: String?
    /** Consequence subject — `<errorType> causes the <subject> to <outcome>`. `null` if no consequence was reported. */
    public var subject: String?
    /** Consequence outcome — see `subject`. `null` if no consequence was reported. */
    public var outcome: String?
    /** Which SDK side reported it — `client` or `server`. `null` if unknown. */
    public var side: String?
    /** Published env the reporting SDK ran against (e.g. `dev`, `staging`, `prod`). `null` if unknown. */
    public var env: String?
    /** `see()` error kind. `null` when the source didn't classify the occurrence. */
    public var kind: Kind?
    /** Latest occurrence's sanitized extras, JSON-encoded. `null` if none. */
    public var lastExtrasJson: String?
    /** `@shipeasy/sdk` version of the latest occurrence, or `null`. */
    public var sdkVersion: String?
    /** Number of folded occurrences for this fingerprint. */
    public var count: Int
    /** Triage state. `open` is the default; a `resolved` error reopens automatically (ingestion-side) if it recurs; `ignored` is sticky until flipped back here. */
    public var status: Status
    /** ISO-8601 timestamp of the first folded occurrence. */
    public var firstSeenAt: String
    /** ISO-8601 timestamp of the most recent folded occurrence. Rows are ordered by this, descending. */
    public var lastSeenAt: String
    /** ISO-8601 timestamp the row was created. */
    public var createdAt: String
    /** ISO-8601 timestamp of the last mutation (e.g. a status flip). */
    public var updatedAt: String

    public init(id: String, projectId: String, fingerprint: String, causedByFingerprint: String? = nil, message: String, errorType: String? = nil, stack: String? = nil, source: String? = nil, url: String? = nil, seenUrls: String? = nil, subject: String? = nil, outcome: String? = nil, side: String? = nil, env: String? = nil, kind: Kind? = nil, lastExtrasJson: String? = nil, sdkVersion: String? = nil, count: Int, status: Status, firstSeenAt: String, lastSeenAt: String, createdAt: String, updatedAt: String) {
        self.id = id
        self.projectId = projectId
        self.fingerprint = fingerprint
        self.causedByFingerprint = causedByFingerprint
        self.message = message
        self.errorType = errorType
        self.stack = stack
        self.source = source
        self.url = url
        self.seenUrls = seenUrls
        self.subject = subject
        self.outcome = outcome
        self.side = side
        self.env = env
        self.kind = kind
        self.lastExtrasJson = lastExtrasJson
        self.sdkVersion = sdkVersion
        self.count = count
        self.status = status
        self.firstSeenAt = firstSeenAt
        self.lastSeenAt = lastSeenAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case projectId
        case fingerprint
        case causedByFingerprint
        case message
        case errorType
        case stack
        case source
        case url
        case seenUrls
        case subject
        case outcome
        case side
        case env
        case kind
        case lastExtrasJson
        case sdkVersion
        case count
        case status
        case firstSeenAt
        case lastSeenAt
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(fingerprint, forKey: .fingerprint)
        try container.encodeIfPresent(causedByFingerprint, forKey: .causedByFingerprint)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(errorType, forKey: .errorType)
        try container.encodeIfPresent(stack, forKey: .stack)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(seenUrls, forKey: .seenUrls)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(outcome, forKey: .outcome)
        try container.encodeIfPresent(side, forKey: .side)
        try container.encodeIfPresent(env, forKey: .env)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(lastExtrasJson, forKey: .lastExtrasJson)
        try container.encodeIfPresent(sdkVersion, forKey: .sdkVersion)
        try container.encode(count, forKey: .count)
        try container.encode(status, forKey: .status)
        try container.encode(firstSeenAt, forKey: .firstSeenAt)
        try container.encode(lastSeenAt, forKey: .lastSeenAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ErrorRecord: Identifiable {}
