//
// ExperimentInlineMetric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Inline metric — a DSL &#x60;query&#x60;, or an &#x60;event&#x60; (+ &#x60;aggregation&#x60;/&#x60;value&#x60;) the server compiles into one. */
public struct ExperimentInlineMetric: Codable, JSONEncodable {

    public enum Aggregation: String, Codable, CaseIterable {
        case countUsers = "count_users"
        case countEvents = "count_events"
        case retention7d = "retention_7d"
        case retention30d = "retention_30d"
        case sum = "sum"
        case avg = "avg"
    }
    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: "/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/")
    public static let queryRule = StringRule(minLength: 1, maxLength: 4096, pattern: nil)
    public static let eventRule = StringRule(minLength: 1, maxLength: 256, pattern: nil)
    public static let valueRule = StringRule(minLength: 1, maxLength: 256, pattern: nil)
    /** Stable metric key. Single segment or `folder.name`; lowercase letters, digits, `_`/`-`; max 128 chars. */
    public var name: String?
    /** Metric DSL string. Provide this OR `event`. */
    public var query: String?
    /** Event name to build the metric from server-side. Auto-created if missing. */
    public var event: String?
    /** Reducer for the `event` form. Defaults to `count_users`. */
    public var aggregation: Aggregation?
    /** Numeric event property for `sum`/`avg` (with `event`). */
    public var value: String?
    /** Per-experiment override of the metric's default minimum effect of interest (relative, 0–1) — the smallest change worth acting on for this experiment's decision. `null`/omitted inherits the metric default. For a guardrail, the non-inferiority margin. */
    public var minEffectOfInterest: Double?

    public init(name: String? = nil, query: String? = nil, event: String? = nil, aggregation: Aggregation? = nil, value: String? = nil, minEffectOfInterest: Double? = nil) {
        self.name = name
        self.query = query
        self.event = event
        self.aggregation = aggregation
        self.value = value
        self.minEffectOfInterest = minEffectOfInterest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case query
        case event
        case aggregation
        case value
        case minEffectOfInterest = "min_effect_of_interest"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(query, forKey: .query)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(aggregation, forKey: .aggregation)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(minEffectOfInterest, forKey: .minEffectOfInterest)
    }
}

