//
// FireConnectorRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/connectors/{id}/fire&#x60;. Entirely optional — an empty body kicks the run with the provider default. */
public struct FireConnectorRequest: Codable, JSONEncodable {

    /** Optional prompt override for the run. When omitted, each provider falls back to its own default (Claude → the configured `fireText`; the others → their built cold-start prompt). */
    public var text: String?

    public init(text: String? = nil) {
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
    }
}

