//
// GateTemplateRuleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Single targeting predicate as returned by the API. &#x60;value&#x60; is optional here — read-only built-in templates (e.g. &#x60;@owner&#x60;, or presets whose operand is supplied at substitution time) legitimately omit it. Request bodies still require &#x60;value&#x60;. */
public struct GateTemplateRuleResponse: Codable, JSONEncodable {

    public enum Op: String, Codable, CaseIterable {
        case eq = "eq"
        case neq = "neq"
        case _in = "in"
        case notIn = "not_in"
        case gt = "gt"
        case gte = "gte"
        case lt = "lt"
        case lte = "lte"
        case contains = "contains"
        case regex = "regex"
        case semverGt = "semver_gt"
        case semverGte = "semver_gte"
        case semverLt = "semver_lt"
        case semverLte = "semver_lte"
        case gatePass = "gate_pass"
        case expIn = "exp_in"
    }
    /** Attribute key on the evaluation context (e.g. `country`, `plan`, `email`). Matched case-sensitively against `Shipeasy.checkGate(user, name)` input. May be empty on a built-in template whose attribute is supplied at substitution time (e.g. the `exp_in` \"in any experiment\" preset — you fill in the experiment name). */
    public var attr: String
    /** Comparison operator. Equality: `eq`/`neq`. Set membership: `in`/`not_in` (value is an array). Numeric order: `gt`/`gte`/`lt`/`lte`. Semver order: `semver_gt`/`semver_gte`/`semver_lt`/`semver_lte`. String: `contains` (substring), `regex` (JS-flavour pattern). Cross-resource: `gate_pass` (value is another gate's name), `exp_in` (attr is an experiment name, value is a variant / `\"$holdout\"` / `\"$any\"`). */
    public var op: Op
    public var value: AnyCodable?

    public init(attr: String, op: Op, value: AnyCodable? = nil) {
        self.attr = attr
        self.op = op
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attr
        case op
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attr, forKey: .attr)
        try container.encode(op, forKey: .op)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

