//
// GateTemplate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A reusable targeting-rule template. Built-ins are read-only (&#x60;builtin: true&#x60;, stable slug &#x60;id&#x60;); per-project customer templates are &#x60;builtin: false&#x60; with a &#x60;gtpl_…&#x60; id. */
public struct GateTemplate: Codable, JSONEncodable {

    public enum Category: String, Codable, CaseIterable {
        case condition = "condition"
        case rollout = "rollout"
    }
    /** Stable slug for built-ins (`country`), `gtpl_…` for customer templates. */
    public var id: String
    /** Human label shown in pickers (`Country is`). */
    public var name: String
    /** One-liner — feeds the list `query` filter. */
    public var description: String
    /** `condition` = rule-based predicate, `rollout` = percentage bucket. */
    public var category: Category
    /** True when the attribute is request-derived (country/browser/…) and resolved at the SDK edge, so the caller need not pass it. */
    public var auto: Bool
    /** Read-only built-in (`true`) vs editable customer template (`false`). */
    public var builtin: Bool
    /** Display-only icon hint. */
    public var iconKey: String?
    /** The rule definition — copy, substitute the value(s), pass as `rules`. */
    public var rules: [GateTemplateRuleResponse]
    /** ISO-8601 creation timestamp; `null` for built-ins. */
    public var createdAt: String?
    /** ISO-8601 last-mutation timestamp; `null` for built-ins. */
    public var updatedAt: String?

    public init(id: String, name: String, description: String, category: Category, auto: Bool, builtin: Bool, iconKey: String? = nil, rules: [GateTemplateRuleResponse], createdAt: String? = nil, updatedAt: String? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.category = category
        self.auto = auto
        self.builtin = builtin
        self.iconKey = iconKey
        self.rules = rules
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case category
        case auto
        case builtin
        case iconKey
        case rules
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(category, forKey: .category)
        try container.encode(auto, forKey: .auto)
        try container.encode(builtin, forKey: .builtin)
        try container.encodeIfPresent(iconKey, forKey: .iconKey)
        try container.encode(rules, forKey: .rules)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GateTemplate: Identifiable {}
