//
// GateTemplateRuleValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Operand. Shape depends on &#x60;op&#x60;: scalar for &#x60;eq/neq/gt/gte/lt/lte/contains/semver_*&#x60;; array of scalars for &#x60;in/not_in&#x60;; string pattern for &#x60;regex&#x60;; referenced gate name for &#x60;gate_pass&#x60;; variant selector for &#x60;exp_in&#x60;. Required on every request rule (value-ops need it; the valueless built-in presets are read-only and never created via the API). */
public struct GateTemplateRuleValue: Codable, JSONEncodable {


    public enum CodingKeys: CodingKey, CaseIterable {
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
    }
}

