//
// GetAttributeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One targeting attribute row. */
public struct GetAttributeResponse: Codable, JSONEncodable {

    public enum Required: Int, Codable, CaseIterable {
        case _0 = 0
        case _1 = 1
    }
    /** Stable opaque attribute id. */
    public var id: String
    /** Attribute key. */
    public var name: String
    public var type: AttributeType
    /** Allowed values for `enum` attributes, else `null`. */
    public var enumValues: [String]?
    /** Whether the attribute is required (D1 stores the flag as `0`/`1`). */
    public var _required: Required?
    /** Human note, or `null`. */
    public var description: String?
    /** Dotted SDK path, or `null`. */
    public var sdkPath: String?
    /** ISO-8601 creation timestamp. */
    public var createdAt: String?

    public init(id: String, name: String, type: AttributeType, enumValues: [String]? = nil, _required: Required? = nil, description: String? = nil, sdkPath: String? = nil, createdAt: String? = nil) {
        self.id = id
        self.name = name
        self.type = type
        self.enumValues = enumValues
        self._required = _required
        self.description = description
        self.sdkPath = sdkPath
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case type
        case enumValues
        case _required = "required"
        case description
        case sdkPath
        case createdAt
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(enumValues, forKey: .enumValues)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(sdkPath, forKey: .sdkPath)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        type = try container.decode(AttributeType.self, forKey: .type)
        enumValues = try container.decodeIfPresent([String].self, forKey: .enumValues)
        _required = try container.decodeIfPresent(Required.self, forKey: ._required)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        sdkPath = try container.decodeIfPresent(String.self, forKey: .sdkPath)
        createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("name")
        nonAdditionalPropertyKeys.insert("type")
        nonAdditionalPropertyKeys.insert("enumValues")
        nonAdditionalPropertyKeys.insert("required")
        nonAdditionalPropertyKeys.insert("description")
        nonAdditionalPropertyKeys.insert("sdkPath")
        nonAdditionalPropertyKeys.insert("createdAt")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetAttributeResponse: Identifiable {}
