//
// GetCurrentProjectResponseModuleTranslations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Whether the i18n/translations module is enabled. */
public struct GetCurrentProjectResponseModuleTranslations: Codable, JSONEncodable {


    public enum CodingKeys: CodingKey, CaseIterable {
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
    }
}

