//
// GetCurrentProjectResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The project the caller&#39;s auth header resolves to. The shape is open — additional project fields may be present. */
public struct GetCurrentProjectResponse: Codable, JSONEncodable {

    public enum Plan: String, Codable, CaseIterable {
        case free = "free"
        case pro = "pro"
        case business = "business"
        case enterprise = "enterprise"
    }
    public enum Status: String, Codable, CaseIterable {
        case active = "active"
        case inactive = "inactive"
    }
    public enum BillingInterval: String, Codable, CaseIterable {
        case monthly = "monthly"
        case annual = "annual"
    }
    /** Stable opaque project id. */
    public var id: String
    /** Project name. */
    public var name: String
    /** Project domain, or `null` if unset. */
    public var domain: String?
    /** Email of the account that owns the project. */
    public var ownerEmail: String
    /** Billing plan tier. */
    public var plan: Plan
    /** Project lifecycle status. */
    public var status: Status
    /** Stripe subscription status (`none`, `active`, `trialing`, `past_due`, …). */
    public var subscriptionStatus: String
    /** Billing cadence. */
    public var billingInterval: BillingInterval
    /** ISO-8601 end of the current billing period, or `null`. */
    public var currentPeriodEnd: String?
    /** ISO-8601 trial end, or `null` if not trialing. */
    public var trialEndsAt: String?
    /** `1` if the subscription is set to cancel at period end, else `0`. */
    public var cancelAtPeriodEnd: Double
    public var moduleTranslations: GetCurrentProjectResponseModuleTranslations
    public var moduleConfigs: GetCurrentProjectResponseModuleTranslations
    public var moduleGates: GetCurrentProjectResponseModuleTranslations
    public var moduleExperiments: GetCurrentProjectResponseModuleTranslations
    public var moduleFeedback: GetCurrentProjectResponseModuleTranslations
    /** Verdict power guard — minimum users per arm before a ship/hold verdict. */
    public var minSampleSize: Int?
    /** Minimum days an experiment must run before a verdict (peeking guard). */
    public var minRuntimeDays: Int?
    /** Target statistical power (1−β) feeding the realized-MDE calculation. */
    public var defaultPower: Double?
    /** Confidence level for the interval surfaced on results. */
    public var ciConfidence: Double?
    /** Default traffic allocation (basis points) new experiments start with. */
    public var defaultAllocationPct: Int?
    /** Default winsorization percentile new metrics start with. */
    public var defaultWinsorizePct: Int?
    /** Default minimum effect of interest (relative, 0–1) new metrics start with, or null. */
    public var defaultMei: Double?
    /** CUPED baseline window — days of pre-experiment history, frozen at start. */
    public var cupedBaselineDays: Int?
    /** CUPED selection-bias guard — min share of users with a baseline, else skip. */
    public var cupedMinOverlap: Double?
    /** CUPED — minimum users with a baseline before it runs at all. */
    public var cupedMinBaselineUsers: Int?
    /** mSPRT prior width — τ = minimum effect of interest × this factor. */
    public var msprtTauMeiFactor: Double?
    /** mSPRT fallback prior width — τ = this × control SD when no MEI is set. */
    public var msprtTauSdFactor: Double?
    /** SRM chi-square p-value below which the run is called invalid. */
    public var srmThreshold: Double?
    /** ISO-8601 timestamp of project creation. */
    public var createdAt: String
    /** ISO-8601 timestamp of last update. */
    public var updatedAt: String

    public init(id: String, name: String, domain: String?, ownerEmail: String, plan: Plan, status: Status, subscriptionStatus: String, billingInterval: BillingInterval, currentPeriodEnd: String?, trialEndsAt: String?, cancelAtPeriodEnd: Double, moduleTranslations: GetCurrentProjectResponseModuleTranslations, moduleConfigs: GetCurrentProjectResponseModuleTranslations, moduleGates: GetCurrentProjectResponseModuleTranslations, moduleExperiments: GetCurrentProjectResponseModuleTranslations, moduleFeedback: GetCurrentProjectResponseModuleTranslations, minSampleSize: Int? = nil, minRuntimeDays: Int? = nil, defaultPower: Double? = nil, ciConfidence: Double? = nil, defaultAllocationPct: Int? = nil, defaultWinsorizePct: Int? = nil, defaultMei: Double? = nil, cupedBaselineDays: Int? = nil, cupedMinOverlap: Double? = nil, cupedMinBaselineUsers: Int? = nil, msprtTauMeiFactor: Double? = nil, msprtTauSdFactor: Double? = nil, srmThreshold: Double? = nil, createdAt: String, updatedAt: String) {
        self.id = id
        self.name = name
        self.domain = domain
        self.ownerEmail = ownerEmail
        self.plan = plan
        self.status = status
        self.subscriptionStatus = subscriptionStatus
        self.billingInterval = billingInterval
        self.currentPeriodEnd = currentPeriodEnd
        self.trialEndsAt = trialEndsAt
        self.cancelAtPeriodEnd = cancelAtPeriodEnd
        self.moduleTranslations = moduleTranslations
        self.moduleConfigs = moduleConfigs
        self.moduleGates = moduleGates
        self.moduleExperiments = moduleExperiments
        self.moduleFeedback = moduleFeedback
        self.minSampleSize = minSampleSize
        self.minRuntimeDays = minRuntimeDays
        self.defaultPower = defaultPower
        self.ciConfidence = ciConfidence
        self.defaultAllocationPct = defaultAllocationPct
        self.defaultWinsorizePct = defaultWinsorizePct
        self.defaultMei = defaultMei
        self.cupedBaselineDays = cupedBaselineDays
        self.cupedMinOverlap = cupedMinOverlap
        self.cupedMinBaselineUsers = cupedMinBaselineUsers
        self.msprtTauMeiFactor = msprtTauMeiFactor
        self.msprtTauSdFactor = msprtTauSdFactor
        self.srmThreshold = srmThreshold
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case domain
        case ownerEmail
        case plan
        case status
        case subscriptionStatus
        case billingInterval
        case currentPeriodEnd
        case trialEndsAt
        case cancelAtPeriodEnd
        case moduleTranslations
        case moduleConfigs
        case moduleGates
        case moduleExperiments
        case moduleFeedback
        case minSampleSize
        case minRuntimeDays
        case defaultPower
        case ciConfidence
        case defaultAllocationPct
        case defaultWinsorizePct
        case defaultMei
        case cupedBaselineDays
        case cupedMinOverlap
        case cupedMinBaselineUsers
        case msprtTauMeiFactor
        case msprtTauSdFactor
        case srmThreshold
        case createdAt
        case updatedAt
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(domain, forKey: .domain)
        try container.encode(ownerEmail, forKey: .ownerEmail)
        try container.encode(plan, forKey: .plan)
        try container.encode(status, forKey: .status)
        try container.encode(subscriptionStatus, forKey: .subscriptionStatus)
        try container.encode(billingInterval, forKey: .billingInterval)
        try container.encode(currentPeriodEnd, forKey: .currentPeriodEnd)
        try container.encode(trialEndsAt, forKey: .trialEndsAt)
        try container.encode(cancelAtPeriodEnd, forKey: .cancelAtPeriodEnd)
        try container.encode(moduleTranslations, forKey: .moduleTranslations)
        try container.encode(moduleConfigs, forKey: .moduleConfigs)
        try container.encode(moduleGates, forKey: .moduleGates)
        try container.encode(moduleExperiments, forKey: .moduleExperiments)
        try container.encode(moduleFeedback, forKey: .moduleFeedback)
        try container.encodeIfPresent(minSampleSize, forKey: .minSampleSize)
        try container.encodeIfPresent(minRuntimeDays, forKey: .minRuntimeDays)
        try container.encodeIfPresent(defaultPower, forKey: .defaultPower)
        try container.encodeIfPresent(ciConfidence, forKey: .ciConfidence)
        try container.encodeIfPresent(defaultAllocationPct, forKey: .defaultAllocationPct)
        try container.encodeIfPresent(defaultWinsorizePct, forKey: .defaultWinsorizePct)
        try container.encodeIfPresent(defaultMei, forKey: .defaultMei)
        try container.encodeIfPresent(cupedBaselineDays, forKey: .cupedBaselineDays)
        try container.encodeIfPresent(cupedMinOverlap, forKey: .cupedMinOverlap)
        try container.encodeIfPresent(cupedMinBaselineUsers, forKey: .cupedMinBaselineUsers)
        try container.encodeIfPresent(msprtTauMeiFactor, forKey: .msprtTauMeiFactor)
        try container.encodeIfPresent(msprtTauSdFactor, forKey: .msprtTauSdFactor)
        try container.encodeIfPresent(srmThreshold, forKey: .srmThreshold)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        domain = try container.decodeIfPresent(String.self, forKey: .domain)
        ownerEmail = try container.decode(String.self, forKey: .ownerEmail)
        plan = try container.decode(Plan.self, forKey: .plan)
        status = try container.decode(Status.self, forKey: .status)
        subscriptionStatus = try container.decode(String.self, forKey: .subscriptionStatus)
        billingInterval = try container.decode(BillingInterval.self, forKey: .billingInterval)
        currentPeriodEnd = try container.decodeIfPresent(String.self, forKey: .currentPeriodEnd)
        trialEndsAt = try container.decodeIfPresent(String.self, forKey: .trialEndsAt)
        cancelAtPeriodEnd = try container.decode(Double.self, forKey: .cancelAtPeriodEnd)
        moduleTranslations = try container.decode(GetCurrentProjectResponseModuleTranslations.self, forKey: .moduleTranslations)
        moduleConfigs = try container.decode(GetCurrentProjectResponseModuleTranslations.self, forKey: .moduleConfigs)
        moduleGates = try container.decode(GetCurrentProjectResponseModuleTranslations.self, forKey: .moduleGates)
        moduleExperiments = try container.decode(GetCurrentProjectResponseModuleTranslations.self, forKey: .moduleExperiments)
        moduleFeedback = try container.decode(GetCurrentProjectResponseModuleTranslations.self, forKey: .moduleFeedback)
        minSampleSize = try container.decodeIfPresent(Int.self, forKey: .minSampleSize)
        minRuntimeDays = try container.decodeIfPresent(Int.self, forKey: .minRuntimeDays)
        defaultPower = try container.decodeIfPresent(Double.self, forKey: .defaultPower)
        ciConfidence = try container.decodeIfPresent(Double.self, forKey: .ciConfidence)
        defaultAllocationPct = try container.decodeIfPresent(Int.self, forKey: .defaultAllocationPct)
        defaultWinsorizePct = try container.decodeIfPresent(Int.self, forKey: .defaultWinsorizePct)
        defaultMei = try container.decodeIfPresent(Double.self, forKey: .defaultMei)
        cupedBaselineDays = try container.decodeIfPresent(Int.self, forKey: .cupedBaselineDays)
        cupedMinOverlap = try container.decodeIfPresent(Double.self, forKey: .cupedMinOverlap)
        cupedMinBaselineUsers = try container.decodeIfPresent(Int.self, forKey: .cupedMinBaselineUsers)
        msprtTauMeiFactor = try container.decodeIfPresent(Double.self, forKey: .msprtTauMeiFactor)
        msprtTauSdFactor = try container.decodeIfPresent(Double.self, forKey: .msprtTauSdFactor)
        srmThreshold = try container.decodeIfPresent(Double.self, forKey: .srmThreshold)
        createdAt = try container.decode(String.self, forKey: .createdAt)
        updatedAt = try container.decode(String.self, forKey: .updatedAt)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("name")
        nonAdditionalPropertyKeys.insert("domain")
        nonAdditionalPropertyKeys.insert("ownerEmail")
        nonAdditionalPropertyKeys.insert("plan")
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("subscriptionStatus")
        nonAdditionalPropertyKeys.insert("billingInterval")
        nonAdditionalPropertyKeys.insert("currentPeriodEnd")
        nonAdditionalPropertyKeys.insert("trialEndsAt")
        nonAdditionalPropertyKeys.insert("cancelAtPeriodEnd")
        nonAdditionalPropertyKeys.insert("moduleTranslations")
        nonAdditionalPropertyKeys.insert("moduleConfigs")
        nonAdditionalPropertyKeys.insert("moduleGates")
        nonAdditionalPropertyKeys.insert("moduleExperiments")
        nonAdditionalPropertyKeys.insert("moduleFeedback")
        nonAdditionalPropertyKeys.insert("minSampleSize")
        nonAdditionalPropertyKeys.insert("minRuntimeDays")
        nonAdditionalPropertyKeys.insert("defaultPower")
        nonAdditionalPropertyKeys.insert("ciConfidence")
        nonAdditionalPropertyKeys.insert("defaultAllocationPct")
        nonAdditionalPropertyKeys.insert("defaultWinsorizePct")
        nonAdditionalPropertyKeys.insert("defaultMei")
        nonAdditionalPropertyKeys.insert("cupedBaselineDays")
        nonAdditionalPropertyKeys.insert("cupedMinOverlap")
        nonAdditionalPropertyKeys.insert("cupedMinBaselineUsers")
        nonAdditionalPropertyKeys.insert("msprtTauMeiFactor")
        nonAdditionalPropertyKeys.insert("msprtTauSdFactor")
        nonAdditionalPropertyKeys.insert("srmThreshold")
        nonAdditionalPropertyKeys.insert("createdAt")
        nonAdditionalPropertyKeys.insert("updatedAt")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


