//
// GetExperimentTimeseriesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetExperimentTimeseriesResponse: Codable, JSONEncodable {

    public var experiment: GetExperimentResultsResponseExperiment
    public var series: [GetExperimentTimeseriesResponseSeriesInner]

    public init(experiment: GetExperimentResultsResponseExperiment, series: [GetExperimentTimeseriesResponseSeriesInner]) {
        self.experiment = experiment
        self.series = series
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case experiment
        case series
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(experiment, forKey: .experiment)
        try container.encode(series, forKey: .series)
    }
}

