//
// GetExperimentResultsResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetExperimentResultsResponseResultsInner: Codable, JSONEncodable {

    public var metric: String
    public var groupName: String
    /** Date slice (`YYYY-MM-DD`). */
    public var ds: String
    public var n: Double?
    public var mean: Double?
    public var deltaPct: Double?
    public var pValue: Double?
    /** `1` if sample-ratio mismatch detected, else `0`. */
    public var srmDetected: Double?
    /** Realized minimum detectable effect (absolute, in metric units) — the smallest true effect this run could detect at the experiment's significance level and target power GIVEN the observed variance and per-arm sample sizes. A derived OUTPUT, not an input knob; compare it against the metric's minimum effect of interest to judge whether the run is adequately powered. `null` on the control row and on empty arms. */
    public var realizedMde: Double?

    public init(metric: String, groupName: String, ds: String, n: Double?, mean: Double?, deltaPct: Double?, pValue: Double?, srmDetected: Double?, realizedMde: Double?) {
        self.metric = metric
        self.groupName = groupName
        self.ds = ds
        self.n = n
        self.mean = mean
        self.deltaPct = deltaPct
        self.pValue = pValue
        self.srmDetected = srmDetected
        self.realizedMde = realizedMde
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metric
        case groupName = "group_name"
        case ds
        case n
        case mean
        case deltaPct = "delta_pct"
        case pValue = "p_value"
        case srmDetected = "srm_detected"
        case realizedMde = "realized_mde"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(metric, forKey: .metric)
        try container.encode(groupName, forKey: .groupName)
        try container.encode(ds, forKey: .ds)
        try container.encode(n, forKey: .n)
        try container.encode(mean, forKey: .mean)
        try container.encode(deltaPct, forKey: .deltaPct)
        try container.encode(pValue, forKey: .pValue)
        try container.encode(srmDetected, forKey: .srmDetected)
        try container.encode(realizedMde, forKey: .realizedMde)
    }
}

