//
// GetOpsItemResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One queue item, any of the five types. Shared fields apply to all; &#x60;stepsToReproduce&#x60;/&#x60;actualResult&#x60;/&#x60;expectedResult&#x60; are bug-specific, &#x60;description&#x60;/&#x60;useCase&#x60; feature-specific. The auto-collected browser fields (page URL, user-agent, viewport) live under &#x60;context.browser&#x60; for bug/feature. &#x60;context&#x60; also carries the hydrated per-type payload for auto-filed &#x60;error&#x60;/&#x60;alert&#x60;/&#x60;measure_plan&#x60; tickets, &#x60;attachments&#x60; lists any uploaded files, and &#x60;related&#x60; gives deep links to the underlying resources. */
public struct GetOpsItemResponse: Codable, JSONEncodable {

    public enum ModelType: String, Codable, CaseIterable {
        case bug = "bug"
        case featureRequest = "feature_request"
        case error = "error"
        case alert = "alert"
        case measurePlan = "measure_plan"
    }
    public enum Source: String, Codable, CaseIterable {
        case team = "team"
        case system = "system"
    }
    /** Stable opaque item id. */
    public var id: String
    /** Per-project item number (the `#7` handle), or `null` if unnumbered. */
    public var number: Double?
    /** Queue item type. `bug` and `feature_request` are user-fileable; `error`, `alert`, and `measure_plan` tickets are auto-filed by the platform (a tracked production error, a metric-threshold alert, and an assistant-proposed measurement plan respectively). */
    public var type: ModelType
    /** One-line item title (all types). */
    public var title: String
    public var status: OpsItemStatus
    /** Triage priority, or `null` if not yet set (all types). */
    public var priority: OpsItemPriority?
    /** How the item was filed: `team` (a human admin/teammate — bug/feature) or `system` (auto-filed — error/alert/measure_plan). */
    public var source: Source?
    /** Stable key of the originating record for auto-filed tickets (error fingerprint, `<alert source>:<dedupeKey>`, or measurement-plan ref); `null` for human-filed bugs/features. */
    public var sourceRef: String?
    /** Reporter email (bug/feature), or `null`. */
    public var reporterEmail: String?
    /** Reproduction steps — populated for `bug`, empty string otherwise. */
    public var stepsToReproduce: String?
    /** What actually happened — `bug` only, empty string otherwise. */
    public var actualResult: String?
    /** What was expected — `bug` only, empty string otherwise. */
    public var expectedResult: String?
    /** Feature description — populated for `feature_request`, empty string otherwise. */
    public var description: String?
    /** Feature use case — `feature_request` only, empty string otherwise. */
    public var useCase: String?
    /** Type-specific capture context. For `bug`/`feature_request` it carries `browser` (the auto-collected page URL / user-agent / viewport). For auto-filed tickets it carries the hydrated `error`, `alert`, or `measurePlan` block. `null` only for legacy rows with nothing captured. */
    public var context: OpsItemContext?
    /** Files attached to the report — screenshots, recordings, logs. Populated for `bug`/`feature_request`; always an empty array for auto-filed `error`/`alert`/`measure_plan` tickets. Fetch each via its `fetchUrl` with the same admin/ops key (the download route is ops-key allow-listed). */
    public var attachments: [OpsItemAttachment]
    public var related: OpsItemRelated
    /** Per-connector linkage recorded for this item, keyed by connector provider. Populated as connectors act on the item (e.g. GitHub opens an issue, Slack posts a message); more than one provider can be present at once. `null` if no connector has touched the item. */
    public var connectorData: ConnectorData?
    /** Per-item completion-notification target, or `null` (falls back to the project default). */
    public var notify: NotificationTarget?
    /** ISO-8601 creation timestamp. */
    public var createdAt: String
    /** ISO-8601 last-update timestamp. */
    public var updatedAt: String?

    public init(id: String, number: Double?, type: ModelType, title: String, status: OpsItemStatus, priority: OpsItemPriority?, source: Source? = nil, sourceRef: String? = nil, reporterEmail: String? = nil, stepsToReproduce: String? = nil, actualResult: String? = nil, expectedResult: String? = nil, description: String? = nil, useCase: String? = nil, context: OpsItemContext?, attachments: [OpsItemAttachment], related: OpsItemRelated, connectorData: ConnectorData? = nil, notify: NotificationTarget? = nil, createdAt: String, updatedAt: String? = nil) {
        self.id = id
        self.number = number
        self.type = type
        self.title = title
        self.status = status
        self.priority = priority
        self.source = source
        self.sourceRef = sourceRef
        self.reporterEmail = reporterEmail
        self.stepsToReproduce = stepsToReproduce
        self.actualResult = actualResult
        self.expectedResult = expectedResult
        self.description = description
        self.useCase = useCase
        self.context = context
        self.attachments = attachments
        self.related = related
        self.connectorData = connectorData
        self.notify = notify
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
        case type
        case title
        case status
        case priority
        case source
        case sourceRef
        case reporterEmail
        case stepsToReproduce
        case actualResult
        case expectedResult
        case description
        case useCase
        case context
        case attachments
        case related
        case connectorData
        case notify
        case createdAt
        case updatedAt
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(number, forKey: .number)
        try container.encode(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encode(status, forKey: .status)
        try container.encode(priority, forKey: .priority)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(sourceRef, forKey: .sourceRef)
        try container.encodeIfPresent(reporterEmail, forKey: .reporterEmail)
        try container.encodeIfPresent(stepsToReproduce, forKey: .stepsToReproduce)
        try container.encodeIfPresent(actualResult, forKey: .actualResult)
        try container.encodeIfPresent(expectedResult, forKey: .expectedResult)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(useCase, forKey: .useCase)
        try container.encode(context, forKey: .context)
        try container.encode(attachments, forKey: .attachments)
        try container.encode(related, forKey: .related)
        try container.encodeIfPresent(connectorData, forKey: .connectorData)
        try container.encodeIfPresent(notify, forKey: .notify)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        number = try container.decodeIfPresent(Double.self, forKey: .number)
        type = try container.decode(ModelType.self, forKey: .type)
        title = try container.decode(String.self, forKey: .title)
        status = try container.decode(OpsItemStatus.self, forKey: .status)
        priority = try container.decodeIfPresent(OpsItemPriority.self, forKey: .priority)
        source = try container.decodeIfPresent(Source.self, forKey: .source)
        sourceRef = try container.decodeIfPresent(String.self, forKey: .sourceRef)
        reporterEmail = try container.decodeIfPresent(String.self, forKey: .reporterEmail)
        stepsToReproduce = try container.decodeIfPresent(String.self, forKey: .stepsToReproduce)
        actualResult = try container.decodeIfPresent(String.self, forKey: .actualResult)
        expectedResult = try container.decodeIfPresent(String.self, forKey: .expectedResult)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        useCase = try container.decodeIfPresent(String.self, forKey: .useCase)
        context = try container.decodeIfPresent(OpsItemContext.self, forKey: .context)
        attachments = try container.decode([OpsItemAttachment].self, forKey: .attachments)
        related = try container.decode(OpsItemRelated.self, forKey: .related)
        connectorData = try container.decodeIfPresent(ConnectorData.self, forKey: .connectorData)
        notify = try container.decodeIfPresent(NotificationTarget.self, forKey: .notify)
        createdAt = try container.decode(String.self, forKey: .createdAt)
        updatedAt = try container.decodeIfPresent(String.self, forKey: .updatedAt)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("number")
        nonAdditionalPropertyKeys.insert("type")
        nonAdditionalPropertyKeys.insert("title")
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("priority")
        nonAdditionalPropertyKeys.insert("source")
        nonAdditionalPropertyKeys.insert("sourceRef")
        nonAdditionalPropertyKeys.insert("reporterEmail")
        nonAdditionalPropertyKeys.insert("stepsToReproduce")
        nonAdditionalPropertyKeys.insert("actualResult")
        nonAdditionalPropertyKeys.insert("expectedResult")
        nonAdditionalPropertyKeys.insert("description")
        nonAdditionalPropertyKeys.insert("useCase")
        nonAdditionalPropertyKeys.insert("context")
        nonAdditionalPropertyKeys.insert("attachments")
        nonAdditionalPropertyKeys.insert("related")
        nonAdditionalPropertyKeys.insert("connectorData")
        nonAdditionalPropertyKeys.insert("notify")
        nonAdditionalPropertyKeys.insert("createdAt")
        nonAdditionalPropertyKeys.insert("updatedAt")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


