//
// GithubConnectorDataIssue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The GitHub issue this item opened. */
public struct GithubConnectorDataIssue: Codable, JSONEncodable {

    /** GitHub issue number. */
    public var number: Double
    /** HTML URL of the opened issue. */
    public var url: String
    /** Repository owner (org or user). */
    public var owner: String
    /** Repository name. */
    public var repo: String
    /** ISO-8601 timestamp the issue was opened. */
    public var createdAt: String?

    public init(number: Double, url: String, owner: String, repo: String, createdAt: String? = nil) {
        self.number = number
        self.url = url
        self.owner = owner
        self.repo = repo
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case url
        case owner
        case repo
        case createdAt
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(number, forKey: .number)
        try container.encode(url, forKey: .url)
        try container.encode(owner, forKey: .owner)
        try container.encode(repo, forKey: .repo)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        number = try container.decode(Double.self, forKey: .number)
        url = try container.decode(String.self, forKey: .url)
        owner = try container.decode(String.self, forKey: .owner)
        repo = try container.decode(String.self, forKey: .repo)
        createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("number")
        nonAdditionalPropertyKeys.insert("url")
        nonAdditionalPropertyKeys.insert("owner")
        nonAdditionalPropertyKeys.insert("repo")
        nonAdditionalPropertyKeys.insert("createdAt")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

