//
// KeyRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A single API key as returned by the list endpoint. Response fields are snake_case. The raw token is never returned here — only its &#x60;last4&#x60; tail. &#x60;last4&#x60; and the typed &#x60;scopes&#x60; may be &#x60;null&#x60; for keys minted before those columns existed. */
public struct KeyRecord: Codable, JSONEncodable {

    public enum ModelType: String, Codable, CaseIterable {
        case server = "server"
        case client = "client"
        case admin = "admin"
        case ops = "ops"
    }
    public enum Env: String, Codable, CaseIterable {
        case dev = "dev"
        case staging = "staging"
        case prod = "prod"
    }
    /** Stable opaque key id (UUID). Use it to revoke the key. */
    public var id: String
    /** Key kind. `server` (back-end, full SDK auth), `client` (public, browser-embeddable), `admin` (CLI/devtools auth token), `ops` (restricted unattended-trigger credential). */
    public var type: ModelType
    /** Environment the key is bound to. The worker derives the read env from the key, so this is the isolation boundary. `admin`/`ops` keys are env-agnostic and pinned to `prod`. */
    public var env: Env
    /** ISO-8601 timestamp the key was minted. */
    public var createdAt: String
    /** ISO-8601 timestamp the key was revoked, or `null` while the key is active. */
    public var revokedAt: String?
    /** ISO-8601 expiry, or `null` for a key that never expires. `admin` keys are fixed at 90 days; `ops` keys use a short sliding window. */
    public var expiresAt: String?
    /** Email of the human or actor that minted the key, or `null` when not attributable (e.g. CLI device-flow). */
    public var createdByEmail: String?
    /** Human label for the key. `null` for unnamed dashboard mints; programmatic mints auto-name themselves. */
    public var name: String?
    /** Permission strings recorded on the key for audit/display, or `null` when none were set. */
    public var scopes: [String]?
    /** Last 4 characters of the raw token, so the dashboard mask is matchable against the held key. `null` for keys minted before this column. */
    public var last4: String?

    public init(id: String, type: ModelType, env: Env, createdAt: String, revokedAt: String?, expiresAt: String?, createdByEmail: String?, name: String?, scopes: [String]?, last4: String?) {
        self.id = id
        self.type = type
        self.env = env
        self.createdAt = createdAt
        self.revokedAt = revokedAt
        self.expiresAt = expiresAt
        self.createdByEmail = createdByEmail
        self.name = name
        self.scopes = scopes
        self.last4 = last4
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case env
        case createdAt = "created_at"
        case revokedAt = "revoked_at"
        case expiresAt = "expires_at"
        case createdByEmail = "created_by_email"
        case name
        case scopes
        case last4
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(env, forKey: .env)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(revokedAt, forKey: .revokedAt)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(createdByEmail, forKey: .createdByEmail)
        try container.encode(name, forKey: .name)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(last4, forKey: .last4)
    }
}


