//
// KillswitchValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Runtime killswitch payload returned to SDKs. */
public struct KillswitchValue: Codable, JSONEncodable {

    /** Default boolean delivered when no `switches` entry matches. */
    public var value: Bool
    /** Per-switch overrides; a matching key takes precedence over `value`. */
    public var switches: [String: Bool]?

    public init(value: Bool, switches: [String: Bool]? = nil) {
        self.value = value
        self.switches = switches
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case switches
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(switches, forKey: .switches)
    }
}

