//
// LinkPrToOpsItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/ops/{handle}/link-pr&#x60;. */
public struct LinkPrToOpsItemRequest: Codable, JSONEncodable {

    public static let prNumberRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    /** PR number to record on the item. `null` unlinks the PR. */
    public var prNumber: Int?
    /** Explicit PR URL. Required for error/alert tickets (no GitHub issue to derive the URL from). */
    public var prUrl: String?

    public init(prNumber: Int?, prUrl: String? = nil) {
        self.prNumber = prNumber
        self.prUrl = prUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case prNumber
        case prUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(prNumber, forKey: .prNumber)
        try container.encodeIfPresent(prUrl, forKey: .prUrl)
    }
}

