//
// ListConfigsResponseDataInnerEnvsValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListConfigsResponseDataInnerEnvsValue: Codable, JSONEncodable {

    public static let versionRule = NumericRule<Int>(minimum: -9007199254740991, exclusiveMinimum: false, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    /** Monotonically increasing version per env. */
    public var version: Int
    /** ISO-8601 publish timestamp. */
    public var publishedAt: String
    /** Email/id of the actor who published this version. */
    public var publishedBy: String

    public init(version: Int, publishedAt: String, publishedBy: String) {
        self.version = version
        self.publishedAt = publishedAt
        self.publishedBy = publishedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case publishedAt
        case publishedBy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(publishedAt, forKey: .publishedAt)
        try container.encode(publishedBy, forKey: .publishedBy)
    }
}

