//
// ListOpsCommentsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for &#x60;GET /api/admin/ops/{handle}/comments&#x60; — the thread, oldest first. */
public struct ListOpsCommentsResponse: Codable, JSONEncodable {

    public var comments: [OpsComment]

    public init(comments: [OpsComment]) {
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comments, forKey: .comments)
    }
}

