//
// ListI18nKeysResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A page of i18n keys plus the total count. (The client also tolerates a bare array.) */
public struct ListI18nKeysResponse: Codable, JSONEncodable {

    /** The page of matching keys. */
    public var keys: [ListI18nKeysResponseKeysInner]
    /** Total matching keys across all pages (ignores `limit`/`offset`). */
    public var total: Double

    public init(keys: [ListI18nKeysResponseKeysInner], total: Double) {
        self.keys = keys
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keys
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keys, forKey: .keys)
        try container.encode(total, forKey: .total)
    }
}

