//
// ListOpsItemsResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One queue item — any type. */
public struct ListOpsItemsResponseInner: Codable, JSONEncodable {

    public enum ModelType: String, Codable, CaseIterable {
        case bug = "bug"
        case featureRequest = "feature_request"
        case error = "error"
        case alert = "alert"
        case measurePlan = "measure_plan"
    }
    /** Stable opaque item id. */
    public var id: String
    /** Per-project item number (the `#7` handle), or `null` if unnumbered. */
    public var number: Double?
    /** Queue item type. `bug` and `feature_request` are user-fileable; `error`, `alert`, and `measure_plan` tickets are auto-filed by the platform (a tracked production error, a metric-threshold alert, and an assistant-proposed measurement plan respectively). */
    public var type: ModelType
    /** One-line item title. */
    public var title: String
    public var status: OpsItemStatus
    /** Triage priority, or `null` if not yet set. */
    public var priority: OpsItemPriority?
    /** Source reference for auto-filed tickets (e.g. an error fingerprint). */
    public var sourceRef: String?
    /** ISO-8601 creation timestamp. */
    public var createdAt: String

    public init(id: String, number: Double?, type: ModelType, title: String, status: OpsItemStatus, priority: OpsItemPriority?, sourceRef: String? = nil, createdAt: String) {
        self.id = id
        self.number = number
        self.type = type
        self.title = title
        self.status = status
        self.priority = priority
        self.sourceRef = sourceRef
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
        case type
        case title
        case status
        case priority
        case sourceRef
        case createdAt
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(number, forKey: .number)
        try container.encode(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encode(status, forKey: .status)
        try container.encode(priority, forKey: .priority)
        try container.encodeIfPresent(sourceRef, forKey: .sourceRef)
        try container.encode(createdAt, forKey: .createdAt)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        number = try container.decodeIfPresent(Double.self, forKey: .number)
        type = try container.decode(ModelType.self, forKey: .type)
        title = try container.decode(String.self, forKey: .title)
        status = try container.decode(OpsItemStatus.self, forKey: .status)
        priority = try container.decodeIfPresent(OpsItemPriority.self, forKey: .priority)
        sourceRef = try container.decodeIfPresent(String.self, forKey: .sourceRef)
        createdAt = try container.decode(String.self, forKey: .createdAt)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("number")
        nonAdditionalPropertyKeys.insert("type")
        nonAdditionalPropertyKeys.insert("title")
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("priority")
        nonAdditionalPropertyKeys.insert("sourceRef")
        nonAdditionalPropertyKeys.insert("createdAt")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ListOpsItemsResponseInner: Identifiable {}
