//
// ListConfigsResponseDataInnerDraftsValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListConfigsResponseDataInnerDraftsValue: Codable, JSONEncodable {

    public static let baseVersionRule = NumericRule<Int>(minimum: -9007199254740991, exclusiveMinimum: false, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    /** ISO-8601 last-edit timestamp on the draft. */
    public var updatedAt: String
    /** Email/id of the actor who last edited the draft. */
    public var authorEmail: String
    /** Published version the draft was forked from. */
    public var baseVersion: Int

    public init(updatedAt: String, authorEmail: String, baseVersion: Int) {
        self.updatedAt = updatedAt
        self.authorEmail = authorEmail
        self.baseVersion = baseVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updatedAt
        case authorEmail
        case baseVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(authorEmail, forKey: .authorEmail)
        try container.encode(baseVersion, forKey: .baseVersion)
    }
}

