//
// ListGatesResponseDataInnerStackInnerOneOfRamp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Linear rollout ramp. The effective rollout % interpolates &#x60;from&#x60;→&#x60;to&#x60; over &#x60;[startAt, startAt+durationMs]&#x60;, clamped outside that window, evaluated against the wall-clock at eval time. Overrides the entry&#39;s static &#x60;rolloutPct&#x60; while present. */
public struct ListGatesResponseDataInnerStackInnerOneOfRamp: Codable, JSONEncodable {

    public static let fromRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let toRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let startAtRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    public static let durationMsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    /** Start of the ramp in basis points (0–10000). */
    public var from: Int
    /** End of the ramp in basis points (0–10000). */
    public var to: Int
    /** Ramp start, epoch milliseconds (UTC). */
    public var startAt: Int
    /** Ramp length in milliseconds. */
    public var durationMs: Int

    public init(from: Int, to: Int, startAt: Int, durationMs: Int) {
        self.from = from
        self.to = to
        self.startAt = startAt
        self.durationMs = durationMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case to
        case startAt
        case durationMs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(startAt, forKey: .startAt)
        try container.encode(durationMs, forKey: .durationMs)
    }
}

