//
// ListConfigActivityResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListConfigActivityResponseInner: Codable, JSONEncodable {

    public enum ActorType: String, Codable, CaseIterable {
        case user = "user"
        case cli = "cli"
        case system = "system"
    }
    public var id: String
    /** Audit action (e.g. `config.create`, `config.publish`). */
    public var action: String
    public var actorEmail: String
    public var actorType: ActorType
    public var payload: AnyCodable?
    /** ISO-8601 timestamp. */
    public var createdAt: String

    public init(id: String, action: String, actorEmail: String, actorType: ActorType, payload: AnyCodable?, createdAt: String) {
        self.id = id
        self.action = action
        self.actorEmail = actorEmail
        self.actorType = actorType
        self.payload = payload
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case action
        case actorEmail
        case actorType
        case payload
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(action, forKey: .action)
        try container.encode(actorEmail, forKey: .actorEmail)
        try container.encode(actorType, forKey: .actorType)
        try container.encode(payload, forKey: .payload)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ListConfigActivityResponseInner: Identifiable {}
