//
// ListKeysResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One page of API keys plus a keyset &#x60;next_cursor&#x60; (ordered &#x60;created_at desc, id desc&#x60;). */
public struct ListKeysResponse: Codable, JSONEncodable {

    public var data: [KeyRecord]
    /** Opaque cursor for the next page, or `null` on the last page. Pass it back as the `cursor` query parameter. */
    public var nextCursor: String?

    public init(data: [KeyRecord], nextCursor: String?) {
        self.data = data
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case nextCursor = "next_cursor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}

