//
// ListConfigsResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListConfigsResponseDataInner: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    /** Stable opaque config id (`cfg_…`). */
    public var id: String
    /** Stable config key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Used by SDKs as `Shipeasy.getConfig('<name>')`. Immutable after create. */
    public var name: String
    public var description: String?
    /** JSON Schema (draft 2020-12) describing the shape of the config value. Top-level `type` must be `'object'`; every published value is validated against this schema. */
    public var schema: [String: AnyCodable]
    /** ISO-8601 timestamp of last mutation. */
    public var updatedAt: String
    /** Per-env latest published version metadata. */
    public var envs: [String: ListConfigsResponseDataInnerEnvsValue]
    /** Per-env active drafts (if any). */
    public var drafts: [String: ListConfigsResponseDataInnerDraftsValue]
    /** Per-env latest published values (only returned by `GET /{id}`, not list). */
    public var values: [String: AnyCodable]?
    /** Per-env draft values (only returned by `GET /{id}`). */
    public var draftValues: [String: AnyCodable]?

    public init(id: String, name: String, description: String?, schema: [String: AnyCodable], updatedAt: String, envs: [String: ListConfigsResponseDataInnerEnvsValue], drafts: [String: ListConfigsResponseDataInnerDraftsValue], values: [String: AnyCodable]? = nil, draftValues: [String: AnyCodable]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.schema = schema
        self.updatedAt = updatedAt
        self.envs = envs
        self.drafts = drafts
        self.values = values
        self.draftValues = draftValues
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case schema
        case updatedAt
        case envs
        case drafts
        case values
        case draftValues
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(schema, forKey: .schema)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(envs, forKey: .envs)
        try container.encode(drafts, forKey: .drafts)
        try container.encodeIfPresent(values, forKey: .values)
        try container.encodeIfPresent(draftValues, forKey: .draftValues)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ListConfigsResponseDataInner: Identifiable {}
