//
// ListEventsResponseInnerPropertiesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One typed property declared on a catalogued event. */
public struct ListEventsResponseInnerPropertiesInner: Codable, JSONEncodable {

    public enum ModelType: String, Codable, CaseIterable {
        case string = "string"
        case number = "number"
        case boolean = "boolean"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    /** Property key, e.g. `amount` or `plan`. */
    public var name: String
    /** Value type of the property as recorded on the event. */
    public var type: ModelType
    /** Whether the property must be present on every emitted event. */
    public var _required: Bool? = false
    /** Human-readable description of the property. */
    public var description: String? = ""

    public init(name: String, type: ModelType, _required: Bool? = false, description: String? = "") {
        self.name = name
        self.type = type
        self._required = _required
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case _required = "required"
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

