//
// ListUniversesResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListUniversesResponseDataInner: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: "/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/")
    public static let holdoutRangeRule = ArrayRule(minItems: 2, maxItems: 2, uniqueItems: false)
    /** Stable opaque universe id. */
    public var id: String
    /** Stable universe key. Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create. */
    public var name: String
    /** Unit of randomisation. Snake-case in request (`unit_type`), camelCase in response. */
    public var unitType: String
    /** Reserved holdout bucket range, or `null` if none. */
    public var holdoutRange: [Double]?
    /** ISO-8601 timestamp of creation. */
    public var createdAt: String

    public init(id: String, name: String, unitType: String, holdoutRange: [Double]?, createdAt: String) {
        self.id = id
        self.name = name
        self.unitType = unitType
        self.holdoutRange = holdoutRange
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case unitType
        case holdoutRange
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(unitType, forKey: .unitType)
        try container.encode(holdoutRange, forKey: .holdoutRange)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


