//
// ListKillswitchesResponseDataInnerEnvsValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListKillswitchesResponseDataInnerEnvsValue: Codable, JSONEncodable {

    public static let versionRule = NumericRule<Int>(minimum: -9007199254740991, exclusiveMinimum: false, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    /** Flat boolean published for this env. */
    public var value: Bool
    public var switches: [String: Bool]?
    /** Monotonically increasing version per env. */
    public var version: Int
    /** ISO-8601 publish timestamp for this version. */
    public var publishedAt: String
    /** Email/id of the actor who published this version. */
    public var publishedBy: String?

    public init(value: Bool, switches: [String: Bool]? = nil, version: Int, publishedAt: String, publishedBy: String? = nil) {
        self.value = value
        self.switches = switches
        self.version = version
        self.publishedAt = publishedAt
        self.publishedBy = publishedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case switches
        case version
        case publishedAt
        case publishedBy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(switches, forKey: .switches)
        try container.encode(version, forKey: .version)
        try container.encode(publishedAt, forKey: .publishedAt)
        try container.encodeIfPresent(publishedBy, forKey: .publishedBy)
    }
}

