//
// ListGatesResponseDataInnerEnabled.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Master switch. Returned as &#x60;1&#x60;/&#x60;0&#x60; from D1; treat truthy as enabled. */
public struct ListGatesResponseDataInnerEnabled: Codable, JSONEncodable {


    public enum CodingKeys: CodingKey, CaseIterable {
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
    }
}

