//
// ListI18nKeysResponseKeysInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One i18n key row. */
public struct ListI18nKeysResponseKeysInner: Codable, JSONEncodable {

    /** Stable opaque key id. */
    public var id: String
    /** Dotted key path, e.g. `home.cta`. */
    public var key: String
    /** Current translated value for the key. */
    public var value: String
    /** Optional human note stored with the key. */
    public var description: String?
    /** `{{var}}` placeholder names in the value, or `null` when there are none. */
    public var variables: [String]?
    /** Owning profile id. */
    public var profileId: String?
    /** Owning chunk (authoring grouping) id. */
    public var chunkId: String?
    /** ISO-8601 timestamp of the last edit. */
    public var updatedAt: String?
    /** Actor email that last edited the key. */
    public var updatedBy: String?

    public init(id: String, key: String, value: String, description: String? = nil, variables: [String]? = nil, profileId: String? = nil, chunkId: String? = nil, updatedAt: String? = nil, updatedBy: String? = nil) {
        self.id = id
        self.key = key
        self.value = value
        self.description = description
        self.variables = variables
        self.profileId = profileId
        self.chunkId = chunkId
        self.updatedAt = updatedAt
        self.updatedBy = updatedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case key
        case value
        case description
        case variables
        case profileId
        case chunkId
        case updatedAt
        case updatedBy
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(variables, forKey: .variables)
        try container.encodeIfPresent(profileId, forKey: .profileId)
        try container.encodeIfPresent(chunkId, forKey: .chunkId)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(updatedBy, forKey: .updatedBy)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        key = try container.decode(String.self, forKey: .key)
        value = try container.decode(String.self, forKey: .value)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        variables = try container.decodeIfPresent([String].self, forKey: .variables)
        profileId = try container.decodeIfPresent(String.self, forKey: .profileId)
        chunkId = try container.decodeIfPresent(String.self, forKey: .chunkId)
        updatedAt = try container.decodeIfPresent(String.self, forKey: .updatedAt)
        updatedBy = try container.decodeIfPresent(String.self, forKey: .updatedBy)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("key")
        nonAdditionalPropertyKeys.insert("value")
        nonAdditionalPropertyKeys.insert("description")
        nonAdditionalPropertyKeys.insert("variables")
        nonAdditionalPropertyKeys.insert("profileId")
        nonAdditionalPropertyKeys.insert("chunkId")
        nonAdditionalPropertyKeys.insert("updatedAt")
        nonAdditionalPropertyKeys.insert("updatedBy")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


