//
// ListConfigsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListConfigsResponse: Codable, JSONEncodable {

    public var data: [ListConfigsResponseDataInner]
    public var nextCursor: String?

    public init(data: [ListConfigsResponseDataInner], nextCursor: String?) {
        self.data = data
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case nextCursor = "next_cursor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}

