//
// ListSlackChannelsResponseChannelsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One Slack channel the project can post to. */
public struct ListSlackChannelsResponseChannelsInner: Codable, JSONEncodable {

    /** Slack channel id. */
    public var id: String
    /** Slack channel name (without the leading `#`). */
    public var name: String
    /** Whether the channel is private. */
    public var isPrivate: Bool?

    public init(id: String, name: String, isPrivate: Bool? = nil) {
        self.id = id
        self.name = name
        self.isPrivate = isPrivate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case isPrivate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(isPrivate, forKey: .isPrivate)
    }
}


