//
// MeasurePlanStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One piece of code instrumentation a measurement plan still needs. */
public struct MeasurePlanStep: Codable, JSONEncodable {

    /** The event name the instrumentation should emit, when known. */
    public var event: String?
    /** A new user attribute the project must start sending on its identify/evaluate context (when a gate's targeting needs a field that doesn't exist yet). */
    public var attribute: String?
    /** Short human-readable name for the moment being instrumented. */
    public var label: String
    /** What to track and why, described conceptually — which user moment/action to capture and what it enables. Deliberately NOT a file path (the assistant has no repo access and can't name real files); you locate the call site yourself. */
    public var description: String?
    /** Event properties the downstream metric needs attached (e.g. `method`, `plan`). */
    public var properties: [String]?

    public init(event: String? = nil, attribute: String? = nil, label: String, description: String? = nil, properties: [String]? = nil) {
        self.event = event
        self.attribute = attribute
        self.label = label
        self.description = description
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
        case attribute
        case label
        case description
        case properties
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(attribute, forKey: .attribute)
        try container.encode(label, forKey: .label)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(properties, forKey: .properties)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        event = try container.decodeIfPresent(String.self, forKey: .event)
        attribute = try container.decodeIfPresent(String.self, forKey: .attribute)
        label = try container.decode(String.self, forKey: .label)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        properties = try container.decodeIfPresent([String].self, forKey: .properties)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("event")
        nonAdditionalPropertyKeys.insert("attribute")
        nonAdditionalPropertyKeys.insert("label")
        nonAdditionalPropertyKeys.insert("description")
        nonAdditionalPropertyKeys.insert("properties")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

