//
// MetricDirection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Desired direction of movement. &#x60;higher_better&#x60; (default), &#x60;lower_better&#x60;, or &#x60;neutral&#x60; (guardrail). */
public enum MetricDirection: String, Codable, CaseIterable {
    case higherBetter = "higher_better"
    case lowerBetter = "lower_better"
    case neutral = "neutral"
}
