//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Uniform error envelope returned by every admin endpoint on a non-2xx status. &#x60;error&#x60; is the human-readable message; &#x60;code&#x60; is the stable machine code (present whenever the failure maps to a catalogued &#x60;ErrorCode&#x60;); &#x60;detail&#x60; carries extra context (validation paths, conflicting field); &#x60;instructions&#x60; is optional actionable guidance for resolving the error. */
public struct ModelError: Codable, JSONEncodable {

    /** Human-readable error message. */
    public var error: String
    public var code: ErrorCode?
    /** Extra context (validation details, conflicting field, referenced row). */
    public var detail: String?
    /** Actionable guidance for resolving this error — what to check or change next. */
    public var instructions: String?

    public init(error: String, code: ErrorCode? = nil, detail: String? = nil, instructions: String? = nil) {
        self.error = error
        self.code = code
        self.detail = detail
        self.instructions = instructions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case code
        case detail
        case instructions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(instructions, forKey: .instructions)
    }
}

