//
// OpsBrowserContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Auto-collected browser environment for a &#x60;bug&#x60;/&#x60;feature_request&#x60;, captured at file time. */
public struct OpsBrowserContext: Codable, JSONEncodable {

    /** URL of the page the report was filed from, or `null`. */
    public var pageUrl: String?
    /** Reporter's user-agent string, or `null`. */
    public var userAgent: String?
    /** Reporter's viewport (e.g. `1280x720`), or `null`. */
    public var viewport: String?

    public init(pageUrl: String? = nil, userAgent: String? = nil, viewport: String? = nil) {
        self.pageUrl = pageUrl
        self.userAgent = userAgent
        self.viewport = viewport
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pageUrl
        case userAgent
        case viewport
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pageUrl, forKey: .pageUrl)
        try container.encodeIfPresent(userAgent, forKey: .userAgent)
        try container.encodeIfPresent(viewport, forKey: .viewport)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        pageUrl = try container.decodeIfPresent(String.self, forKey: .pageUrl)
        userAgent = try container.decodeIfPresent(String.self, forKey: .userAgent)
        viewport = try container.decodeIfPresent(String.self, forKey: .viewport)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("pageUrl")
        nonAdditionalPropertyKeys.insert("userAgent")
        nonAdditionalPropertyKeys.insert("viewport")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

