//
// OpsCommentAuthorType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Who wrote a comment. &#x60;user&#x60; is a teammate (their email is in &#x60;authorEmail&#x60;); &#x60;system&#x60; is Jarvis — the AI agent — which authors comments when an ops-notify escalation lands on the item and when it is &#x60;@shipeasy&#x60;-mentioned in a thread. */
public enum OpsCommentAuthorType: String, Codable, CaseIterable {
    case user = "user"
    case system = "system"
}
