//
// OpsComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A single comment on a queue item. */
public struct OpsComment: Codable, JSONEncodable {

    /** Comment id. */
    public var id: String
    /** The queue item this comment hangs off. */
    public var feedbackId: String
    /** The top-level comment this is a reply to, or `null` for a top-level comment. */
    public var parentId: String?
    public var authorType: OpsCommentAuthorType
    /** The teammate who wrote it, or `null` for a `system` (Jarvis) comment. */
    public var authorEmail: String?
    /** Comment body as markdown (may contain sanitised inline image/video embeds). */
    public var body: String
    /** ISO-8601 creation timestamp. */
    public var createdAt: String
    /** ISO-8601 last-edit timestamp. */
    public var updatedAt: String

    public init(id: String, feedbackId: String, parentId: String?, authorType: OpsCommentAuthorType, authorEmail: String?, body: String, createdAt: String, updatedAt: String) {
        self.id = id
        self.feedbackId = feedbackId
        self.parentId = parentId
        self.authorType = authorType
        self.authorEmail = authorEmail
        self.body = body
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case feedbackId
        case parentId
        case authorType
        case authorEmail
        case body
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(feedbackId, forKey: .feedbackId)
        try container.encode(parentId, forKey: .parentId)
        try container.encode(authorType, forKey: .authorType)
        try container.encode(authorEmail, forKey: .authorEmail)
        try container.encode(body, forKey: .body)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


