//
// OpsItemAttachment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A file uploaded with a bug/feature report. */
public struct OpsItemAttachment: Codable, JSONEncodable {

    /** Attachment id. */
    public var id: String
    /** `screenshot` | `video` | `log`. */
    public var kind: String
    /** Sanitized original filename. */
    public var filename: String
    /** MIME type, e.g. `image/png`. */
    public var mimeType: String
    /** Upload size in bytes. */
    public var sizeBytes: Double
    /** Admin-API path to download the file (`GET` with the admin/ops key — screenshots render inline; recordings can't be watched). */
    public var fetchUrl: String

    public init(id: String, kind: String, filename: String, mimeType: String, sizeBytes: Double, fetchUrl: String) {
        self.id = id
        self.kind = kind
        self.filename = filename
        self.mimeType = mimeType
        self.sizeBytes = sizeBytes
        self.fetchUrl = fetchUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case kind
        case filename
        case mimeType
        case sizeBytes
        case fetchUrl
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(kind, forKey: .kind)
        try container.encode(filename, forKey: .filename)
        try container.encode(mimeType, forKey: .mimeType)
        try container.encode(sizeBytes, forKey: .sizeBytes)
        try container.encode(fetchUrl, forKey: .fetchUrl)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decode(String.self, forKey: .id)
        kind = try container.decode(String.self, forKey: .kind)
        filename = try container.decode(String.self, forKey: .filename)
        mimeType = try container.decode(String.self, forKey: .mimeType)
        sizeBytes = try container.decode(Double.self, forKey: .sizeBytes)
        fetchUrl = try container.decode(String.self, forKey: .fetchUrl)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("kind")
        nonAdditionalPropertyKeys.insert("filename")
        nonAdditionalPropertyKeys.insert("mimeType")
        nonAdditionalPropertyKeys.insert("sizeBytes")
        nonAdditionalPropertyKeys.insert("fetchUrl")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OpsItemAttachment: Identifiable {}
