//
// OpsItemStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Lifecycle status of a queue item. The working flow is &#x60;open&#x60; → &#x60;triaged&#x60; → &#x60;in_progress&#x60; → &#x60;ready_for_qa&#x60; → &#x60;resolved&#x60; (or &#x60;wont_fix&#x60;, terminal from any earlier stage). &#x60;ready_for_qa&#x60; is what a developer sets once a fix lands; &#x60;resolved&#x60; is the QA sign-off, normally flipped in the dashboard after verification — set it directly from code only when the fix has been verified end-to-end. Two human-gated holding states park an item OUT of the work queue until a human promotes it to &#x60;open&#x60; in the dashboard, so &#x60;GET /api/admin/ops&#x60; excludes them under &#x60;status&#x3D;all&#x60;/default and returns them only when requested as an exact &#x60;status&#x60;: &#x60;pending_approval&#x60; is the pre-open approval gate for untriaged inbound (e.g. connector requests filed from a customer&#39;s connectors panel) so it never gets auto-implemented — approving &#x3D; flipping the status to &#x60;open&#x60;; &#x60;triage&#x60; is the onboarding-help bucket — questions/errors submitted to the \&quot;Stuck in onboarding?\&quot; assistant are funnelled into the platform project as &#x60;triage&#x60; rows so the team can see where people get stuck and follow up, keeping onboarding chatter out of the work queue until a human moves real items to &#x60;open&#x60;. */
public enum OpsItemStatus: String, Codable, CaseIterable {
    case _open = "open"
    case pendingApproval = "pending_approval"
    case triage = "triage"
    case triaged = "triaged"
    case inProgress = "in_progress"
    case readyForQa = "ready_for_qa"
    case resolved = "resolved"
    case wontFix = "wont_fix"
}
