//
// OpsMeasurePlanContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An assistant-proposed measurement plan: what it already built, what it still needs, and the event instrumentation you implement. */
public struct OpsMeasurePlanContext: Codable, JSONEncodable {

    /** The customer's underlying intent in their own words — WHAT they want to learn or achieve and WHY, independent of the specific steps. The plan below is a best-effort proposal made without repo access; when the code reveals a better path, this goal is the target you optimize for, not literal step-adherence. */
    public var goal: String?
    /** Resources the assistant already created on approval (live now) — don't recreate them. */
    public var created: [MeasurePlanResource]
    /** Resources the assistant couldn't create yet (usually a metric whose backing event isn't emitted); create these after the instrumentation lands. */
    public var pending: [MeasurePlanResource]?
    /** The code instrumentation to implement before the metrics can collect data. */
    public var instrumentation: [MeasurePlanStep]

    public init(goal: String? = nil, created: [MeasurePlanResource], pending: [MeasurePlanResource]? = nil, instrumentation: [MeasurePlanStep]) {
        self.goal = goal
        self.created = created
        self.pending = pending
        self.instrumentation = instrumentation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case goal
        case created
        case pending
        case instrumentation
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(goal, forKey: .goal)
        try container.encode(created, forKey: .created)
        try container.encodeIfPresent(pending, forKey: .pending)
        try container.encode(instrumentation, forKey: .instrumentation)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        goal = try container.decodeIfPresent(String.self, forKey: .goal)
        created = try container.decode([MeasurePlanResource].self, forKey: .created)
        pending = try container.decodeIfPresent([MeasurePlanResource].self, forKey: .pending)
        instrumentation = try container.decode([MeasurePlanStep].self, forKey: .instrumentation)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("goal")
        nonAdditionalPropertyKeys.insert("created")
        nonAdditionalPropertyKeys.insert("pending")
        nonAdditionalPropertyKeys.insert("instrumentation")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

