//
// PublishI18nProfileResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of a profile-wide publish. */
public struct PublishI18nProfileResponse: Codable, JSONEncodable {

    public enum Ok: Bool, Codable, JSONEncodable, CaseIterable {
        case _true = true
    }
    public enum Purged: String, Codable, CaseIterable {
        case purged = "purged"
        case skipped = "skipped"
        case failed = "failed"
    }
    /** Always `true` on success. */
    public var ok: Ok
    /** Profile that was published. */
    public var profileId: String
    /** Audit chunk label, or `null` when none was given. */
    public var chunk: String?
    /** ISO-8601 timestamp of the publish. */
    public var publishedAt: String
    /** New KV snapshot version that was shipped. */
    public var version: String
    /** Number of keys in the published snapshot. */
    public var keyCount: Double
    /** Whether the snapshot's contents actually changed since the last publish. */
    public var changed: Bool
    /** CDN purge outcome: `purged` ok, `skipped` (no creds), or `failed` (edge still stale). */
    public var purged: Purged
    /** Whether a KV read-back confirmed the new version persisted. */
    public var kvVerified: Bool
    /** Human-readable caveat when the publish landed but is not fully live. */
    public var warning: String?

    public init(ok: Ok, profileId: String, chunk: String?, publishedAt: String, version: String, keyCount: Double, changed: Bool, purged: Purged, kvVerified: Bool, warning: String? = nil) {
        self.ok = ok
        self.profileId = profileId
        self.chunk = chunk
        self.publishedAt = publishedAt
        self.version = version
        self.keyCount = keyCount
        self.changed = changed
        self.purged = purged
        self.kvVerified = kvVerified
        self.warning = warning
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case profileId = "profile_id"
        case chunk
        case publishedAt = "published_at"
        case version
        case keyCount = "key_count"
        case changed
        case purged
        case kvVerified = "kv_verified"
        case warning
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(profileId, forKey: .profileId)
        try container.encode(chunk, forKey: .chunk)
        try container.encode(publishedAt, forKey: .publishedAt)
        try container.encode(version, forKey: .version)
        try container.encode(keyCount, forKey: .keyCount)
        try container.encode(changed, forKey: .changed)
        try container.encode(purged, forKey: .purged)
        try container.encode(kvVerified, forKey: .kvVerified)
        try container.encodeIfPresent(warning, forKey: .warning)
    }
}

