//
// PushI18nKeysResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of an insert-only key push. */
public struct PushI18nKeysResponse: Codable, JSONEncodable {

    /** Key names that were newly inserted. */
    public var added: [String]
    /** Key names that already existed and were left untouched. */
    public var skipped: [String]
    /** Number of keys inserted (== `added.length`). */
    public var pushedCount: Double
    /** Number of keys skipped (== `skipped.length`). */
    public var skippedCount: Double
    /** The chunk the keys were filed under. */
    public var chunk: String?

    public init(added: [String], skipped: [String], pushedCount: Double, skippedCount: Double, chunk: String? = nil) {
        self.added = added
        self.skipped = skipped
        self.pushedCount = pushedCount
        self.skippedCount = skippedCount
        self.chunk = chunk
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case added
        case skipped
        case pushedCount = "pushed_count"
        case skippedCount = "skipped_count"
        case chunk
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(added, forKey: .added)
        try container.encode(skipped, forKey: .skipped)
        try container.encode(pushedCount, forKey: .pushedCount)
        try container.encode(skippedCount, forKey: .skippedCount)
        try container.encodeIfPresent(chunk, forKey: .chunk)
    }
}

