//
// QueryIrAgg.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Aggregation function applied to the source event. */
public enum QueryIrAgg: Codable, JSONEncodable {
    case typeQueryIrAggOneOf(QueryIrAggOneOf)
    case typeQueryIrAggOneOf1(QueryIrAggOneOf1)
    case typeQueryIrAggOneOf2(QueryIrAggOneOf2)
    case typeQueryIrAggOneOf3(QueryIrAggOneOf3)
    case typeQueryIrAggOneOf4(QueryIrAggOneOf4)
    case typeQueryIrAggOneOf5(QueryIrAggOneOf5)
    case typeQueryIrAggOneOf6(QueryIrAggOneOf6)
    case typeQueryIrAggOneOf7(QueryIrAggOneOf7)
    case typeQueryIrAggOneOf8(QueryIrAggOneOf8)
    case typeQueryIrAggOneOf9(QueryIrAggOneOf9)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeQueryIrAggOneOf(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf1(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf2(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf3(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf4(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf5(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf6(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf7(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf8(let value):
            try container.encode(value)
        case .typeQueryIrAggOneOf9(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(QueryIrAggOneOf.self) {
            self = .typeQueryIrAggOneOf(value)
        } else if let value = try? container.decode(QueryIrAggOneOf1.self) {
            self = .typeQueryIrAggOneOf1(value)
        } else if let value = try? container.decode(QueryIrAggOneOf2.self) {
            self = .typeQueryIrAggOneOf2(value)
        } else if let value = try? container.decode(QueryIrAggOneOf3.self) {
            self = .typeQueryIrAggOneOf3(value)
        } else if let value = try? container.decode(QueryIrAggOneOf4.self) {
            self = .typeQueryIrAggOneOf4(value)
        } else if let value = try? container.decode(QueryIrAggOneOf5.self) {
            self = .typeQueryIrAggOneOf5(value)
        } else if let value = try? container.decode(QueryIrAggOneOf6.self) {
            self = .typeQueryIrAggOneOf6(value)
        } else if let value = try? container.decode(QueryIrAggOneOf7.self) {
            self = .typeQueryIrAggOneOf7(value)
        } else if let value = try? container.decode(QueryIrAggOneOf8.self) {
            self = .typeQueryIrAggOneOf8(value)
        } else if let value = try? container.decode(QueryIrAggOneOf9.self) {
            self = .typeQueryIrAggOneOf9(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of QueryIrAgg"))
        }
    }
}

