//
// QueryIrAggOneOf9Numerator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Numerator or denominator arm of a &#x60;ratio&#x60; aggregation. */
public struct QueryIrAggOneOf9Numerator: Codable, JSONEncodable {

    public enum Agg: String, Codable, CaseIterable {
        case countUsers = "count_users"
        case countEvents = "count_events"
    }
    public static let metricRule = StringRule(minLength: 1, maxLength: 128, pattern: nil)
    public static let filtersRule = ArrayRule(minItems: nil, maxItems: 16, uniqueItems: false)
    /** Counting mode for this ratio arm. */
    public var agg: Agg
    /** Source event name for this ratio arm. */
    public var metric: String
    /** Optional label filters. */
    public var filters: [QueryIrAggOneOf9NumeratorFiltersInner]?

    public init(agg: Agg, metric: String, filters: [QueryIrAggOneOf9NumeratorFiltersInner]? = nil) {
        self.agg = agg
        self.metric = metric
        self.filters = filters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agg
        case metric
        case filters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(agg, forKey: .agg)
        try container.encode(metric, forKey: .metric)
        try container.encodeIfPresent(filters, forKey: .filters)
    }
}

