//
// QueryIrAggOneOf9.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueryIrAggOneOf9: Codable, JSONEncodable {

    public enum Kind: String, Codable, CaseIterable {
        case ratio = "ratio"
    }
    public var kind: Kind
    public var numerator: QueryIrAggOneOf9Numerator
    public var denominator: QueryIrAggOneOf9Numerator

    public init(kind: Kind, numerator: QueryIrAggOneOf9Numerator, denominator: QueryIrAggOneOf9Numerator) {
        self.kind = kind
        self.numerator = numerator
        self.denominator = denominator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case numerator
        case denominator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(numerator, forKey: .numerator)
        try container.encode(denominator, forKey: .denominator)
    }
}

