//
// QueryIr.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Typed query IR — the structured alternative to the &#x60;query&#x60; DSL string. Exactly one of &#x60;query&#x60; / &#x60;query_ir&#x60; is supplied per metric body. */
public struct QueryIr: Codable, JSONEncodable {

    public static let metricRule = StringRule(minLength: 1, maxLength: 128, pattern: nil)
    public static let valueLabelRule = StringRule(minLength: 1, maxLength: 128, pattern: nil)
    public static let filtersRule = ArrayRule(minItems: nil, maxItems: 16, uniqueItems: false)
    public var agg: QueryIrAgg
    /** Source event name (must equal `event_name`). */
    public var metric: String
    /** Numeric property summed/averaged for `sum`/`avg`/quantile aggregations. */
    public var valueLabel: String?
    /** Label filters on the event. */
    public var filters: [QueryIrAggOneOf9NumeratorFiltersInner]?
    public var groupBy: QueryIrGroupBy?

    public init(agg: QueryIrAgg, metric: String, valueLabel: String? = nil, filters: [QueryIrAggOneOf9NumeratorFiltersInner]? = nil, groupBy: QueryIrGroupBy? = nil) {
        self.agg = agg
        self.metric = metric
        self.valueLabel = valueLabel
        self.filters = filters
        self.groupBy = groupBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agg
        case metric
        case valueLabel
        case filters
        case groupBy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(agg, forKey: .agg)
        try container.encode(metric, forKey: .metric)
        try container.encodeIfPresent(valueLabel, forKey: .valueLabel)
        try container.encodeIfPresent(filters, forKey: .filters)
        try container.encodeIfPresent(groupBy, forKey: .groupBy)
    }
}

