//
// ReanalyzeExperimentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReanalyzeExperimentResponse: Codable, JSONEncodable {

    public enum Queued: Bool, Codable, JSONEncodable, CaseIterable {
        case _true = true
    }
    public var id: String
    public var queued: Queued

    public init(id: String, queued: Queued) {
        self.id = id
        self.queued = queued
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case queued
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(queued, forKey: .queued)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ReanalyzeExperimentResponse: Identifiable {}
