//
// RevokeKeyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Confirms the key is revoked. Idempotent — revoking an already-revoked key returns the same shape. */
public struct RevokeKeyResponse: Codable, JSONEncodable {

    /** Id of the key that was revoked. */
    public var id: String
    public var revoked: Bool

    public init(id: String, revoked: Bool) {
        self.id = id
        self.revoked = revoked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case revoked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(revoked, forKey: .revoked)
    }
}


