//
// SaveConfigDraftRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PUT /api/admin/configs/{id}/drafts&#x60;. Stages a value for a single env without publishing. */
public struct SaveConfigDraftRequest: Codable, JSONEncodable {

    public var env: Env
    public var value: AnyCodable?

    public init(env: Env, value: AnyCodable?) {
        self.env = env
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case env
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(env, forKey: .env)
        try container.encode(value, forKey: .value)
    }
}

