//
// SaveConfigDraftResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SaveConfigDraftResponse: Codable, JSONEncodable {

    public static let baseVersionRule = NumericRule<Int>(minimum: -9007199254740991, exclusiveMinimum: false, maximum: 9007199254740991, exclusiveMaximum: false, multipleOf: nil)
    public var id: String
    public var env: Env
    /** Published version the draft is based on. */
    public var baseVersion: Int
    public var updatedAt: String

    public init(id: String, env: Env, baseVersion: Int, updatedAt: String) {
        self.id = id
        self.env = env
        self.baseVersion = baseVersion
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case env
        case baseVersion
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(env, forKey: .env)
        try container.encode(baseVersion, forKey: .baseVersion)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


