//
// SetExperimentStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetExperimentStatusResponse: Codable, JSONEncodable {

    public enum Status: String, Codable, CaseIterable {
        case draft = "draft"
        case running = "running"
        case stopped = "stopped"
        case archived = "archived"
    }
    public var id: String
    public var status: Status

    public init(id: String, status: Status) {
        self.id = id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
    }
}


