//
// SetI18nLabelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of a one-shot set-and-publish. */
public struct SetI18nLabelResponse: Codable, JSONEncodable {

    public enum Ok: Bool, Codable, JSONEncodable, CaseIterable {
        case _true = true
    }
    public enum Purged: String, Codable, CaseIterable {
        case purged = "purged"
        case skipped = "skipped"
        case failed = "failed"
    }
    /** Always `true` on success. */
    public var ok: Ok
    /** Name of the profile that was published. */
    public var profile: String
    /** Id of the profile that was published. */
    public var profileId: String
    /** The key that was set. */
    public var key: String
    /** The value that was stored. */
    public var value: String
    /** ISO-8601 timestamp of the publish. */
    public var publishedAt: String
    /** New KV snapshot version that was shipped. */
    public var version: String
    /** Number of keys in the published snapshot. */
    public var keyCount: Double
    /** Whether the snapshot's contents actually changed since the last publish. */
    public var changed: Bool
    /** CDN purge outcome: `purged` ok, `skipped` (no creds), or `failed` (edge still stale). */
    public var purged: Purged
    /** Whether a KV read-back confirmed the new version persisted. */
    public var kvVerified: Bool
    /** Human-readable caveat when the publish landed but is not fully live. */
    public var warning: String?

    public init(ok: Ok, profile: String, profileId: String, key: String, value: String, publishedAt: String, version: String, keyCount: Double, changed: Bool, purged: Purged, kvVerified: Bool, warning: String? = nil) {
        self.ok = ok
        self.profile = profile
        self.profileId = profileId
        self.key = key
        self.value = value
        self.publishedAt = publishedAt
        self.version = version
        self.keyCount = keyCount
        self.changed = changed
        self.purged = purged
        self.kvVerified = kvVerified
        self.warning = warning
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ok
        case profile
        case profileId = "profile_id"
        case key
        case value
        case publishedAt = "published_at"
        case version
        case keyCount = "key_count"
        case changed
        case purged
        case kvVerified = "kv_verified"
        case warning
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ok, forKey: .ok)
        try container.encode(profile, forKey: .profile)
        try container.encode(profileId, forKey: .profileId)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
        try container.encode(publishedAt, forKey: .publishedAt)
        try container.encode(version, forKey: .version)
        try container.encode(keyCount, forKey: .keyCount)
        try container.encode(changed, forKey: .changed)
        try container.encode(purged, forKey: .purged)
        try container.encode(kvVerified, forKey: .kvVerified)
        try container.encodeIfPresent(warning, forKey: .warning)
    }
}

