//
// SetI18nLabelRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;POST /api/admin/i18n/set&#x60;. Upserts one key&#39;s value and publishes the profile live. */
public struct SetI18nLabelRequest: Codable, JSONEncodable {

    public static let keyRule = StringRule(minLength: 1, maxLength: 256, pattern: nil)
    public static let profileRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    /** Dotted key path to set, e.g. `home.cta`. */
    public var key: String
    /** New value for the key. Inserted when the key is new, overwritten when it exists. */
    public var value: String
    /** Profile name to target, e.g. `en:prod`. Omit to target the project's default-marked profile. */
    public var profile: String?
    /** Optional human note to store with the key. */
    public var description: String?

    public init(key: String, value: String, profile: String? = nil, description: String? = nil) {
        self.key = key
        self.value = value
        self.profile = profile
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case value
        case profile
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

