//
// SetKillswitchSwitchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetKillswitchSwitchResponse: Codable, JSONEncodable {

    public static let switchKeyRule = StringRule(minLength: nil, maxLength: 64, pattern: "/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?$/")
    public var id: String
    public var env: Env
    /** Single-segment switch key (lowercase letters, digits, `_`/`-`; no dots). Used as the nested switch entry inside a killswitch's `switches` map. */
    public var switchKey: String
    public var value: Bool

    public init(id: String, env: Env, switchKey: String, value: Bool) {
        self.id = id
        self.env = env
        self.switchKey = switchKey
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case env
        case switchKey
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(env, forKey: .env)
        try container.encode(switchKey, forKey: .switchKey)
        try container.encode(value, forKey: .value)
    }
}


