//
// UnsetKillswitchSwitchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;DELETE /api/admin/killswitches/{id}/switch&#x60;. Removes one switch entry from one env. */
public struct UnsetKillswitchSwitchRequest: Codable, JSONEncodable {

    public static let switchKeyRule = StringRule(minLength: nil, maxLength: 64, pattern: "/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?$/")
    public var env: Env
    /** Switch key to remove. */
    public var switchKey: String

    public init(env: Env, switchKey: String) {
        self.env = env
        self.switchKey = switchKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case env
        case switchKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(env, forKey: .env)
        try container.encode(switchKey, forKey: .switchKey)
    }
}

