//
// UpdateGateTemplateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/gate-templates/{id}&#x60;. Partial — only supplied fields change. &#x60;rules&#x60; replaces wholesale. Built-in templates are read-only (409). */
public struct UpdateGateTemplateRequest: Codable, JSONEncodable {

    public enum Category: String, Codable, CaseIterable {
        case condition = "condition"
        case rollout = "rollout"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 140, pattern: nil)
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 2000, pattern: nil)
    public static let rulesRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var name: String?
    public var description: String?
    public var category: Category?
    public var iconKey: String?
    public var auto: Bool?
    public var rules: [GateTemplateRule]?

    public init(name: String? = nil, description: String? = nil, category: Category? = nil, iconKey: String? = nil, auto: Bool? = nil, rules: [GateTemplateRule]? = nil) {
        self.name = name
        self.description = description
        self.category = category
        self.iconKey = iconKey
        self.auto = auto
        self.rules = rules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case category
        case iconKey = "icon_key"
        case auto
        case rules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(iconKey, forKey: .iconKey)
        try container.encodeIfPresent(auto, forKey: .auto)
        try container.encodeIfPresent(rules, forKey: .rules)
    }
}

