//
// UpdateAlertRuleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateAlertRuleRequest: Codable, JSONEncodable {

    public enum Comparator: String, Codable, CaseIterable {
        case gt = "gt"
        case gte = "gte"
        case lt = "lt"
        case lte = "lte"
    }
    public enum Severity: String, Codable, CaseIterable {
        case danger = "danger"
        case warn = "warn"
        case info = "info"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let windowHoursRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 720, exclusiveMaximum: false, multipleOf: nil)
    public var name: String?
    public var comparator: Comparator?
    public var threshold: Double?
    public var windowHours: Int?
    public var severity: Severity?
    public var enabled: Bool?
    public var notify: NotificationTarget?

    public init(name: String? = nil, comparator: Comparator? = nil, threshold: Double? = nil, windowHours: Int? = nil, severity: Severity? = nil, enabled: Bool? = nil, notify: NotificationTarget? = nil) {
        self.name = name
        self.comparator = comparator
        self.threshold = threshold
        self.windowHours = windowHours
        self.severity = severity
        self.enabled = enabled
        self.notify = notify
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case comparator
        case threshold
        case windowHours
        case severity
        case enabled
        case notify
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(comparator, forKey: .comparator)
        try container.encodeIfPresent(threshold, forKey: .threshold)
        try container.encodeIfPresent(windowHours, forKey: .windowHours)
        try container.encodeIfPresent(severity, forKey: .severity)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(notify, forKey: .notify)
    }
}

