//
// UpdateMetricRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/metrics/{id}&#x60;. Every field is optional (&#x60;name&#x60; is immutable); provide at most one of &#x60;query&#x60; / &#x60;query_ir&#x60; — modelled as a &#x60;oneOf&#x60; of three disjoint strict variants (query-only, query_ir-only, or neither), so supplying both is rejected. */
public enum UpdateMetricRequest: Codable, JSONEncodable {
    case typeUpdateMetricFields(UpdateMetricFields)
    case typeUpdateMetricWithQuery(UpdateMetricWithQuery)
    case typeUpdateMetricWithQueryIr(UpdateMetricWithQueryIr)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateMetricFields(let value):
            try container.encode(value)
        case .typeUpdateMetricWithQuery(let value):
            try container.encode(value)
        case .typeUpdateMetricWithQueryIr(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(UpdateMetricFields.self) {
            self = .typeUpdateMetricFields(value)
        } else if let value = try? container.decode(UpdateMetricWithQuery.self) {
            self = .typeUpdateMetricWithQuery(value)
        } else if let value = try? container.decode(UpdateMetricWithQueryIr.self) {
            self = .typeUpdateMetricWithQueryIr(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of UpdateMetricRequest"))
        }
    }
}

