//
// UpdateJulesTriggerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Per-provider PATCH body for editing an existing &#x60;jules_trigger&#x60; connector. &#x60;config&#x60; replaces the stored config wholesale; &#x60;name&#x60; and either credential are optional. */
public struct UpdateJulesTriggerRequest: Codable, JSONEncodable {

    public enum Provider: String, Codable, CaseIterable {
        case julesTrigger = "jules_trigger"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 80, pattern: nil)
    public static let apiKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let opsKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Discriminator. Google Jules trigger. */
    public var provider: Provider
    /** New connector label. Optional — omit to leave it unchanged. */
    public var name: String?
    public var config: JulesTriggerConfig
    /** New Jules launch key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `opsKey`. Encrypted; never returned. */
    public var apiKey: String?
    /** New restricted Shipeasy ops key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `apiKey`. Encrypted; never returned. */
    public var opsKey: String?

    public init(provider: Provider, name: String? = nil, config: JulesTriggerConfig, apiKey: String? = nil, opsKey: String? = nil) {
        self.provider = provider
        self.name = name
        self.config = config
        self.apiKey = apiKey
        self.opsKey = opsKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case name
        case config
        case apiKey
        case opsKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(config, forKey: .config)
        try container.encodeIfPresent(apiKey, forKey: .apiKey)
        try container.encodeIfPresent(opsKey, forKey: .opsKey)
    }
}

