//
// UpdateMetricWithQueryIr.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update-metric variant that replaces the query with a typed &#x60;query_ir&#x60;. */
public struct UpdateMetricWithQueryIr: Codable, JSONEncodable {

    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    public static let eventNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let winsorizePctRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 99, exclusiveMaximum: false, multipleOf: nil)
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** Source event the query reads from. */
    public var eventName: String?
    public var queryIr: QueryIr
    /** Winsorise percentile (1–99) to clamp outliers. Defaults to 99. */
    public var winsorizePct: Int? = 99
    /** Default minimum effect of interest (relative, 0–1) — the smallest change in this metric worth acting on, used as the power-planning baseline. Intrinsic to the metric; an experiment overrides it per-attachment with `min_effect_of_interest` when a specific decision has a different cost/risk bar. `null` to omit. */
    public var defaultMinEffectOfInterest: Double?
    public var direction: MetricDirection?

    public init(folder: String? = nil, eventName: String? = nil, queryIr: QueryIr, winsorizePct: Int? = 99, defaultMinEffectOfInterest: Double? = nil, direction: MetricDirection? = nil) {
        self.folder = folder
        self.eventName = eventName
        self.queryIr = queryIr
        self.winsorizePct = winsorizePct
        self.defaultMinEffectOfInterest = defaultMinEffectOfInterest
        self.direction = direction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folder
        case eventName = "event_name"
        case queryIr = "query_ir"
        case winsorizePct = "winsorize_pct"
        case defaultMinEffectOfInterest = "default_min_effect_of_interest"
        case direction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(eventName, forKey: .eventName)
        try container.encode(queryIr, forKey: .queryIr)
        try container.encodeIfPresent(winsorizePct, forKey: .winsorizePct)
        try container.encodeIfPresent(defaultMinEffectOfInterest, forKey: .defaultMinEffectOfInterest)
        try container.encodeIfPresent(direction, forKey: .direction)
    }
}

