//
// UpdateUniverseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/universes/{id}&#x60;. Only &#x60;holdout_range&#x60; is mutable — name and unit_type are immutable after create. */
public struct UpdateUniverseRequest: Codable, JSONEncodable {

    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    public static let holdoutRangeRule = ArrayRule(minItems: 2, maxItems: 2, uniqueItems: false)
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** Inclusive `[lo, hi]` bucket range (0–9999) reserved as the **holdout** — callers hashed into this slice are excluded from every experiment in the universe. `null` disables the holdout. Pro plan or higher required. */
    public var holdoutRange: [Int]?

    public init(folder: String? = nil, holdoutRange: [Int]? = nil) {
        self.folder = folder
        self.holdoutRange = holdoutRange
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folder
        case holdoutRange = "holdout_range"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(holdoutRange, forKey: .holdoutRange)
    }
}

