//
// UpdateOpsItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/ops/{handle}&#x60;. The body is type-less — the server validates it against the stored item&#39;s type: a &#x60;bug&#x60; accepts the bug content fields, a &#x60;feature_request&#x60; the feature fields, and &#x60;error&#x60;/&#x60;alert&#x60;/&#x60;measure_plan&#x60; only &#x60;status&#x60;/&#x60;priority&#x60;/&#x60;notify&#x60;. Pass at least one field. */
public struct UpdateOpsItemRequest: Codable, JSONEncodable {

    public static let titleRule = StringRule(minLength: 1, maxLength: 200, pattern: "/^\\S(.*\\S)?$/")
    public static let stepsToReproduceRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    public static let actualResultRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    public static let expectedResultRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    public static let githubPrNumberRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    public static let useCaseRule = StringRule(minLength: nil, maxLength: 8000, pattern: nil)
    /** New feature-request title (no leading/trailing whitespace). */
    public var title: String?
    /** Updated reproduction steps. */
    public var stepsToReproduce: String?
    /** Updated actual result. */
    public var actualResult: String?
    /** Updated expected result. */
    public var expectedResult: String?
    public var status: OpsItemStatus?
    public var priority: OpsItemPriorityOrNull?
    /** Link (or, when `null`, unlink) a GitHub pull request to this request. */
    public var githubPrNumber: Int?
    public var notify: OpsItemNotifyOrNull?
    /** Updated description. */
    public var description: String?
    /** Updated use case. */
    public var useCase: String?

    public init(title: String? = nil, stepsToReproduce: String? = nil, actualResult: String? = nil, expectedResult: String? = nil, status: OpsItemStatus? = nil, priority: OpsItemPriorityOrNull? = nil, githubPrNumber: Int? = nil, notify: OpsItemNotifyOrNull? = nil, description: String? = nil, useCase: String? = nil) {
        self.title = title
        self.stepsToReproduce = stepsToReproduce
        self.actualResult = actualResult
        self.expectedResult = expectedResult
        self.status = status
        self.priority = priority
        self.githubPrNumber = githubPrNumber
        self.notify = notify
        self.description = description
        self.useCase = useCase
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case stepsToReproduce
        case actualResult
        case expectedResult
        case status
        case priority
        case githubPrNumber
        case notify
        case description
        case useCase
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(stepsToReproduce, forKey: .stepsToReproduce)
        try container.encodeIfPresent(actualResult, forKey: .actualResult)
        try container.encodeIfPresent(expectedResult, forKey: .expectedResult)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(githubPrNumber, forKey: .githubPrNumber)
        try container.encodeIfPresent(notify, forKey: .notify)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(useCase, forKey: .useCase)
    }
}

