//
// UpdateGateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/gates/{id}&#x60;. Partial — only supplied fields change. Array fields (&#x60;rules&#x60;, &#x60;stack&#x60;) replace, not merge. */
public struct UpdateGateRequest: Codable, JSONEncodable {

    public static let rolloutPctRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let rolloutPercentRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let titleRule = StringRule(minLength: nil, maxLength: 140, pattern: nil)
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 2000, pattern: nil)
    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    public static let groupRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public static let ownerEmailRule = StringRule(minLength: nil, maxLength: 190, pattern: nil)
    /** New rollout in **basis points** (0–10000 = 0%–100%) — `100` here means **1%**. Use `rollout_percent` (0–100) below for percent. Omit both to leave unchanged. */
    public var rolloutPct: Int?
    /** New rollout as a **percentage** (0–100). Friendlier alias for `rollout_pct`; converted internally. Wins over `rollout_pct` if both are supplied. Omit both to leave unchanged. */
    public var rolloutPercent: Double?
    /** Replaces the rule list wholesale. To add a value to an `in` rule, send the full new `rules` array with the augmented `value` (e.g. previous `['US','CA']` → `['US','CA','GB']`). */
    public var rules: [ListGatesResponseDataInnerRulesInner]?
    /** Master switch. `false` makes the gate evaluate to `false` for every caller regardless of `rollout_pct`, `rules`, or `stack` — use as kill switch. */
    public var enabled: Bool?
    /** Replaces the gatekeeper stack wholesale. Send `null` to revert to flat `rules` + `rollout_pct` evaluation. */
    public var stack: [ListGatesResponseDataInnerStackInner]?
    /** Human-readable title shown in the dashboard. Free-form, no key format constraint. */
    public var title: String?
    /** Long-form description / runbook. Markdown is rendered in the dashboard. */
    public var description: String?
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?
    /** Group label for dashboard organisation (e.g. team or product area). */
    public var group: String?
    /** Owner contact. Displayed verbatim; not used for auth. */
    public var ownerEmail: String?

    public init(rolloutPct: Int? = nil, rolloutPercent: Double? = nil, rules: [ListGatesResponseDataInnerRulesInner]? = nil, enabled: Bool? = nil, stack: [ListGatesResponseDataInnerStackInner]? = nil, title: String? = nil, description: String? = nil, folder: String? = nil, group: String? = nil, ownerEmail: String? = nil) {
        self.rolloutPct = rolloutPct
        self.rolloutPercent = rolloutPercent
        self.rules = rules
        self.enabled = enabled
        self.stack = stack
        self.title = title
        self.description = description
        self.folder = folder
        self.group = group
        self.ownerEmail = ownerEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rolloutPct = "rollout_pct"
        case rolloutPercent = "rollout_percent"
        case rules
        case enabled
        case stack
        case title
        case description
        case folder
        case group
        case ownerEmail = "owner_email"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rolloutPct, forKey: .rolloutPct)
        try container.encodeIfPresent(rolloutPercent, forKey: .rolloutPercent)
        try container.encodeIfPresent(rules, forKey: .rules)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(stack, forKey: .stack)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(group, forKey: .group)
        try container.encodeIfPresent(ownerEmail, forKey: .ownerEmail)
    }
}

