//
// UpdateGateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update returns only the id — re-fetch via &#x60;GET /api/admin/gates&#x60; for the full row. */
public struct UpdateGateResponse: Codable, JSONEncodable {

    /** Gate id that was updated. */
    public var id: String

    public init(id: String) {
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
    }
}


