//
// UpdateTriggerConnectorRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/connectors/{id}/trigger&#x60;, discriminated on &#x60;provider&#x60;. Edits an existing trigger connector: the non-secret &#x60;config&#x60; is always supplied and replaces the stored config wholesale; &#x60;name&#x60; and the credential secret(s) are optional (a supplied secret rotates just that key, a blank/omitted one leaves the stored cipher untouched). */
public enum UpdateTriggerConnectorRequest: Codable, JSONEncodable {
    case typeUpdateClaudeTriggerRequest(UpdateClaudeTriggerRequest)
    case typeUpdateCopilotTriggerRequest(UpdateCopilotTriggerRequest)
    case typeUpdateCursorTriggerRequest(UpdateCursorTriggerRequest)
    case typeUpdateJulesTriggerRequest(UpdateJulesTriggerRequest)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateClaudeTriggerRequest(let value):
            try container.encode(value)
        case .typeUpdateCopilotTriggerRequest(let value):
            try container.encode(value)
        case .typeUpdateCursorTriggerRequest(let value):
            try container.encode(value)
        case .typeUpdateJulesTriggerRequest(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case provider = "provider"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .provider)

        switch discriminatorValue {
        case "claude_trigger":
            self = .typeUpdateClaudeTriggerRequest(try UpdateClaudeTriggerRequest(from: decoder))
        case "copilot_trigger":
            self = .typeUpdateCopilotTriggerRequest(try UpdateCopilotTriggerRequest(from: decoder))
        case "cursor_trigger":
            self = .typeUpdateCursorTriggerRequest(try UpdateCursorTriggerRequest(from: decoder))
        case "jules_trigger":
            self = .typeUpdateJulesTriggerRequest(try UpdateJulesTriggerRequest(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for UpdateTriggerConnectorRequest"
                )
            )
        }
    }
}

