//
// UpdateConfigRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/configs/{id}&#x60;. Partial — only supplied fields change. &#x60;value&#x60; republishes on every env. */
public struct UpdateConfigRequest: Codable, JSONEncodable {

    public static let folderRule = StringRule(minLength: nil, maxLength: 256, pattern: "/^[a-zA-Z0-9_-]+$/")
    /** Replacement schema. When supplied, the new schema is validated against every published value before it lands. */
    public var schema: [String: AnyCodable]?
    public var value: AnyCodable?
    /** Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    public var folder: String?

    public init(schema: [String: AnyCodable]? = nil, value: AnyCodable? = nil, folder: String? = nil) {
        self.schema = schema
        self.value = value
        self.folder = folder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schema
        case value
        case folder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schema, forKey: .schema)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(folder, forKey: .folder)
    }
}

