//
// UpdateI18nKeyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PUT /api/admin/i18n/keys/{id}&#x60;. Updates one existing key&#39;s value. */
public struct UpdateI18nKeyRequest: Codable, JSONEncodable {

    public static let variablesRule = ArrayRule(minItems: nil, maxItems: 32, uniqueItems: false)
    /** New value for the key (the only overwrite path). */
    public var value: String
    /** Optional human note to store with the key. */
    public var description: String?
    /** Explicit `{{var}}` placeholder names in the value. Omit to auto-derive them from the value. */
    public var variables: [String]?

    public init(value: String, description: String? = nil, variables: [String]? = nil) {
        self.value = value
        self.description = description
        self.variables = variables
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case description
        case variables
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(variables, forKey: .variables)
    }
}

