//
// UpdateClaudeTriggerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Per-provider PATCH body for editing an existing &#x60;claude_trigger&#x60; connector (the dashboard \&quot;Triggers\&quot; tab). The non-secret &#x60;config&#x60; is always supplied and replaces the stored config wholesale; &#x60;name&#x60; and &#x60;token&#x60; are optional. */
public struct UpdateClaudeTriggerRequest: Codable, JSONEncodable {

    public enum Provider: String, Codable, CaseIterable {
        case claudeTrigger = "claude_trigger"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 80, pattern: nil)
    public static let tokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Discriminator. Claude Code scheduled-routine trigger. */
    public var provider: Provider
    /** New connector label. Optional — omit to leave it unchanged. */
    public var name: String?
    public var config: ClaudeTriggerConfig
    /** New fire bearer token (secret). Optional — a blank/omitted token leaves the stored cipher untouched; a supplied one replaces it. Encrypted; never returned. */
    public var token: String?

    public init(provider: Provider, name: String? = nil, config: ClaudeTriggerConfig, token: String? = nil) {
        self.provider = provider
        self.name = name
        self.config = config
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case name
        case config
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(config, forKey: .config)
        try container.encodeIfPresent(token, forKey: .token)
    }
}

