//
// UpdateAttributeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/attributes/{id}&#x60;. Every field is optional; &#x60;name&#x60; is immutable. */
public struct UpdateAttributeRequest: Codable, JSONEncodable {

    public var type: AttributeType?
    /** Replacement allowed values (for `enum`), or `null` to clear. */
    public var enumValues: [String]?
    /** Whether the attribute must be present on the evaluation context. */
    public var _required: Bool?
    /** Optional human note shown in the dashboard. */
    public var description: String?
    /** Optional dotted path the SDK reads the value from. */
    public var sdkPath: String?

    public init(type: AttributeType? = nil, enumValues: [String]? = nil, _required: Bool? = nil, description: String? = nil, sdkPath: String? = nil) {
        self.type = type
        self.enumValues = enumValues
        self._required = _required
        self.description = description
        self.sdkPath = sdkPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case enumValues = "enum_values"
        case _required = "required"
        case description
        case sdkPath = "sdk_path"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(enumValues, forKey: .enumValues)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(sdkPath, forKey: .sdkPath)
    }
}

