//
// UpdateConnectorRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/connectors/{id}&#x60;. Partial — only supplied fields change. Array/object fields (&#x60;events&#x60;, &#x60;config&#x60;) replace, not merge. */
public struct UpdateConnectorRequest: Codable, JSONEncodable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 80, pattern: nil)
    /** New connector label. */
    public var name: String?
    /** Toggle the connector on/off. */
    public var enabled: Bool?
    /** Replaces the subscribed-events list wholesale. An empty array unsubscribes the connector from every event (e.g. turning off a trigger's auto-fire). */
    public var events: [ConnectorEvent]?
    /** Replaces the non-secret config wholesale. Secrets are never set through this endpoint. */
    public var config: [String: AnyCodable]?

    public init(name: String? = nil, enabled: Bool? = nil, events: [ConnectorEvent]? = nil, config: [String: AnyCodable]? = nil) {
        self.name = name
        self.enabled = enabled
        self.events = events
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case enabled
        case events
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

