//
// UpdateProjectRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for &#x60;PATCH /api/admin/projects/{id}&#x60;. Partial — every field is optional; only supplied fields change. The project id in the path must match the caller&#39;s own project. */
public struct UpdateProjectRequest: Codable, JSONEncodable {

    public enum DefaultEnv: String, Codable, CaseIterable {
        case dev = "dev"
        case staging = "staging"
        case prod = "prod"
    }
    public enum StatMethod: String, Codable, CaseIterable {
        case sequential = "sequential"
        case fixed = "fixed"
        case bayesian = "bayesian"
    }
    public enum SigThreshold: String, Codable, CaseIterable {
        case _001 = "0.01"
        case _005 = "0.05"
        case _010 = "0.10"
    }
    public static let nameRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let domainRule = StringRule(minLength: 1, maxLength: 2048, pattern: "/^(\\*|(\\*\\.)?[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+)$/")
    public static let slugRule = StringRule(minLength: 2, maxLength: 48, pattern: "/^[a-z0-9](?:[a-z0-9-]{0,46}[a-z0-9])?$/")
    public static let timezoneRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let minSampleDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 365, exclusiveMaximum: false, multipleOf: nil)
    public static let minSampleSizeRule = NumericRule<Int>(minimum: 2, exclusiveMinimum: false, maximum: 1000000, exclusiveMaximum: false, multipleOf: nil)
    public static let minRuntimeDaysRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 365, exclusiveMaximum: false, multipleOf: nil)
    public static let defaultPowerRule = NumericRule<Double>(minimum: 0.5, exclusiveMinimum: false, maximum: 0.99, exclusiveMaximum: false, multipleOf: nil)
    public static let ciConfidenceRule = NumericRule<Double>(minimum: 0.5, exclusiveMinimum: false, maximum: 0.999, exclusiveMaximum: false, multipleOf: nil)
    public static let defaultAllocationPctRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let defaultWinsorizePctRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 99, exclusiveMaximum: false, multipleOf: nil)
    public static let defaultMeiRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public static let cupedBaselineDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 365, exclusiveMaximum: false, multipleOf: nil)
    public static let cupedMinOverlapRule = NumericRule<Double>(minimum: 0.01, exclusiveMinimum: false, maximum: 0.99, exclusiveMaximum: false, multipleOf: nil)
    public static let cupedMinBaselineUsersRule = NumericRule<Int>(minimum: 10, exclusiveMinimum: false, maximum: 100000, exclusiveMaximum: false, multipleOf: nil)
    public static let msprtTauMeiFactorRule = NumericRule<Double>(minimum: 0.1, exclusiveMinimum: false, maximum: 2, exclusiveMaximum: false, multipleOf: nil)
    public static let msprtTauSdFactorRule = NumericRule<Double>(minimum: 0.05, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public static let srmThresholdRule = NumericRule<Double>(minimum: 0.00010, exclusiveMinimum: false, maximum: 0.05, exclusiveMaximum: false, multipleOf: nil)
    /** New project name. */
    public var name: String?
    /** Lowercase bare hostname (e.g. `acme.com`, `app.acme.com`, `*.acme.com`), or `*` to allow any origin. Full URLs with `https://` are not accepted. The project is keyed by `(owner_email, domain)`, so a second call with the same domain returns the existing project. */
    public var domain: String?
    /** URL-safe identifier used in app URLs and SDK config. Lowercase letters, numbers, and hyphens; 2–48 chars; cannot start or end with a hyphen. The caller lowercases the raw slug before sending. */
    public var slug: String?
    /** Default environment new resources are scoped to. */
    public var defaultEnv: DefaultEnv?
    /** IANA timezone the project's daily analysis runs in. */
    public var timezone: String?
    /** Statistical method the experiment analyzer uses. */
    public var statMethod: StatMethod?
    /** Significance threshold (alpha) for experiment analysis. */
    public var sigThreshold: SigThreshold?
    /** Whether a failing guardrail auto-rolls back the experiment. */
    public var autoRollback: Bool?
    /** Minimum number of days an experiment must run before it can be called. */
    public var minSampleDays: Int?
    /** Enable/disable the i18n/translations module. */
    public var moduleTranslations: Bool?
    /** Enable/disable the dynamic-configs module. */
    public var moduleConfigs: Bool?
    /** Enable/disable the feature-gates module. */
    public var moduleGates: Bool?
    /** Enable/disable the experiments module. */
    public var moduleExperiments: Bool?
    /** Enable/disable the feedback/ops module. */
    public var moduleFeedback: Bool?
    /** Enable/disable the user-management module. */
    public var moduleUser: Bool?
    /** Enable/disable the events module. */
    public var moduleEvents: Bool?
    /** Verdict power guard — minimum users per arm before a ship/hold verdict. */
    public var minSampleSize: Int?
    /** Minimum days an experiment must run before a verdict (peeking guard). */
    public var minRuntimeDays: Int?
    /** Target statistical power (1−β) feeding the realized-MDE calculation. */
    public var defaultPower: Double?
    /** Confidence level for the interval surfaced on results (any value in [0.5, 0.999], e.g. 0.90, 0.95, 0.975, 0.99). */
    public var ciConfidence: Double?
    /** Default traffic allocation (basis points, 1000 = 10%) new experiments start with; overridable per experiment. */
    public var defaultAllocationPct: Int?
    /** Default winsorization percentile new metrics start with; overridable per metric. */
    public var defaultWinsorizePct: Int?
    /** Default minimum effect of interest (relative, 0–1) new metrics start with; overridable per metric and per experiment. Null clears it. */
    public var defaultMei: Double?
    /** CUPED baseline window — days of pre-experiment history, frozen at start. */
    public var cupedBaselineDays: Int?
    /** CUPED selection-bias guard — min share of users with a baseline, else skip. */
    public var cupedMinOverlap: Double?
    /** CUPED — minimum users with a baseline before it runs at all. */
    public var cupedMinBaselineUsers: Int?
    /** mSPRT prior width — τ = minimum effect of interest × this factor. */
    public var msprtTauMeiFactor: Double?
    /** mSPRT fallback prior width — τ = this × control SD when no MEI is set. */
    public var msprtTauSdFactor: Double?
    /** SRM chi-square p-value below which the run is called invalid. */
    public var srmThreshold: Double?

    public init(name: String? = nil, domain: String? = nil, slug: String? = nil, defaultEnv: DefaultEnv? = nil, timezone: String? = nil, statMethod: StatMethod? = nil, sigThreshold: SigThreshold? = nil, autoRollback: Bool? = nil, minSampleDays: Int? = nil, moduleTranslations: Bool? = nil, moduleConfigs: Bool? = nil, moduleGates: Bool? = nil, moduleExperiments: Bool? = nil, moduleFeedback: Bool? = nil, moduleUser: Bool? = nil, moduleEvents: Bool? = nil, minSampleSize: Int? = nil, minRuntimeDays: Int? = nil, defaultPower: Double? = nil, ciConfidence: Double? = nil, defaultAllocationPct: Int? = nil, defaultWinsorizePct: Int? = nil, defaultMei: Double? = nil, cupedBaselineDays: Int? = nil, cupedMinOverlap: Double? = nil, cupedMinBaselineUsers: Int? = nil, msprtTauMeiFactor: Double? = nil, msprtTauSdFactor: Double? = nil, srmThreshold: Double? = nil) {
        self.name = name
        self.domain = domain
        self.slug = slug
        self.defaultEnv = defaultEnv
        self.timezone = timezone
        self.statMethod = statMethod
        self.sigThreshold = sigThreshold
        self.autoRollback = autoRollback
        self.minSampleDays = minSampleDays
        self.moduleTranslations = moduleTranslations
        self.moduleConfigs = moduleConfigs
        self.moduleGates = moduleGates
        self.moduleExperiments = moduleExperiments
        self.moduleFeedback = moduleFeedback
        self.moduleUser = moduleUser
        self.moduleEvents = moduleEvents
        self.minSampleSize = minSampleSize
        self.minRuntimeDays = minRuntimeDays
        self.defaultPower = defaultPower
        self.ciConfidence = ciConfidence
        self.defaultAllocationPct = defaultAllocationPct
        self.defaultWinsorizePct = defaultWinsorizePct
        self.defaultMei = defaultMei
        self.cupedBaselineDays = cupedBaselineDays
        self.cupedMinOverlap = cupedMinOverlap
        self.cupedMinBaselineUsers = cupedMinBaselineUsers
        self.msprtTauMeiFactor = msprtTauMeiFactor
        self.msprtTauSdFactor = msprtTauSdFactor
        self.srmThreshold = srmThreshold
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case domain
        case slug
        case defaultEnv
        case timezone
        case statMethod
        case sigThreshold
        case autoRollback
        case minSampleDays
        case moduleTranslations
        case moduleConfigs
        case moduleGates
        case moduleExperiments
        case moduleFeedback
        case moduleUser
        case moduleEvents
        case minSampleSize
        case minRuntimeDays
        case defaultPower
        case ciConfidence
        case defaultAllocationPct
        case defaultWinsorizePct
        case defaultMei
        case cupedBaselineDays
        case cupedMinOverlap
        case cupedMinBaselineUsers
        case msprtTauMeiFactor
        case msprtTauSdFactor
        case srmThreshold
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(defaultEnv, forKey: .defaultEnv)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(statMethod, forKey: .statMethod)
        try container.encodeIfPresent(sigThreshold, forKey: .sigThreshold)
        try container.encodeIfPresent(autoRollback, forKey: .autoRollback)
        try container.encodeIfPresent(minSampleDays, forKey: .minSampleDays)
        try container.encodeIfPresent(moduleTranslations, forKey: .moduleTranslations)
        try container.encodeIfPresent(moduleConfigs, forKey: .moduleConfigs)
        try container.encodeIfPresent(moduleGates, forKey: .moduleGates)
        try container.encodeIfPresent(moduleExperiments, forKey: .moduleExperiments)
        try container.encodeIfPresent(moduleFeedback, forKey: .moduleFeedback)
        try container.encodeIfPresent(moduleUser, forKey: .moduleUser)
        try container.encodeIfPresent(moduleEvents, forKey: .moduleEvents)
        try container.encodeIfPresent(minSampleSize, forKey: .minSampleSize)
        try container.encodeIfPresent(minRuntimeDays, forKey: .minRuntimeDays)
        try container.encodeIfPresent(defaultPower, forKey: .defaultPower)
        try container.encodeIfPresent(ciConfidence, forKey: .ciConfidence)
        try container.encodeIfPresent(defaultAllocationPct, forKey: .defaultAllocationPct)
        try container.encodeIfPresent(defaultWinsorizePct, forKey: .defaultWinsorizePct)
        try container.encodeIfPresent(defaultMei, forKey: .defaultMei)
        try container.encodeIfPresent(cupedBaselineDays, forKey: .cupedBaselineDays)
        try container.encodeIfPresent(cupedMinOverlap, forKey: .cupedMinOverlap)
        try container.encodeIfPresent(cupedMinBaselineUsers, forKey: .cupedMinBaselineUsers)
        try container.encodeIfPresent(msprtTauMeiFactor, forKey: .msprtTauMeiFactor)
        try container.encodeIfPresent(msprtTauSdFactor, forKey: .msprtTauSdFactor)
        try container.encodeIfPresent(srmThreshold, forKey: .srmThreshold)
    }
}

